// Business Analyst 用の暗記フラッシュカード。front=用語/質問, back=説明/答え。
export const flashcards = [
  {
    id: 'ba-fc-1',
    domain: 'ba-discovery',
    front: 'BA・PM・アーキテクト・管理者の役割の違いは？',
    back: 'BA=何を・なぜ作るかを定義（要件の中身に責任）。PM=スコープ/スケジュール/予算/リスクの管理。アーキテクト=技術的な実現方式の設計。管理者=Salesforce 上での構築・運用。',
  },
  {
    id: 'ba-fc-2',
    domain: 'ba-discovery',
    front: 'ウォーターフォールとアジャイルの使い分けは？',
    back: 'ウォーターフォール=要件が安定・規制/監査で事前承認が必要・固定価格契約。アジャイル=要件が流動的・早期に価値を出したい・フィードバックで磨きたい。折衷がハイブリッド。',
  },
  {
    id: 'ba-fc-3',
    domain: 'ba-discovery',
    front: 'Scrum の3ロールとその責任は？',
    back: 'プロダクトオーナー=何を作るか（バックログの優先順位）。スクラムマスター=プロセス支援と障害除去。開発チーム=どう作るかと見積り。BA は公式ロールではなくPOを支援する。',
  },
  {
    id: 'ba-fc-4',
    domain: 'ba-discovery',
    front: 'スプリントレビューとレトロスペクティブの違いは？',
    back: 'レビュー=成果物をステークホルダーに見せてフィードバックを得る（プロダクト）。レトロスペクティブ=チームの進め方を改善する振り返り（プロセス）。',
  },
  {
    id: 'ba-fc-5',
    domain: 'ba-discovery',
    front: '引き出し(Elicitation)手法の使い分けは？',
    back: '深い業務ルール=インタビュー／SME。合意形成=ワークショップ。実態把握=観察(ジョブシャドウイング)。分散した多人数=アンケート。イメージ共有=プロトタイピング。前提知識=ドキュメント分析。',
  },
  {
    id: 'ba-fc-6',
    domain: 'ba-collaboration',
    front: 'ステークホルダー分析の4象限（影響力×関心度）は？',
    back: '高×高=密接に管理。高×低=満足させておく（要点のみ報告）。低×高=情報提供を継続。低×低=監視。影響力が高いのに関心が低い層が最も危険。',
  },
  {
    id: 'ba-fc-7',
    domain: 'ba-collaboration',
    front: 'RACI の4つの記号は？',
    back: 'R=Responsible(実行責任・複数可)、A=Accountable(説明責任/最終承認・各項目1人だけ)、C=Consulted(相談先)、I=Informed(報告先)。A が曖昧だと決まらない。',
  },
  {
    id: 'ba-fc-8',
    domain: 'ba-collaboration',
    front: 'パーキングロットとは？',
    back: '会議中に出た本題以外の重要な論点を一時的に記録するリスト。議論を止めずに脱線を扱える。会議後に担当と期限を付けて必ず処理する。',
  },
  {
    id: 'ba-fc-9',
    domain: 'ba-collaboration',
    front: '変更管理(OCM)と変更要求管理の違いは？',
    back: 'OCM=人と組織を新しい働き方へ移行させ定着させる活動（コミュニケーション/トレーニング/チャンピオン）。変更要求管理=要件の変更を受付・影響分析・承認するプロセス。',
  },
  {
    id: 'ba-fc-10',
    domain: 'ba-collaboration',
    front: '抵抗への最も効果的な対処は？',
    back: '早期にユーザーを巻き込むこと。加えて「自分にとって何が良くなるか(WIIFM)」を具体的に伝える、スポンサーの可視的支持、各部署のチェンジチャンピオンの起用。',
  },
  {
    id: 'ba-fc-11',
    domain: 'ba-process',
    front: 'プロセス図の使い分けは？',
    back: '部門間の受け渡し=スイムレーン図。顧客体験=ジャーニーマップ。システムの振る舞い=ユースケース。時間のムダ=バリューストリームマップ。厳密な標準記法=BPMN。',
  },
  {
    id: 'ba-fc-12',
    domain: 'ba-process',
    front: 'As-Is を描くときの鉄則は？',
    back: '「実際に行われていること」を描く。公式手順から逸脱したワークアラウンドと例外パスも含める。理想（改善案）は混ぜない。最後に実務担当者にレビューしてもらい検証する。',
  },
  {
    id: 'ba-fc-13',
    domain: 'ba-process',
    front: 'ギャップ分析とは？',
    back: 'As-Is と To-Be の差分を洗い出し、埋めるために必要な変更を特定すること。変更にはシステム機能だけでなく、業務ルール・役割分担・トレーニングも含まれる。',
  },
  {
    id: 'ba-fc-14',
    domain: 'ba-process',
    front: 'プロセス改善を検討する順序は？',
    back: 'なくす(Eliminate) → 単純にする(Simplify) → 標準化する(Standardize) → 自動化する(Automate)。いきなり自動化しない。標準化前の自動化は保守不能な仕組みを生む。',
  },
  {
    id: 'ba-fc-15',
    domain: 'ba-requirements',
    front: '要件の種類は？',
    back: 'ビジネス要件(組織の目的)、ステークホルダー要件(特定グループのニーズ)、機能要件(振る舞い)、非機能要件(性能/セキュリティ等の品質特性)、移行要件(移行期間だけ必要)。ほかに制約・前提・ビジネスルール。',
  },
  {
    id: 'ba-fc-16',
    domain: 'ba-requirements',
    front: '良い要件の条件は？',
    back: '明確・簡潔・完全・一貫・検証可能(Testable)・実現可能・追跡可能・優先順位付き。曖昧語（速い/使いやすい/必要に応じて）を排し、1要件1事項、実装方式は書かない。',
  },
  {
    id: 'ba-fc-17',
    domain: 'ba-requirements',
    front: 'MoSCoW の4分類は？',
    back: 'Must have(必須)、Should have(重要だが代替可能)、Could have(あれば良い)、Wont have(今回はやらない=明示的な合意)。Wont have の明示がスコープ管理の要点。',
  },
  {
    id: 'ba-fc-18',
    domain: 'ba-requirements',
    front: '検証(Verification)と妥当性確認(Validation)の違いは？',
    back: 'Verification=要件を「正しく作っているか」（品質基準の充足）。Validation=「正しい要件を作っているか」（ビジネス目標への寄与）。',
  },
  {
    id: 'ba-fc-19',
    domain: 'ba-requirements',
    front: 'トレーサビリティと RTM とは？',
    back: 'ビジネス要件→ソリューション要件/ストーリー→設計→テストケース→実装の対応をたどれる状態。RTM(要件トレーサビリティマトリクス)で一覧化し、抜けの検出と影響分析に使う。',
  },
  {
    id: 'ba-fc-20',
    domain: 'ba-user-stories',
    front: 'ユーザーストーリーの書式は？',
    back: '「〈役割〉として、〈やりたいこと〉をしたい。なぜなら〈得たい価値〉だからだ。」役割は具体的に。「なぜなら」がないと優先順位も代替案も判断できない。',
  },
  {
    id: 'ba-fc-21',
    domain: 'ba-user-stories',
    front: 'INVEST の6要素は？',
    back: 'Independent(独立)、Negotiable(交渉可能)、Valuable(価値がある)、Estimable(見積り可能)、Small(小さい)、Testable(テスト可能)。',
  },
  {
    id: 'ba-fc-22',
    domain: 'ba-user-stories',
    front: '受け入れ基準 / DoD / DoR の違いは？',
    back: '受け入れ基準=そのストーリー固有の合格条件。Definition of Done=全ストーリー共通のチーム標準（テスト済み等）。Definition of Ready=スプリントに取り込める状態の条件。',
  },
  {
    id: 'ba-fc-23',
    domain: 'ba-user-stories',
    front: 'ストーリーポイントとベロシティは？',
    back: 'ストーリーポイント=作業量・複雑さ・不確実性を合わせた相対規模（時間ではない）。ベロシティ=1スプリントで完了できたポイントの実績値。自チームの計画にのみ使う。',
  },
  {
    id: 'ba-fc-24',
    domain: 'ba-user-stories',
    front: 'ストーリー分割の原則は？',
    back: '価値の縦割りで分ける（工程で割らない）。切り口は、業務ルール別・データ種別・ユーザー役割別・正常系と例外系・CRUD別・手動版と自動版。',
  },
  {
    id: 'ba-fc-25',
    domain: 'ba-acceptance',
    front: 'テストレベルの違いは？',
    back: '単体=個々の機能（開発者）。結合=連携とデータの流れ。回帰=既存機能が壊れていないか。UAT=業務が回るかをビジネス視点で確認（業務ユーザーが実施、BA は計画・支援）。',
  },
  {
    id: 'ba-fc-26',
    domain: 'ba-acceptance',
    front: 'UAT の開始基準と終了基準は？',
    back: '開始基準=結合テスト完了・重大欠陥ゼロ・環境とデータの準備・参加者のトレーニング済み。終了基準=全シナリオ実施済み・重大欠陥の解消・ビジネスオーナーのサインオフ。',
  },
  {
    id: 'ba-fc-27',
    domain: 'ba-acceptance',
    front: '重大度(Severity)と優先度(Priority)の違いは？',
    back: '重大度=業務への影響の大きさ（Critical/High/Medium/Low）。優先度=対応の緊急度。重大でも回避策があれば優先度は下がることがある。',
  },
  {
    id: 'ba-fc-28',
    domain: 'ba-acceptance',
    front: '切り替え方式の4種は？',
    back: 'ビッグバン=一斉切替（速いがリスク集中）。段階導入=部署/機能ごとに順次。並行稼働=新旧を一定期間併用（安全だが負荷大）。パイロット=一部先行導入。',
  },
  {
    id: 'ba-fc-29',
    domain: 'ba-acceptance',
    front: 'ハイパーケアとは？',
    back: 'リリース直後の2〜4週間程度の集中サポート期間。問い合わせに即応し、傾向を分析して追加トレーニングや軽微な調整を行い、初期の不満の蓄積を防ぐ。',
  },
  {
    id: 'ba-fc-30',
    domain: 'ba-acceptance',
    front: '価値測定に必要な前提は？',
    back: 'リリース前に KPI の現状値（ベースライン）を測定しておくこと。これがないと改善を証明できず ROI も語れない。ディスカバリー段階での記録が生きる。',
  },
]

export const flashcardsByDomain = (domainId) => flashcards.filter((f) => f.domain === domainId)
