export const requirementsQuestions = [
  {
    id: 'req-1',
    domain: 'ba-requirements',
    type: 'mcq',
    question: '「画面の表示は3秒以内に完了すること」はどの種類の要件か。',
    options: [
      { text: '非機能要件(Non-Functional Requirement)', correct: true, note: '正解。性能・可用性・セキュリティなどの品質特性は非機能要件。' },
      { text: '機能要件(Functional Requirement)', correct: false, note: '機能要件はシステムが提供する振る舞い。性能は品質特性。' },
      { text: 'ビジネス要件(Business Requirement)', correct: false, note: 'ビジネス要件は組織の目的レベル（例：営業サイクル20%短縮）。' },
      { text: '移行要件(Transition Requirement)', correct: false, note: '移行要件は新旧移行の間だけ必要な要件。' },
    ],
    explanation: '非機能要件は性能、可用性、セキュリティ、監査、保守性、ユーザビリティなどの品質特性や制約。見落とされやすく、後半で発覚すると設計に大きな影響が出る。',
    reference: '💡 非機能要件の抜けは大きな手戻りの原因。「速さ・量・時間・セキュリティ・保持期間」を意識的に聞き出す。',
  },
  {
    id: 'req-2',
    domain: 'ba-requirements',
    type: 'mcq',
    question: '「過去2年分の商談データを新システムに移行する」はどの種類の要件か。',
    options: [
      { text: '移行要件(Transition Requirement)', correct: true, note: '正解。移行期間だけ必要で、稼働後は不要になるのが特徴。' },
      { text: '機能要件', correct: false, note: '恒常的なシステムの振る舞いではない。' },
      { text: '非機能要件', correct: false, note: '品質特性ではない。' },
      { text: 'ビジネスルール', correct: false, note: '組織の方針・規則ではない。' },
    ],
    explanation: '移行要件は現行から新システムへ移る間だけ必要な要件。データ移行、並行稼働、旧システムの停止手順などが該当し、稼働後は不要になる。',
    reference: '💡 移行要件は忘れられやすい。データ移行の対象・件数・変換ルール・重複判定は早期に要件化する。',
  },
  {
    id: 'req-3',
    domain: 'ba-requirements',
    type: 'mcq',
    question: '「割引率20%超は部長承認が必要」という組織の方針は何と呼ばれるか。',
    options: [
      { text: 'ビジネスルール(Business Rule)', correct: true, note: '正解。組織の方針・規則そのもので、複数の機能から参照される。' },
      { text: '非機能要件', correct: false, note: '品質特性ではない。' },
      { text: '受け入れ基準', correct: false, note: '受け入れ基準は特定ストーリーの合格条件。' },
      { text: '前提(Assumption)', correct: false, note: '前提は「そうだと仮定して進める事柄」。' },
    ],
    explanation: 'ビジネスルールは要件とは別に一覧管理する。複数の機能から参照されるため、一元管理しておくと変更時の影響範囲が把握しやすい。',
    reference: '💡 制約(Constraint)＝動かせない条件、前提(Assumption)＝仮定、ビジネスルール＝組織の規則。3つを区別する。',
  },
  {
    id: 'req-4',
    domain: 'ba-requirements',
    type: 'mcq',
    question: '「システムは使いやすいこと」という要件の最大の問題点はどれか。',
    options: [
      { text: '検証可能(Testable)でない', correct: true, note: '正解。合否を判定できない要件は受け入れ時に紛糾する。' },
      { text: '優先順位が付いていない', correct: false, note: '優先順位も必要だが、この文の根本的な問題は検証不能な点。' },
      { text: '実装方式が書かれていない', correct: false, note: '実装方式は要件に書くべきでない。' },
      { text: 'ビジネス価値が書かれていない', correct: false, note: '価値の記述も重要だが、この要件の致命的な欠陥は検証不能なこと。' },
    ],
    explanation: '良い要件の条件は、明確・簡潔・完全・一貫・検証可能・実現可能・追跡可能・優先順位付き。「使いやすい」「速い」「柔軟な」といった曖昧語は要件から排除する。',
    reference: '💡 「3クリック以内で登録を完了できる」のように、数値・条件・対象を明示すると検証可能になる。',
  },
  {
    id: 'req-5',
    domain: 'ba-requirements',
    type: 'mcq',
    question: 'MoSCoW 法における「Wont have」の正しい意味はどれか。',
    options: [
      { text: '今回のリリースではやらないと明示的に合意された項目', correct: true, note: '正解。スコープ外を文書化することで期待値を管理する。' },
      { text: '永久に実装しない項目', correct: false, note: '将来のリリースで実施される可能性はある。' },
      { text: '実現不可能な項目', correct: false, note: '実現可能性の判定ではなく、今回のスコープの判定。' },
      { text: '優先順位が未定の項目', correct: false, note: '未定ではなく、やらないと決定した項目。' },
    ],
    explanation: 'MoSCoW は Must have(必須)、Should have(重要だが代替可能)、Could have(あれば良い)、Wont have(今回はやらない)。Wont have を明示することがスコープ管理の要点。',
    reference: '💡 「全部 Must」と主張する関係者には、「リリース初日に絶対必要か？」と問うと切り分けられる。',
  },
  {
    id: 'req-6',
    domain: 'ba-requirements',
    type: 'mcq',
    question: '要件トレーサビリティマトリクス(RTM)の主な用途はどれか。',
    options: [
      { text: '各要件がどのストーリー・テストケース・成果物に対応するかを追跡し、抜けを発見する', correct: true, note: '正解。「テストされていない要件」「要件のない実装」を検出できる。' },
      { text: 'プロジェクトの予算執行状況を管理する', correct: false, note: '予算管理の道具ではない。' },
      { text: '欠陥の再現手順を記録する', correct: false, note: 'それは欠陥報告の役割。' },
      { text: 'ステークホルダーの影響度を分類する', correct: false, note: 'それはステークホルダー分析マトリクス。' },
    ],
    explanation: 'トレーサビリティは、ビジネス要件 → ソリューション要件／ストーリー → 設計 → テストケース → 実装 という対応をたどれる状態。影響分析にも使える。',
    reference: '💡 「この要件を変えると、どのテストと機能に影響するか」が即座に分かるのが実利。',
  },
  {
    id: 'req-7',
    domain: 'ba-requirements',
    type: 'mcq',
    question: 'スコープクリープ(Scope Creep)の説明として正しいものはどれか。',
    options: [
      { text: '正式な承認なしに要件が少しずつ増えていく現象', correct: true, note: '正解。「ついでにこれも」の積み重ねが納期とコストを壊す。' },
      { text: '要件が承認プロセスを経て正式に変更されること', correct: false, note: 'それは正常な変更管理。' },
      { text: 'スプリントのベロシティが低下すること', correct: false, note: 'ベロシティの話ではない。' },
      { text: '要件の優先順位が入れ替わること', correct: false, note: '優先順位の変更自体はスコープクリープではない。' },
    ],
    explanation: 'スコープクリープを防ぐには、変更要求を正式なプロセス（受付 → 影響分析 → 承認／却下 → ベースライン反映）に乗せる。BA は影響を可視化する役割を担う。',
    reference: '💡 BA は変更を断る役ではない。影響を示し、意思決定者が判断できる材料を出す。',
  },
  {
    id: 'req-8',
    domain: 'ba-requirements',
    type: 'mcq',
    question: '要件の「検証(Verification)」と「妥当性確認(Validation)」の違いとして正しいものはどれか。',
    options: [
      { text: '検証は「要件を正しく作っているか」、妥当性確認は「正しい要件を作っているか」', correct: true, note: '正解。品質基準の充足か、ビジネス目標への寄与か、の違い。' },
      { text: 'どちらも同じ意味である', correct: false, note: '目的が異なる別の活動。' },
      { text: '検証は UAT、妥当性確認は単体テストのことである', correct: false, note: 'テストレベルの話ではない。' },
      { text: '検証は開発者、妥当性確認は BA だけが行う', correct: false, note: '担当者で区別するものではない。' },
    ],
    explanation: '検証(Verification)＝明確・完全・一貫・検証可能といった品質基準を満たしているかのチェック。妥当性確認(Validation)＝その要件が本当にビジネス目標の達成に寄与するかのチェック。',
    reference: '💡 「正しく作る(Verification)」と「正しいものを作る(Validation)」の対比で覚える。',
  },
  {
    id: 'req-9',
    domain: 'ba-requirements',
    type: 'mcq',
    question: 'デシジョンテーブル（決定表）を使うのに最も適した場面はどれか。',
    options: [
      { text: '複数条件の組み合わせで結果が変わる複雑なビジネスルールを網羅的に整理したいとき', correct: true, note: '正解。条件の組み合わせ漏れを防げる。' },
      { text: '業務の流れと担当者を可視化したいとき', correct: false, note: 'それはスイムレーン図。' },
      { text: 'ステークホルダーの影響度を分類したいとき', correct: false, note: 'それはステークホルダー分析。' },
      { text: '顧客体験の改善点を見つけたいとき', correct: false, note: 'それはジャーニーマップ。' },
    ],
    explanation: 'デシジョンテーブルは条件の組み合わせと結果を表形式で網羅する技法。承認ルート、割引率、料金計算など、条件分岐が複雑なルールの抜け漏れ防止に有効。',
    reference: '💡 条件が3つあれば組み合わせは最大8通り。表にすると未定義のケースが一目で分かる。',
  },
  {
    id: 'req-10',
    domain: 'ba-requirements',
    type: 'mcq',
    question: 'データ辞書(Data Dictionary)に記載する情報として適切なものはどれか。',
    options: [
      { text: '項目の名称、データ型、桁数、必須／任意、選択肢、意味', correct: true, note: '正解。実装時の解釈違いを防ぐための定義集。' },
      { text: '業務用語の一般的な意味', correct: false, note: 'それは用語集(Glossary)。' },
      { text: '各ステークホルダーの連絡先', correct: false, note: 'ステークホルダー一覧の情報。' },
      { text: 'テストケースの実行結果', correct: false, note: 'テスト管理の情報。' },
    ],
    explanation: 'データ辞書は項目レベルの定義集で、実装とデータ移行の前提になる。業務用語の意味を定義する用語集(Glossary)とは目的が異なる。',
    reference: '💡 用語集＝言葉の意味、データ辞書＝項目の仕様。この区別は頻出。',
  },
  {
    id: 'req-11',
    domain: 'ba-requirements',
    type: 'mcq',
    question: '要件に「カスタムオブジェクトを新規作成する」と書かれていた。BA としての適切な指摘はどれか。',
    options: [
      { text: '要件には What（何が必要か）を書き、How（実装方式）は書かないべきである', correct: true, note: '正解。実装方式を固定すると、より良い選択肢を排除する。' },
      { text: 'オブジェクト名まで具体的に書くべきである', correct: false, note: 'さらに実装方式に踏み込むことになる。' },
      { text: '問題なく、そのまま承認してよい', correct: false, note: '標準機能で実現できる可能性を閉ざしてしまう。' },
      { text: '開発者が書いた要件なので修正不要である', correct: false, note: '誰が書いたかにかかわらず、要件の書き方は統一する。' },
    ],
    explanation: '「顧客ごとの契約情報を管理できること」のように業務上の必要性で書けば、標準オブジェクトの活用や別の設計も検討できる。実装方式の固定は要件レビューの定番指摘。',
    reference: '💡 要件レビューでは「実装方式が混入していないか」を必ずチェックする。',
  },
  {
    id: 'req-12',
    domain: 'ba-requirements',
    type: 'multi',
    question: '良い要件が満たすべき条件として適切なものを2つ選べ。',
    options: [
      { text: '検証可能である（テストで合否を判定できる）', correct: true, note: '正解。判定できない要件は受け入れ時に紛糾する。' },
      { text: '追跡可能である（一意の ID を持ち、対応関係をたどれる）', correct: true, note: '正解。トレーサビリティと変更管理の前提。' },
      { text: '複数の事項をまとめて記述している', correct: false, note: '1要件1事項が原則。まとめると部分的な合否を判定できない。' },
      { text: '実装方式が具体的に指定されている', correct: false, note: '要件に How は書かない。' },
    ],
    explanation: '良い要件は、明確・簡潔・完全・一貫・検証可能・実現可能・追跡可能・優先順位付き。曖昧語を排し、1要件1事項で書く。',
    reference: '💡 「Aができ、かつBも通知される」は2つに分割する。合否判定の単位を揃えるため。',
  },
  {
    id: 'req-13',
    domain: 'ba-requirements',
    type: 'mcq',
    question: 'ベースライン(Baseline)の説明として正しいものはどれか。',
    options: [
      { text: '正式に承認された時点の要件セットで、以降の変更は差分として管理される', correct: true, note: '正解。変更管理の基準点になる。' },
      { text: 'プロジェクト開始前に測定した KPI の現状値', correct: false, note: 'それは効果測定のベースライン測定。文脈が異なる。' },
      { text: '開発チームの標準的なベロシティ', correct: false, note: 'ベロシティの基準値ではない。' },
      { text: 'テストの合格基準', correct: false, note: 'それは Exit Criteria。' },
    ],
    explanation: '要件のベースラインは、承認済みの要件セット。以降の変更要求はすべてベースラインとの差分として影響分析・承認され、承認されたものだけが反映される。',
    reference: '💡 効果測定の「ベースライン測定」と、要件管理の「ベースライン」は文脈が異なる。両方の意味で出題される。',
  },
  {
    id: 'req-14',
    domain: 'ba-requirements',
    type: 'mcq',
    question: '変更管理委員会(CCB: Change Control Board)の役割はどれか。',
    options: [
      { text: '変更要求を審査し、承認または却下を決定する', correct: true, note: '正解。誰が承認権を持つかを事前に定めておく。' },
      { text: '変更を実装する開発作業を行う', correct: false, note: '実装は開発チームの役割。' },
      { text: '要件の初回作成を行う', correct: false, note: '要件作成は BA の役割。' },
      { text: 'UAT の実施を行う', correct: false, note: 'UAT は業務ユーザーが実施する。' },
    ],
    explanation: '変更要求の扱いは、受付 → 影響分析（工数・コスト・スケジュール・他要件への波及）→ CCB による承認／却下 → 承認分のみベースライン反映、という流れ。',
    reference: '💡 影響分析を行うのは BA。判断するのは CCB や意思決定者、という役割分担を押さえる。',
  },
  {
    id: 'req-15',
    domain: 'ba-requirements',
    type: 'mcq',
    question: '「価値 vs 労力(Value vs Effort)」マトリクスで最初に着手すべき象限はどれか。',
    options: [
      { text: '価値が高く、労力が低いもの（クイックウィン）', correct: true, note: '正解。早期に成果を出し、プロジェクトへの信頼を獲得できる。' },
      { text: '価値が低く、労力が高いもの', correct: false, note: '最も避けるべき象限。' },
      { text: '価値が低く、労力も低いもの', correct: false, note: '着手コストは低いが成果が小さい。優先度は低い。' },
      { text: '価値が高く、労力も高いもの', correct: false, note: '重要だが時間がかかる。クイックウィンの後に計画的に取り組む。' },
    ],
    explanation: 'クイックウィン（高価値・低労力）を早期に出すことで、ステークホルダーの信頼と協力を得やすくなる。高価値・高労力は計画的に、低価値・高労力は原則見送る。',
    reference: '💡 MoSCoW、価値vs労力、Kano モデル、重み付けスコアリング — 手法名と特徴をセットで覚える。',
  },
  {
    id: 'req-16',
    domain: 'ba-requirements',
    type: 'mcq',
    question: 'Kano モデルにおける「当たり前品質」の説明として正しいものはどれか。',
    options: [
      { text: 'あって当然とされ、なければ強い不満を招くが、あっても満足度は上がらない要素', correct: true, note: '正解。基本機能や法令対応が該当する。' },
      { text: 'あるほど満足度が比例して上がる要素', correct: false, note: 'それは一元的品質。' },
      { text: 'あると感動を与える予想外の要素', correct: false, note: 'それは魅力品質。' },
      { text: 'あってもなくても満足度に影響しない要素', correct: false, note: 'それは無関心品質。' },
    ],
    explanation: 'Kano モデルは、当たり前品質(ないと不満)、一元的品質(あるほど満足)、魅力品質(あると感動)に分類し、満足度への寄与から優先度を考える手法。',
    reference: '💡 当たり前品質を落とすと致命的。魅力品質は差別化要素だが、当たり前品質の充足が先。',
  },
  {
    id: 'req-17',
    domain: 'ba-requirements',
    type: 'mcq',
    question: '要件の優先順位を最終的に決定するのは誰か。',
    options: [
      { text: 'ビジネス側（プロダクトオーナー／スポンサー）', correct: true, note: '正解。BA は判断材料を整理する役割。' },
      { text: 'ビジネスアナリスト', correct: false, note: 'BA は独断で優先順位を決めない。' },
      { text: '開発チーム', correct: false, note: '開発チームは見積りと実装方式に責任を持つ。' },
      { text: 'スクラムマスター', correct: false, note: 'プロセス支援が役割で、優先順位は決めない。' },
    ],
    explanation: 'BA は「この要件を落とすと何が起きるか」を示し判断を助けるが、決めるのはビジネス側。この役割分担は BA 試験全体を貫く原則。',
    reference: '💡 「BA は決めない、支援する」。優先順位＝ビジネス側、見積り＝開発チーム。',
  },
  {
    id: 'req-18',
    domain: 'ba-requirements',
    type: 'mcq',
    question: '根本原因分析に用いられる手法の組み合わせとして正しいものはどれか。',
    options: [
      { text: '5 Whys とフィッシュボーン図（特性要因図）', correct: true, note: '正解。表面的な症状から原因を掘り下げる代表的な技法。' },
      { text: 'MoSCoW と Kano モデル', correct: false, note: '優先順位付けの手法。' },
      { text: 'INVEST と Given-When-Then', correct: false, note: 'ユーザーストーリーの品質基準と受け入れ基準の書式。' },
      { text: 'RACI とステークホルダーマトリクス', correct: false, note: 'ステークホルダー分析の道具。' },
    ],
    explanation: '5 Whys は「なぜ」を繰り返して原因を掘り下げる技法。フィッシュボーン図は原因を人・プロセス・システム・環境などに分類して整理する図。',
    reference: '💡 「レポートが欲しい」の 5 Whys で「データが5システムに分散している」が真因と判明する、が典型例。',
  },
  {
    id: 'req-19',
    domain: 'ba-requirements',
    type: 'mcq',
    question: '前提(Assumption)と制約(Constraint)の違いとして正しいものはどれか。',
    options: [
      { text: '前提は「そうだと仮定して進める事柄」、制約は「動かせない条件」', correct: true, note: '正解。前提は崩れるとリスクになるため明示・追跡する。' },
      { text: 'どちらも同じ意味である', correct: false, note: '性質が異なる。' },
      { text: '前提は技術的な条件、制約は業務的な条件である', correct: false, note: '領域による区別ではない。' },
      { text: '前提は文書化不要、制約は文書化必須である', correct: false, note: '前提も必ず文書化して追跡する。' },
    ],
    explanation: '制約は予算上限、法令、既存システムの仕様など動かせない条件。前提は「連携先の API が来月までに提供される」のような仮定で、崩れるとリスク化するため追跡が必要。',
    reference: '💡 前提は「リスク登録簿」に紐づけて監視するのが実務の定石。',
  },
  {
    id: 'req-20',
    domain: 'ba-requirements',
    type: 'multi',
    question: 'プロトタイピング（モックアップ）を要件の引き出しに使う利点として適切なものを2つ選べ。',
    options: [
      { text: '抽象的な議論では出てこない要望を具体的に引き出せる', correct: true, note: '正解。「これじゃない」が分かることに価値がある。' },
      { text: 'ステークホルダーが完成イメージを共有でき、認識のズレを早期に発見できる', correct: true, note: '正解。文書より直感的に理解される。' },
      { text: '開発工数が自動的に算出される', correct: false, note: '工数見積りは別作業。' },
      { text: 'そのまま本番システムとして使用できる', correct: false, note: 'プロトタイプは検証用であり、本番実装とは別。' },
    ],
    explanation: 'プロトタイピングは、言葉では表現しにくい要望を可視化して引き出す手法。ただしプロトタイプを完成品と誤解されないよう、位置づけを明確に伝える必要がある。',
    reference: '💡 Salesforce では標準機能で素早くモックを組めるため、プロトタイピングと相性が良い。',
  },
  {
    id: 'req-21',
    domain: 'ba-requirements',
    type: 'scenario',
    scenario: 'BA が要件一覧をレビューしたところ、「営業担当者は商談を素早く登録でき、必要に応じて上長に通知される」という記述があった。',
    question: 'この要件の問題点として最も適切な指摘はどれか。',
    options: [
      { text: '「素早く」「必要に応じて」が曖昧で検証できず、さらに2つの事項が1文にまとまっている', correct: true, note: '正解。曖昧語の排除と1要件1事項の両方に違反している。' },
      { text: '優先順位が付いていない', correct: false, note: '優先順位も必要だが、記述自体の欠陥がより深刻。' },
      { text: '実装方式が書かれていない', correct: false, note: '実装方式は要件に書くべきでない。' },
      { text: '問題はない', correct: false, note: '曖昧語と複数事項の混在は明確な欠陥。' },
    ],
    explanation: '「素早く」は数値化（例：3クリック以内）、「必要に応じて」は条件の明示（例：金額500万円以上の場合）が必要。さらに登録と通知は別要件に分割する。',
    reference: '💡 曖昧語のブラックリスト：速い、柔軟な、使いやすい、必要に応じて、など、適切に。',
  },
  {
    id: 'req-22',
    domain: 'ba-requirements',
    type: 'scenario',
    scenario: '構築フェーズの中盤で、営業部門から「商談画面に新しい項目を5つ追加してほしい」という依頼が BA に直接届いた。スプリントはすでに計画済みである。',
    question: 'BA が取るべき最も適切な行動はどれか。',
    options: [
      { text: '変更要求として受け付け、影響（工数・スケジュール・他要件への波及）を分析して意思決定者に判断を仰ぐ', correct: true, note: '正解。正式な変更管理プロセスに乗せる。' },
      { text: '小さな変更なので開発者に直接依頼する', correct: false, note: '積み重なるとスコープクリープになる。' },
      { text: '変更は受け付けられないと断る', correct: false, note: 'BA は変更を断る役ではない。影響を示して判断を仰ぐ。' },
      { text: 'リリース後に対応すると独断で決める', correct: false, note: '優先順位の判断は意思決定者が行う。' },
    ],
    explanation: '変更要求は「受付 → 影響分析 → 承認／却下 → ベースライン反映」の流れで扱う。BA の役割は影響の可視化であり、判断ではない。',
    reference: '💡 「小さいから」という理由で正式プロセスを飛ばすと、スコープクリープが常態化する。',
  },
  {
    id: 'req-23',
    domain: 'ba-requirements',
    type: 'scenario',
    scenario: 'UAT の直前になって、「監査要件として全レコードの変更履歴を7年間保持する必要がある」ことが判明した。データモデルとアーカイブ方式の見直しが必要になった。',
    question: 'この問題の根本原因として最も可能性が高いものはどれか。',
    options: [
      { text: '非機能要件の引き出しが不十分で、監査・保持要件が要件定義で抜けていた', correct: true, note: '正解。非機能要件の抜けは設計に大きな影響を与える典型例。' },
      { text: 'ユーザーストーリーの見積りが甘かった', correct: false, note: '見積りの問題ではなく、要件の抜けが原因。' },
      { text: 'UAT のテストシナリオが不足していた', correct: false, note: 'UAT で発見されたこと自体は問題ではない。要件段階の抜けが原因。' },
      { text: '開発チームの技術力が不足していた', correct: false, note: '技術力ではなく要件の入力の欠落。' },
    ],
    explanation: '非機能要件（性能、可用性、セキュリティ、監査、データ保持）は見落とされやすい。監査部門やセキュリティ部門をステークホルダーとして早期に巻き込むことで防げる。',
    reference: '💡 非機能要件のチェックリスト：性能・可用性・セキュリティ・監査・保持期間・同時利用者数・モバイル対応。',
  },
  {
    id: 'req-24',
    domain: 'ba-requirements',
    type: 'scenario',
    scenario: '複数部門から集めた要件のうち、経理部門の要件と営業部門の要件が同じ機能について矛盾する条件を求めていることが分かった。',
    question: 'BA が最初に行うべきことはどれか。',
    options: [
      { text: '双方の要件の背景（なぜその条件が必要か）を確認し、共通のビジネス目標に照らして整理する', correct: true, note: '正解。矛盾の解消は背景の理解から始める。' },
      { text: 'より詳細に書かれている方を採用する', correct: false, note: '記述の詳しさは正しさの基準にならない。' },
      { text: '両方の条件を満たす複雑な仕組みを設計する', correct: false, note: '矛盾を解消せずに複雑性だけが増す。' },
      { text: '矛盾はテストフェーズで解消する', correct: false, note: '要件段階で解消しないと大きな手戻りになる。' },
    ],
    explanation: '要件の一貫性(Consistent)は良い要件の条件のひとつ。矛盾を発見したら背景を確認し、それでも解けない場合は判断材料を整えてエスカレーションする。',
    reference: '💡 「立場ではなく利害に注目する」が矛盾解消の鍵になることが多い。',
  },
  {
    id: 'req-25',
    domain: 'ba-requirements',
    type: 'scenario',
    scenario: 'BA は要件一覧を作成したが、リリース時期が決まっており、すべてを実装する時間はない。ステークホルダーは全項目が重要だと主張している。',
    question: 'BA が取るべき最も適切なアプローチはどれか。',
    options: [
      { text: 'MoSCoW などの手法で分類し、「リリース初日に絶対必要か」を基準に Must と Should を切り分ける', correct: true, note: '正解。判断基準を与えることで優先順位付けが進む。' },
      { text: '要件を均等に半分ずつ実装する', correct: false, note: '価値の大小を無視した配分は成果を最大化しない。' },
      { text: 'リリース時期の延期を要求する', correct: false, note: '最初に検討すべきは優先順位付け。延期は最後の手段。' },
      { text: 'BA が重要と判断した要件だけ実装する', correct: false, note: '優先順位の決定はビジネス側の責任。' },
    ],
    explanation: '全部が最優先という状態は、判断基準が与えられていないことが原因。MoSCoW、価値 vs 労力、強制順位付けといった手法で比較可能にすることが BA の仕事。',
    reference: '💡 Wont have を明示することで「今回はやらない」という合意が文書に残る。',
  },
  {
    id: 'req-26',
    domain: 'ba-requirements',
    type: 'scenario',
    scenario: '要件定義中、ステークホルダーが「他社ではこの機能をこう実現している」と具体的なシステム構成を提示してきた。BA は自社の業務に合うか確信が持てない。',
    question: 'BA が取るべき最も適切な行動はどれか。',
    options: [
      { text: 'その構成が解決しようとしている課題を確認し、自社の課題・目標に照らして妥当性を検討する', correct: true, note: '正解。他社事例は参考であって、自社の要件の根拠にはならない。' },
      { text: '他社事例なので採用する', correct: false, note: '業務も前提も異なるため、そのままでは適合しない。' },
      { text: '他社事例は無関係なので検討しない', correct: false, note: '有用な示唆を含む可能性がある。切り捨てるのは早計。' },
      { text: '開発者に実現可能性だけ確認して決定する', correct: false, note: '実現可能でも自社の課題を解決するとは限らない。' },
    ],
    explanation: '他社事例は解決策(How)の一例にすぎない。BA は常に自社の課題(Problem)と目標に照らして妥当性を判断する。妥当性確認(Validation)の実践例。',
    reference: '💡 「その解決策はどの課題を解いているか」を問い返すのが BA の基本動作。',
  },
  {
    id: 'req-27',
    domain: 'ba-requirements',
    type: 'scenario',
    scenario: 'BA が承認プロセスの要件をまとめている。金額、部門、顧客区分、割引率の4つの条件によって承認者が変わる複雑なルールである。',
    question: '要件の抜け漏れを防ぐために BA が使うべき技法はどれか。',
    options: [
      { text: 'デシジョンテーブルで条件の組み合わせと結果を網羅的に整理する', correct: true, note: '正解。未定義の組み合わせが一目で分かる。' },
      { text: '文章で丁寧に説明する', correct: false, note: '条件が多いと文章では組み合わせ漏れを検出できない。' },
      { text: 'スイムレーン図で担当者を可視化する', correct: false, note: '流れは分かるが条件の網羅性は担保できない。' },
      { text: 'ユーザーストーリーを1つ書く', correct: false, note: '複雑なルールを1ストーリーに押し込むと受け入れ基準が破綻する。' },
    ],
    explanation: '条件が4つあると組み合わせは最大で数十通りになる。デシジョンテーブルは組み合わせを表で網羅し、定義されていないケースを可視化する。',
    reference: '💡 整理したルールはビジネスルール一覧として別管理し、複数の機能から参照できるようにする。',
  },
  {
    id: 'req-28',
    domain: 'ba-requirements',
    type: 'scenario',
    scenario: 'BA が要件をまとめた段階で、ある要件について「Salesforce の標準機能では実現できず、大規模なカスタム開発が必要」と開発者から指摘された。この要件は Must have に分類されている。',
    question: 'BA が取るべき最も適切な行動はどれか。',
    options: [
      { text: '要件の背景にある業務上の必要性を再確認し、標準機能で満たせる代替案とコスト比較を示して意思決定者に判断を仰ぐ', correct: true, note: '正解。目的に立ち返り、選択肢を提示して判断してもらう。' },
      { text: 'Must have なのでカスタム開発をそのまま進める', correct: false, note: 'コストとリスクを検討せずに進めるのは不適切。' },
      { text: '実現不可能として要件を削除する', correct: false, note: 'BA の独断で Must have を落とすことはできない。' },
      { text: '要件を Could have に変更する', correct: false, note: '優先順位の変更はビジネス側の判断。' },
    ],
    explanation: '実現可能性の問題が判明したら、要件の目的に立ち返って代替案を探る。「80%を標準機能で満たす案」が受け入れられることも多い。判断は意思決定者が行う。',
    reference: '💡 実現可能性の確認は要件確定前に行うのが理想。承認後に発覚すると信頼を損なう。',
  },
  {
    id: 'req-29',
    domain: 'ba-requirements',
    type: 'scenario',
    scenario: 'リリース後、ある機能がまったく使われていないことが判明した。調べると、要件は正しく実装されていたが、そもそもその機能が業務上必要とされていなかった。',
    question: 'この問題を防ぐために不足していた活動はどれか。',
    options: [
      { text: '妥当性確認(Validation)：その要件が本当にビジネス目標に寄与するかの確認', correct: true, note: '正解。正しく作ったが、正しいものを作っていなかった。' },
      { text: '検証(Verification)：要件が品質基準を満たしているかの確認', correct: false, note: '要件は正しく実装されており、品質基準の問題ではない。' },
      { text: '単体テストの強化', correct: false, note: '実装は正しかったため、テストの問題ではない。' },
      { text: 'ベロシティの測定', correct: false, note: '進捗指標であり、要件の妥当性とは無関係。' },
    ],
    explanation: '検証(Verification)は「正しく作っているか」、妥当性確認(Validation)は「正しいものを作っているか」。この事例は妥当性確認の不足が原因で、要件段階でビジネス目標との紐付けを確認すべきだった。',
    reference: '💡 要件をビジネス目標にトレースできる状態にしておくと、目標に寄与しない要件を検出できる。',
  },
  {
    id: 'req-30',
    domain: 'ba-requirements',
    type: 'scenario',
    scenario: 'プロジェクトの終盤で「この要件のテストケースが存在しない」ことが発覚した。BA は同様の抜けが他にもないか確認したい。',
    question: 'BA が使うべき最も適切な道具はどれか。',
    options: [
      { text: '要件トレーサビリティマトリクス(RTM)で、要件とテストケースの対応を突き合わせる', correct: true, note: '正解。テストされていない要件、要件のない実装を検出できる。' },
      { text: 'ステークホルダー分析マトリクス', correct: false, note: '関係者の分類であり、要件の追跡には使えない。' },
      { text: 'MoSCoW 分類表', correct: false, note: '優先順位付けの道具。' },
      { text: 'バーンダウンチャート', correct: false, note: '進捗の可視化であり、対応関係の追跡ではない。' },
    ],
    explanation: 'RTM は要件 → ストーリー → テストケース → 実装の対応を一覧化する。「カバーされていない要件」と「根拠のない実装」の両方を検出できるのが利点。',
    reference: '💡 RTM は影響分析にも使える。変更時にどこに波及するかが即座に分かる。',
  },
]
