export const userStoryQuestions = [
  {
    id: 'story-1',
    domain: 'ba-user-stories',
    type: 'mcq',
    question: 'ユーザーストーリーの標準書式として正しいものはどれか。',
    options: [
      { text: '〈ユーザー種別〉として、〈実現したいこと〉をしたい。なぜなら〈得たい価値〉だからだ。', correct: true, note: '正解。As a … I want … So that … の3要素。' },
      { text: 'Given〈前提〉、When〈操作〉、Then〈結果〉', correct: false, note: 'それは受け入れ基準の Gherkin 書式。' },
      { text: '〈条件〉のとき〈担当者〉が〈作業〉を行う', correct: false, note: 'プロセス記述であり、ユーザーストーリーの書式ではない。' },
      { text: '〈オブジェクト〉に〈項目〉を追加する', correct: false, note: '実装作業の記述であり、ユーザー価値が表現されていない。' },
    ],
    explanation: 'ユーザーストーリーは「誰が・何を・なぜ」を1〜2文で表す。特に「なぜなら(So that)」が重要で、これがないと優先順位の判断も代替案の検討もできない。',
    reference: '💡 主語は「ユーザーとして」ではなく「サービスエージェントとして」のように具体的な役割で書く。',
  },
  {
    id: 'story-2',
    domain: 'ba-user-stories',
    type: 'mcq',
    question: 'INVEST の「I」が示すものはどれか。',
    options: [
      { text: 'Independent（独立している）', correct: true, note: '正解。他ストーリーへの依存が少なく単独で開発・リリースできること。' },
      { text: 'Important（重要である）', correct: false, note: 'INVEST に Important は含まれない。' },
      { text: 'Integrated（統合されている）', correct: false, note: 'INVEST の項目ではない。' },
      { text: 'Iterative（反復的である）', correct: false, note: 'INVEST の項目ではない。' },
    ],
    explanation: 'INVEST は Independent(独立)、Negotiable(交渉可能)、Valuable(価値がある)、Estimable(見積り可能)、Small(小さい)、Testable(テスト可能)。',
    reference: '💡 バックログリファインメントで、各ストーリーを INVEST のチェックリストとして点検する。',
  },
  {
    id: 'story-3',
    domain: 'ba-user-stories',
    type: 'mcq',
    question: '受け入れ基準(Acceptance Criteria)と完了の定義(Definition of Done)の違いとして正しいものはどれか。',
    options: [
      { text: '受け入れ基準はストーリー固有の条件、DoD は全ストーリー共通のチーム標準', correct: true, note: '正解。適用範囲が異なる。' },
      { text: 'どちらも同じ意味である', correct: false, note: '階層と適用範囲が異なる別物。' },
      { text: '受け入れ基準は開発者、DoD はビジネス側が定める', correct: false, note: '担当者による区別ではない。' },
      { text: '受け入れ基準は UAT 用、DoD は単体テスト用である', correct: false, note: 'テストレベルによる区別ではない。' },
    ],
    explanation: '受け入れ基準はそのストーリーが完成したと言える固有の条件。DoD はコードレビュー済み・テスト済み・文書更新済みといった、すべてのストーリーに共通する品質基準。',
    reference: '💡 Definition of Ready（着手可能な状態の条件）も併せて3点セットで整理する。',
  },
  {
    id: 'story-4',
    domain: 'ba-user-stories',
    type: 'mcq',
    question: 'Given-When-Then（Gherkin）形式で受け入れ基準を書く利点はどれか。',
    options: [
      { text: '前提・操作・結果が明確に分かれ、そのままテストケースに変換できる', correct: true, note: '正解。テスト設計と直結する。' },
      { text: '実装方式を具体的に指定できる', correct: false, note: '受け入れ基準に実装方式は書かない。' },
      { text: '見積りが自動的に算出される', correct: false, note: '見積りは開発チームが行う。' },
      { text: 'ストーリーの優先順位が決まる', correct: false, note: '優先順位はプロダクトオーナーが決める。' },
    ],
    explanation: 'Given（前提）・When（操作）・Then（結果）の構造は、テストケースの「前提条件・手順・期待結果」に一対一で対応するため、UAT シナリオの作成が容易になる。',
    reference: '💡 箇条書き形式でもよい。重要なのは「真偽が判定できる形」であること。',
  },
  {
    id: 'story-5',
    domain: 'ba-user-stories',
    type: 'mcq',
    question: 'エピック(Epic)の説明として正しいものはどれか。',
    options: [
      { text: '1スプリントに収まらない大きなストーリーで、複数のストーリーに分割してから着手する', correct: true, note: '正解。分割前の大きな単位。' },
      { text: 'ストーリーを実現するための開発作業の単位', correct: false, note: 'それはタスク。' },
      { text: '調査のために時間を区切って行う作業', correct: false, note: 'それはスパイク。' },
      { text: 'スプリントで完了できたポイントの実績値', correct: false, note: 'それはベロシティ。' },
    ],
    explanation: '階層は、テーマ／イニシアチブ > エピック > ユーザーストーリー > タスク。エピックはユーザー価値を持つが大きすぎるため、着手前に分割する。',
    reference: '💡 ストーリー＝ユーザー価値の単位、タスク＝開発作業の単位。混同しやすい。',
  },
  {
    id: 'story-6',
    domain: 'ba-user-stories',
    type: 'mcq',
    question: 'ストーリーポイント(Story Point)の説明として正しいものはどれか。',
    options: [
      { text: '作業量・複雑さ・不確実性を合わせた相対的な規模の単位', correct: true, note: '正解。絶対時間ではないため、担当者の習熟度に影響されにくい。' },
      { text: '作業に必要な人時(man-hour)を示す絶対値', correct: false, note: '時間ではなく相対規模。' },
      { text: 'ストーリーのビジネス価値の大きさ', correct: false, note: '価値ではなく規模を表す。' },
      { text: 'ストーリーの優先順位', correct: false, note: '優先順位とは別の概念。' },
    ],
    explanation: 'ストーリーポイントは相対見積り。フィボナッチ数列を使うのは、規模が大きいほど見積り精度が落ちることを反映するためで、大きな数字は分割のサインでもある。',
    reference: '💡 ベロシティ（1スプリントの完了ポイント）はチーム固有の値。他チームとの比較には使わない。',
  },
  {
    id: 'story-7',
    domain: 'ba-user-stories',
    type: 'mcq',
    question: 'プランニングポーカーを行う本当の目的として最も適切なものはどれか。',
    options: [
      { text: '見積りの差異が生じた理由を議論し、認識の食い違いをその場で発見すること', correct: true, note: '正解。数字を決めること以上に、理解を揃えることに価値がある。' },
      { text: '最も経験豊富なメンバーの見積りに合わせること', correct: false, note: '一人の意見に収束させるための手法ではない。' },
      { text: '見積りにかかる時間を最小化すること', correct: false, note: '時間短縮が主目的ではない。' },
      { text: '作業時間を正確に予測すること', correct: false, note: '相対規模の見積りであり、絶対時間の予測ではない。' },
    ],
    explanation: '同じストーリーに1と13が付いたなら、そこには理解の食い違いがある。その理由を議論することで、要件の曖昧さや見落とされた作業が明らかになる。',
    reference: '💡 見積りを行うのは開発チーム。BA やマネージャが数字を押し付けてはいけない。',
  },
  {
    id: 'story-8',
    domain: 'ba-user-stories',
    type: 'mcq',
    question: 'ユーザーストーリーを分割する際の原則として正しいものはどれか。',
    options: [
      { text: '価値の縦割りで分け、各ストーリーが単独でユーザーに何かを提供できるようにする', correct: true, note: '正解。工程で割ると単独では価値を届けられない。' },
      { text: '設計・実装・テストの工程ごとに分ける', correct: false, note: '工程分割では各ストーリーが単独で価値を持たない。' },
      { text: '担当する開発者ごとに分ける', correct: false, note: '担当者の都合はストーリーの分割基準にならない。' },
      { text: '画面ごとに機械的に分ける', correct: false, note: '画面単位が価値の単位とは限らない。' },
    ],
    explanation: '分割の切り口は、業務ルールごと、データの種類ごと、ユーザー役割ごと、正常系と例外系、CRUD 操作ごと、手動版と自動版など。いずれも価値の縦割りで考える。',
    reference: '💡 「まず手動運用で価値を出し、後で自動化する」という分割も有効な選択肢。',
  },
  {
    id: 'story-9',
    domain: 'ba-user-stories',
    type: 'multi',
    question: '良い受け入れ基準の条件として適切なものを2つ選べ。',
    options: [
      { text: '真偽が判定できる形で書かれている', correct: true, note: '正解。判定できなければ完了を確認できない。' },
      { text: '正常系だけでなく異常系・境界値も含んでいる', correct: true, note: '正解。抜けるとリリース後の不具合になる。' },
      { text: '実装方式が具体的に指定されている', correct: false, note: '受け入れ基準には結果を書き、実装方式は書かない。' },
      { text: '可能な限り多くの条件（20個以上）を列挙している', correct: false, note: '数が多すぎるのはストーリーが大きすぎるサイン。' },
    ],
    explanation: '受け入れ基準は、開発者にとっての作るべき境界、テスターにとってのテストケースの元、プロダクトオーナーにとっての受け入れ判断の根拠として機能する。',
    reference: '💡 受け入れ基準が10個以上になるなら、ストーリーの分割を検討する。',
  },
  {
    id: 'story-10',
    domain: 'ba-user-stories',
    type: 'mcq',
    question: 'バックログリファインメント(Refinement)の説明として正しいものはどれか。',
    options: [
      { text: 'ストーリーの分割・明確化・見積り・並べ替えを継続的に行う活動', correct: true, note: '正解。BA の主戦場となる継続活動。' },
      { text: 'スプリント末に成果物をステークホルダーに見せる会議', correct: false, note: 'それはスプリントレビュー。' },
      { text: 'チームの働き方を改善する振り返り会議', correct: false, note: 'それはレトロスペクティブ。' },
      { text: 'スプリントで実施する作業を決める会議', correct: false, note: 'それはスプリントプランニング。' },
    ],
    explanation: 'リファインメント（グルーミング）は、次のスプリントで着手できる状態にストーリーを整えるための継続活動。スプリント作業時間の1割程度を充てるのが目安。',
    reference: '💡 DEEP の原則：適切に詳細化・見積り済み・創発的・優先順位付き。',
  },
  {
    id: 'story-11',
    domain: 'ba-user-stories',
    type: 'mcq',
    question: 'MVP(Minimum Viable Product) の説明として正しいものはどれか。',
    options: [
      { text: '価値を検証できる最小限の機能セット', correct: true, note: '正解。すべてを作り込む前にユーザーの反応を得る考え方。' },
      { text: '最も優先度の高い1つの機能', correct: false, note: '単一機能とは限らない。価値を検証できる最小の「まとまり」。' },
      { text: 'すべての Must have 要件を含む完成版', correct: false, note: 'MVP は完成版ではない。' },
      { text: '品質基準を下げて早くリリースしたもの', correct: false, note: '品質を下げることではない。範囲を絞ることが本質。' },
    ],
    explanation: 'MVP はリリース計画の基本的な考え方。ストーリーマッピングを使うと、ユーザーの行動の流れを俯瞰しながら MVP の線引きができる。',
    reference: '💡 MVP は「品質を落とす」ではなく「範囲を絞る」。この区別は誤解されやすい。',
  },
  {
    id: 'story-12',
    domain: 'ba-user-stories',
    type: 'mcq',
    question: 'ユーザーストーリーの「3C」に含まれないものはどれか。',
    options: [
      { text: 'Complexity（複雑さ）', correct: true, note: '正解。3C は Card、Conversation、Confirmation。Complexity は含まれない。' },
      { text: 'Card（カード）', correct: false, note: '3C に含まれる。ストーリーの記述そのもの。' },
      { text: 'Conversation（対話）', correct: false, note: '3C に含まれる。詳細は対話で詰める。' },
      { text: 'Confirmation（確認）', correct: false, note: '3C に含まれる。受け入れ基準による確認。' },
    ],
    explanation: 'ユーザーストーリーは仕様書の代替ではなく「会話の約束」。Card（簡潔な記述）、Conversation（詳細を詰める対話）、Confirmation（受け入れ基準）の3つで成り立つ。',
    reference: '💡 だからこそ INVEST の N(Negotiable)＝細部を固め切らない、が成立する。',
  },
  {
    id: 'story-13',
    domain: 'ba-user-stories',
    type: 'mcq',
    question: '「システムのパフォーマンスを改善したい」というストーリーは INVEST のどの原則に主に違反しているか。',
    options: [
      { text: 'Testable と Small（テスト可能でなく、大きすぎる）', correct: true, note: '正解。合否判定ができず、範囲も定まっていない。' },
      { text: 'Valuable（価値がない）', correct: false, note: '価値自体は認められる。問題は検証可能性と大きさ。' },
      { text: 'Independent（依存している）', correct: false, note: '依存関係の問題ではない。' },
      { text: 'Negotiable（交渉できない）', correct: false, note: '交渉余地の問題ではない。' },
    ],
    explanation: '「商談一覧の初期表示を3秒以内にする」のように、対象と数値を具体化して分割すると、見積り可能かつテスト可能なストーリーになる。',
    reference: '💡 見積れないストーリーはスパイク（時間を区切った調査）で情報を得てから見積り直す。',
  },
  {
    id: 'story-14',
    domain: 'ba-user-stories',
    type: 'mcq',
    question: 'ストーリーマッピング(User Story Mapping)の主な用途はどれか。',
    options: [
      { text: 'ユーザーの行動の流れを俯瞰し、リリース範囲（MVP の線引き）を検討する', correct: true, note: '正解。バックログの一次元リストでは見えない全体像を可視化する。' },
      { text: '欠陥の重大度を分類する', correct: false, note: '欠陥管理の話ではない。' },
      { text: 'ステークホルダーの影響度を分析する', correct: false, note: 'ステークホルダー分析の道具ではない。' },
      { text: 'テストケースを自動生成する', correct: false, note: '自動生成の仕組みではない。' },
    ],
    explanation: 'ストーリーマッピングは、横軸にユーザーの行動の流れ、縦軸に詳細度／優先度を置いてバックログを俯瞰する手法。リリースの水平線を引いて MVP を切り出せる。',
    reference: '💡 一次元のバックログでは「ユーザーが一連の作業を完結できるか」が見えにくい。',
  },
  {
    id: 'story-15',
    domain: 'ba-user-stories',
    type: 'multi',
    question: 'Salesforce プロジェクトのユーザーストーリーに含めるべき観点として適切なものを2つ選べ。',
    options: [
      { text: '対象となるユーザー（プロファイル／権限セット）とレコードの可視性要件', correct: true, note: '正解。共有要件は後から変えると影響が大きい。' },
      { text: 'レポートで見えるべきか、モバイルでも使うか', correct: true, note: '正解。表示チャネルの要件は受け入れ基準に影響する。' },
      { text: '使用する Apex クラス名とメソッド名', correct: false, note: '実装方式であり、ストーリーには書かない。' },
      { text: '担当する開発者の氏名', correct: false, note: 'ストーリーの内容ではなく作業割り当ての話。' },
    ],
    explanation: 'Salesforce では標準機能の設定に落ちるストーリーが多く、業務ルールの正確さと権限・可視性の要件が価値を左右する。実装方式は書かない。',
    reference: '💡 「営業担当は自分の商談だけ見える」といった共有要件は早期にストーリー化する。',
  },
  {
    id: 'story-16',
    domain: 'ba-user-stories',
    type: 'mcq',
    question: 'Definition of Ready（準備完了の定義）の説明として正しいものはどれか。',
    options: [
      { text: 'スプリントに取り込める状態の条件（受け入れ基準がある、見積り済み、依存が解消済みなど）', correct: true, note: '正解。着手後の手戻りを防ぐ。' },
      { text: 'ストーリーが完成したと言える条件', correct: false, note: 'それは Definition of Done。' },
      { text: 'UAT を開始してよい条件', correct: false, note: 'それは UAT の Entry Criteria。' },
      { text: 'リリースしてよい条件', correct: false, note: 'リリース判定基準とは別。' },
    ],
    explanation: 'Definition of Ready は「着手可能な状態」、Definition of Done は「完了した状態」、受け入れ基準は「そのストーリー固有の合格条件」。3つの区別が頻出。',
    reference: '💡 Ready でないストーリーをスプリントに入れると、スプリント中に要件確認で止まる。',
  },
  {
    id: 'story-17',
    domain: 'ba-user-stories',
    type: 'mcq',
    question: 'ベロシティ(Velocity)の適切な使い方はどれか。',
    options: [
      { text: '自チームの将来のスプリント計画とリリース時期の予測に使う', correct: true, note: '正解。計画のための実績値。' },
      { text: 'チーム間の生産性を比較する指標として使う', correct: false, note: 'ポイントの基準はチーム固有。比較すると数字が意図的に膨らむ。' },
      { text: '個人の人事評価に使う', correct: false, note: '評価指標にすると見積りが歪む。' },
      { text: 'ストーリーの優先順位を決めるのに使う', correct: false, note: '優先順位はビジネス価値で決める。' },
    ],
    explanation: 'ベロシティは1スプリントで完了できたポイントの実績値。自チームの計画に使うのが正しい用途で、他チームとの比較や評価に使うと機能しなくなる。',
    reference: '💡 数字を評価に使うと、見積りが膨らみ、ベロシティは計画の道具として役に立たなくなる。',
  },
  {
    id: 'story-18',
    domain: 'ba-user-stories',
    type: 'scenario',
    scenario: 'BA が次のストーリーを作成した。「営業担当者として、商談を登録したい。」受け入れ基準は書かれていない。',
    question: 'このストーリーの最も重要な改善点はどれか。',
    options: [
      { text: '「なぜなら〜だからだ」という価値の記述と、受け入れ基準を追加する', correct: true, note: '正解。価値がないと優先順位を判断できず、受け入れ基準がないと完了を判定できない。' },
      { text: 'ストーリーポイントを BA が付与する', correct: false, note: '見積りは開発チームが行う。' },
      { text: '実装方式（項目とレイアウト）を追記する', correct: false, note: 'ストーリーに実装方式は書かない。' },
      { text: '対象を「ユーザー」に一般化する', correct: false, note: '役割は具体的な方がよい。一般化は改悪。' },
    ],
    explanation: '「なぜなら(So that)」は優先順位判断と代替案検討の根拠になる。受け入れ基準は完了判定とテストケースの元になる。両方が欠けたストーリーは実装できない。',
    reference: '💡 INVEST の V(Valuable) と T(Testable) の両方に違反している状態。',
  },
  {
    id: 'story-19',
    domain: 'ba-user-stories',
    type: 'scenario',
    scenario: '開発チームがあるストーリーの見積りで「情報が足りず、規模の見当がつかない」と述べた。技術的な調査が必要とのことである。',
    question: 'BA が提案すべき最も適切な対応はどれか。',
    options: [
      { text: '時間を区切った調査（スパイク）をバックログに追加し、結果を得てから見積り直す', correct: true, note: '正解。不確実性を減らしてから見積る。' },
      { text: '大きめのポイントを暫定で付けて着手する', correct: false, note: '不確実なまま着手するとスプリントが破綻する。' },
      { text: 'BA が代わりに見積りを決める', correct: false, note: '見積りは開発チームが行う。' },
      { text: 'そのストーリーをバックログから削除する', correct: false, note: '価値のある要求を失うことになる。' },
    ],
    explanation: '見積れないのは INVEST の E(Estimable) を満たしていない状態。スパイクで不確実性を減らしてから見積り直すのが定石。',
    reference: '💡 スパイクはユーザー価値を直接持たないため、通常のストーリー書式には収まらない。',
  },
  {
    id: 'story-20',
    domain: 'ba-user-stories',
    type: 'scenario',
    scenario: 'あるストーリーの受け入れ基準が18項目に膨らみ、開発チームから「1スプリントでは終わらない」と指摘された。',
    question: 'BA が取るべき最も適切な行動はどれか。',
    options: [
      { text: 'ストーリーを価値の縦割りで複数に分割し、それぞれに受け入れ基準を割り当てる', correct: true, note: '正解。受け入れ基準の多さはストーリーが大きすぎるサイン。' },
      { text: '受け入れ基準を10項目に削って範囲を狭める', correct: false, note: '必要な条件を消すと品質が落ちる。分割が正しい対処。' },
      { text: 'スプリント期間を延長する', correct: false, note: 'スプリント長は固定が原則。' },
      { text: '受け入れ基準を「一式対応する」とまとめる', correct: false, note: '検証可能性が失われる。' },
    ],
    explanation: '受け入れ基準が多すぎるのは INVEST の S(Small) 違反のサイン。業務ルールごと、正常系と例外系、ユーザー役割ごとといった切り口で分割する。',
    reference: '💡 分割時も「各ストーリーが単独で価値を届けられるか」を確認する。',
  },
  {
    id: 'story-21',
    domain: 'ba-user-stories',
    type: 'scenario',
    scenario: 'プロダクトオーナーが「バックログに200件のストーリーがあり、どれも重要なので順序が決められない」と BA に相談してきた。',
    question: 'BA が提案すべき最も適切なアプローチはどれか。',
    options: [
      { text: 'ストーリーマッピングでユーザーの行動の流れを俯瞰し、MVP の範囲を線引きする', correct: true, note: '正解。一次元リストでは見えない全体像から優先順位を導く。' },
      { text: '登録順に上から着手する', correct: false, note: '価値に基づく順序ではない。' },
      { text: 'BA が独断で順序を決める', correct: false, note: '優先順位の決定はプロダクトオーナーの責任。' },
      { text: 'すべてを同時に着手する', correct: false, note: '実行不可能であり、何も完了しない。' },
    ],
    explanation: 'ストーリーマッピングは、ユーザーの行動の流れという文脈の中でストーリーを並べ直すため、「この一連の作業が完結するために最低限必要なもの」が見えやすくなる。',
    reference: '💡 MoSCoW や価値vs労力と組み合わせると、線引きの根拠がさらに明確になる。',
  },
  {
    id: 'story-22',
    domain: 'ba-user-stories',
    type: 'scenario',
    scenario: 'スプリントレビューで、完成したストーリーに対しステークホルダーから「これは想定していたものと違う」という指摘が出た。ストーリー自体は受け入れ基準どおりに実装されていた。',
    question: 'BA が振り返るべき最も重要な点はどれか。',
    options: [
      { text: '受け入れ基準の作成過程で、ステークホルダーとの認識合わせが不十分だった可能性', correct: true, note: '正解。受け入れ基準は対話を通じて精緻化する必要がある。' },
      { text: '開発チームの実装品質が低かった', correct: false, note: '受け入れ基準どおりに実装されている。' },
      { text: 'スプリントの期間が短すぎた', correct: false, note: '期間の問題ではない。' },
      { text: 'ベロシティの見積りが甘かった', correct: false, note: '進捗の問題ではない。' },
    ],
    explanation: 'ユーザーストーリーは「会話の約束」であり、受け入れ基準は BA／プロダクトオーナーが起案してステークホルダーと対話で精緻化する。認識合わせを省くとこの事態が起きる。',
    reference: '💡 プロトタイプやモックを使った事前確認は、この種のズレを防ぐのに効果的。',
  },
  {
    id: 'story-23',
    domain: 'ba-user-stories',
    type: 'scenario',
    scenario: 'BA が「割引率が20%を超える商談は保存できないようにする」というストーリーを作成した。受け入れ基準に「20%を超える場合エラーになる」とだけ書かれている。',
    question: '受け入れ基準に追加すべき最も重要な内容はどれか。',
    options: [
      { text: 'ちょうど20%の場合の挙動、および権限による例外の有無などの境界・例外条件', correct: true, note: '正解。境界値と例外の未定義は実装のぶれと不具合を生む。' },
      { text: 'エラーメッセージの文字色とフォントサイズ', correct: false, note: '実装の細部であり、受け入れ基準の主眼ではない。' },
      { text: '入力規則で実装する旨の指定', correct: false, note: '実装方式は書かない。' },
      { text: '開発者の担当割り当て', correct: false, note: '受け入れ基準の内容ではない。' },
    ],
    explanation: '受け入れ基準は正常系だけでなく境界値と異常系も網羅する。「ちょうど20%」「権限のあるユーザーは可能か」といった条件が抜けると、UAT で必ず論点になる。',
    reference: '💡 境界値（以上／超える、以下／未満）の曖昧さは、要件段階で最も頻繁に起きる誤解。',
  },
  {
    id: 'story-24',
    domain: 'ba-user-stories',
    type: 'scenario',
    scenario: '開発チームが「このストーリーは別のストーリーが完成しないと着手できない」と指摘した。依存関係が複数のストーリー間に張り巡らされている。',
    question: 'BA が取るべき最も適切な対応はどれか。',
    options: [
      { text: '依存関係を可視化し、可能な範囲でストーリーを再分割して独立性を高める', correct: true, note: '正解。INVEST の I(Independent) を満たすよう組み替える。' },
      { text: '依存関係は避けられないのでそのまま進める', correct: false, note: '計画の柔軟性が失われ、遅延が連鎖する。' },
      { text: '依存するストーリーをすべて1つに統合する', correct: false, note: '巨大なストーリーになり S(Small) に違反する。' },
      { text: '依存関係の解消は開発チームに任せる', correct: false, note: 'ストーリーの構成は BA が整える領域。' },
    ],
    explanation: '依存が多いと順序が固定され、優先順位の変更に追随できなくなる。分割の切り口を変える、共通部分を先行ストーリーにまとめるなどで独立性を高める。',
    reference: '💡 完全に依存をなくせないこともある。その場合は依存を明示して計画に織り込む。',
  },
  {
    id: 'story-25',
    domain: 'ba-user-stories',
    type: 'scenario',
    scenario: 'BA が「経営層として、全社の売上を見たい」というストーリーを作成した。開発チームから「何をどう集計するのか分からない」と質問された。',
    question: 'BA が受け入れ基準に明記すべき内容として最も適切なものはどれか。',
    options: [
      { text: '指標の定義（分子・分母・対象期間・フィルタ条件）と表示単位、対象ユーザー', correct: true, note: '正解。レポート系ストーリーは指標定義まで落とさないと実装できない。' },
      { text: '使用するレポートタイプ名', correct: false, note: '実装方式であり受け入れ基準に書かない。' },
      { text: 'ダッシュボードの配色', correct: false, note: '本質的な合格条件ではない。' },
      { text: '開発工数の見積り', correct: false, note: '受け入れ基準の内容ではない。' },
    ],
    explanation: 'レポート／ダッシュボードのストーリーは「何を売上とみなすか（受注ベースか請求ベースか）」「対象期間」「除外条件」まで定義しないと、実装も検証もできない。',
    reference: '💡 集計定義の曖昧さは、リリース後に「数字が合わない」という最も厄介な問題を生む。',
  },
  {
    id: 'story-26',
    domain: 'ba-user-stories',
    type: 'scenario',
    scenario: 'バックログに1年以上前に登録され、一度も着手されていないストーリーが多数残っている。内容は現在の業務と合わなくなっているものもある。',
    question: 'BA が取るべき最も適切な対応はどれか。',
    options: [
      { text: 'リファインメントで定期的に見直し、古くなったものはプロダクトオーナーと合意して削除する', correct: true, note: '正解。バックログは生き物であり、整理も含めて維持する。' },
      { text: 'すべて残しておく', correct: false, note: 'ノイズが増え、優先順位付けの精度が落ちる。' },
      { text: 'BA の判断で一括削除する', correct: false, note: 'バックログの内容はプロダクトオーナーの責任範囲。合意が必要。' },
      { text: 'すべてを次のスプリントに投入する', correct: false, note: '実行不可能であり、価値も検証されていない。' },
    ],
    explanation: 'DEEP の Emergent（創発的）が示すように、バックログは変化する。載っているだけで着手されない項目は定期的に見直し、古くなったものは削除して精度を保つ。',
    reference: '💡 「バックログに載せる」ことと「やると約束する」ことは別である。',
  },
  {
    id: 'story-27',
    domain: 'ba-user-stories',
    type: 'scenario',
    scenario: 'スプリント計画時、プロダクトオーナーが「今回は12ストーリー全部やってほしい」と要求した。チームの過去3スプリントのベロシティは平均で約半分の規模である。',
    question: 'BA が取るべき最も適切な行動はどれか。',
    options: [
      { text: 'ベロシティの実績を示し、現実的な範囲とその中での優先順位をプロダクトオーナーと確認する', correct: true, note: '正解。実績データに基づいて期待値を調整する。' },
      { text: 'プロダクトオーナーの要求どおりに全件を投入する', correct: false, note: '完了しない作業が積み上がり、計画の信頼性が失われる。' },
      { text: '開発チームに残業を依頼する', correct: false, note: '持続可能なペースの原則に反し、品質も落ちる。' },
      { text: 'ストーリーポイントを小さく付け直す', correct: false, note: '数字の操作であり、実態は変わらない。' },
    ],
    explanation: 'ベロシティは計画の現実性を示す実績値。BA はデータを示して期待値を調整し、限られた容量の中で最も価値の高いものを選ぶ議論に導く。',
    reference: '💡 「入らないなら何を外すか」を問うのが、スコープ総量を守る基本の型。',
  },
  {
    id: 'story-28',
    domain: 'ba-user-stories',
    type: 'scenario',
    scenario: 'BA が作成したストーリーに対し、開発者が「まずデータベースのテーブルを作るストーリーと、後で画面を作るストーリーに分けたい」と提案した。',
    question: 'BA が指摘すべき最も適切な点はどれか。',
    options: [
      { text: 'その分割は工程分割であり、各ストーリー単独ではユーザー価値を届けられない', correct: true, note: '正解。価値の縦割りで分けるのが原則。' },
      { text: '開発者の提案なので受け入れるべきである', correct: false, note: '提案は尊重するが、ストーリーの原則に反する分割は指摘する。' },
      { text: 'ストーリーポイントが小さくなるので良い分割である', correct: false, note: '小ささだけでは良い分割とは言えない。V(Valuable)も必要。' },
      { text: '受け入れ基準を分ければ問題ない', correct: false, note: '受け入れ基準の分割では価値の問題は解決しない。' },
    ],
    explanation: '工程（設計／実装／テスト、あるいは DB／画面）で割ると、各ストーリーは単独でユーザーに何も提供しない。開発上のタスク分割としては妥当だが、ストーリーの分割とは区別する。',
    reference: '💡 ストーリー＝ユーザー価値の単位、タスク＝開発作業の単位。開発者の分割はタスクとして扱えばよい。',
  },
]
