// Agentforce Specialist 用のフラッシュカード。表裏とも英日を併記し、カードごとに切り替えられる。
export const flashcards = [
  {
    id: 'af-fc-1',
    domain: 'af-prompt',
    front: 'The four prompt template types — how do you choose?',
    front_ja: '4つのプロンプトテンプレート種別 — どう選ぶ？',
    back: 'By where the output lands. Into a field → Field Generation. Onto the record page → Record Summary. Into an email → Sales Email. Called from a flow, Apex or an agent → Flex.',
    back_ja: '出力の行き先で選ぶ。項目に入る→Field Generation。レコードページに出る→Record Summary。メールになる→Sales Email。フロー・Apex・エージェントから呼ぶ→Flex。',
  },
  {
    id: 'af-fc-2',
    domain: 'af-prompt',
    front: 'Why would an edited prompt template still produce the old wording?',
    front_ja: '編集したプロンプトテンプレートが旧文言のまま出力されるのはなぜ？',
    back: 'Saving creates a new version; the previously activated version keeps serving until the new one is activated. Save ≠ activate.',
    back_ja: '保存は新しいバージョンを作るだけ。新版を有効化するまで、以前に有効化されたバージョンが処理を続ける。保存≠有効化。',
  },
  {
    id: 'af-fc-3',
    domain: 'af-prompt',
    front: 'How do you stop a model inventing content when a field is empty?',
    front_ja: '項目が空のときにモデルが内容を作り出すのを防ぐには？',
    back: 'Instruct it explicitly to state that the information is unavailable rather than infer it, and improve grounding. Not: a longer response, a bigger model, or hiding the merge field.',
    back_ja: '推測せず「情報が利用できない」と述べるよう明示的に指示し、グラウンディングを改善する。応答長を伸ばす・大きなモデルにする・差し込み項目を隠す、はいずれも誤り。',
  },
  {
    id: 'af-fc-4',
    domain: 'af-prompt',
    front: 'What does template preview show?',
    front_ja: 'テンプレートプレビューは何を見せてくれる？',
    back: 'The fully resolved prompt against a sample record, and the response the model returns. It is the design-time verification tool — use a typical record, not your best one.',
    back_ja: 'サンプルレコードで完全に解決されたプロンプトと、モデルが返す応答。設計時の検証ツール。最良のレコードではなく典型的なレコードで行う。',
  },
  {
    id: 'af-fc-5',
    domain: 'af-agent',
    front: 'Prompt instruction vs deterministic instruction',
    front_ja: 'プロンプト指示と決定的指示の違いは？',
    back: 'A prompt instruction is evaluated by the model at run time and its outcome can vary. A deterministic instruction executes exactly as written every time. "Always / must / guaranteed" → deterministic.',
    back_ja: 'プロンプト指示は実行時にモデルが評価し結果が変動する。決定的指示は毎回記述どおりに実行される。「必ず／must／保証」→決定的指示。',
  },
  {
    id: 'af-fc-6',
    domain: 'af-agent',
    front: 'before_reasoning vs after_reasoning',
    front_ja: 'before_reasoning と after_reasoning の使い分けは？',
    back: 'before_reasoning loads context the decision needs (fetch open orders, look up tier). after_reasoning applies fixed post-processing to the produced response (compliance footer, survey link).',
    back_ja: 'before_reasoning は判断に必要な文脈を読み込む（未処理注文の取得、ティアの参照）。after_reasoning は生成された応答に固定の後処理を適用する（コンプライアンスフッター、アンケートリンク）。',
  },
  {
    id: 'af-fc-7',
    domain: 'af-agent',
    front: 'What is a topic?',
    front_ja: 'トピックとは何か？',
    back: 'A job to be done, bundled with its instructions and the actions available for that job. The reasoning engine selects one by classifying the request against each topic\'s classification description.',
    back_ja: 'なすべき仕事を、その指示とその仕事で使えるアクションとともに束ねたもの。推論エンジンは要求を各トピックの分類説明と照合して1つを選ぶ。',
  },
  {
    id: 'af-fc-8',
    domain: 'af-agent',
    front: 'What does the Atlas Reasoning Engine actually receive?',
    front_ja: 'Atlas Reasoning Engine が実際に受け取るものは？',
    back: 'A single resolved prompt, compiled from the authoring definition and the active topic\'s instructions before any model call. Not the raw Agent Script and not the Canvas diagram.',
    back_ja: '作成定義とアクティブなトピックの指示から、モデル呼び出し前にコンパイルされた単一の解決済みプロンプト。生の Agent Script でも Canvas の図でもない。',
  },
  {
    id: 'af-fc-9',
    domain: 'af-agent',
    front: 'Availability filter — what does it do?',
    front_ja: '利用可能条件（availability filter）とは？',
    back: 'A condition that decides whether an action is presented to the reasoning engine at all. Because a filtered-out action is invisible, it is enforcement — unlike an action description, which is only guidance.',
    back_ja: 'アクションを推論エンジンに提示するかどうかを決める条件。除外されたアクションは見えないため強制として機能する。案内にすぎないアクション説明とは異なる。',
  },
  {
    id: 'af-fc-10',
    domain: 'af-agent',
    front: 'Canvas view vs Script view',
    front_ja: 'Canvas ビューと Script ビューの関係は？',
    back: 'Two editors over one underlying agent definition. They stay in sync; there is no precedence rule and no manual merge step.',
    back_ja: '1つのエージェント定義に対する2つのエディタ。常に同期しており、優先順位のルールも手動マージの手順もない。',
  },
  {
    id: 'af-fc-11',
    domain: 'af-agent',
    front: 'When should you build a flow instead of an agent?',
    front_ja: 'エージェントではなくフローを作るべきなのはどんなとき？',
    back: 'When there is no natural-language input and no judgement required. Reasoning adds cost, latency and variability that a fixed-rule nightly job gains nothing from.',
    back_ja: '自然言語の入力がなく、判断も不要なとき。推論はコスト・レイテンシ・変動をもたらすが、固定ルールの夜間ジョブには何の見返りもない。',
  },
  {
    id: 'af-fc-12',
    domain: 'af-agent',
    front: 'Mis-routing: which layer do you fix?',
    front_ja: '誤ルーティング：どの層を直す？',
    back: 'Wrong subject entirely → agent role and scope. Right subject, wrong topic → topic classification descriptions. Right topic, wrong action → action descriptions or availability filters.',
    back_ja: 'そもそも主題が違う→エージェントのロールとスコープ。主題は合うがトピックが違う→トピックの分類説明。トピックは合うがアクションが違う→アクションの説明または利用可能条件。',
  },
  {
    id: 'af-fc-13',
    domain: 'af-data',
    front: 'Structured vs unstructured grounding',
    front_ja: '構造化グラウンディングと非構造化グラウンディングの違いは？',
    back: 'Records and fields → merge fields, resolved live at generation time. Documents → an index and a retriever. Both needed → configure both; they are complementary, not alternatives.',
    back_ja: 'レコードと項目→差し込み項目（生成時にライブで解決）。ドキュメント→インデックスとリトリーバー。両方必要なら両方構成する。択一ではなく補完関係。',
  },
  {
    id: 'af-fc-14',
    domain: 'af-data',
    front: 'The RAG pipeline in order',
    front_ja: 'RAG パイプラインの順序は？',
    back: 'Build time: ingest → chunk → embed → index. Run time: retrieve the relevant chunks → include them in the prompt → generate.',
    back_ja: '構築時：取り込み→チャンク分割→埋め込み→インデックス化。実行時：関連チャンクを検索→プロンプトに含める→生成。',
  },
  {
    id: 'af-fc-15',
    domain: 'af-data',
    front: 'Retrieval symptoms → fixes',
    front_ja: '検索の症状と対処の対応は？',
    back: 'Wrong subject → metadata + retriever filter. Passage too short → larger chunks. Cut off at a boundary → more overlap. Paraphrases missed → vector index.',
    back_ja: '主題が違う→メタデータ＋リトリーバーのフィルター。パッセージが短すぎる→チャンクを大きく。境界で切れる→オーバーラップを増やす。言い換えを取りこぼす→ベクトルインデックス。',
  },
  {
    id: 'af-fc-16',
    domain: 'af-data',
    front: 'DLO vs DMO — and why map between them?',
    front_ja: 'DLO と DMO の違い、そしてなぜマッピングするのか？',
    back: 'A data lake object mirrors the source exactly. A data model object is the harmonised standard model. Mapping exists because identity resolution, segmentation, insights and retrievers all expect the harmonised model.',
    back_ja: 'データレイクオブジェクトはソースをそのまま写す。データモデルオブジェクトは調和された標準モデル。ID解決・セグメント化・インサイト・リトリーバーがいずれも調和済みモデルを前提とするため、マッピングが必要。',
  },
  {
    id: 'af-fc-17',
    domain: 'af-data',
    front: 'Identity resolution vs data spaces',
    front_ja: 'ID解決とデータスペースの違いは？',
    back: 'Identity resolution unifies records describing the same person across sources. Data spaces partition data so brands or business units stay separate. Opposite purposes, often used together.',
    back_ja: 'ID解決は複数ソースにまたがる同一人物のレコードを統合する。データスペースはデータを区切り、ブランドや事業部を分離する。目的は正反対だが併用されることも多い。',
  },
  {
    id: 'af-fc-18',
    domain: 'af-data',
    front: 'Data Library vs building the index yourself',
    front_ja: 'Data Library と自前でのインデックス構築の使い分けは？',
    back: 'Data Library when speed matters and no special control is needed — it packages ingestion, chunking, indexing and retrieval. Build it yourself when you need a metadata filter, custom ranking, or a shared index.',
    back_ja: '速さ重視で特別な制御が不要なら Data Library（取り込み・チャンク分割・インデックス化・検索をまとめて提供）。メタデータフィルター、独自ランキング、共有インデックスが必要なら自前構築。',
  },
  {
    id: 'af-fc-19',
    domain: 'af-trust',
    front: 'Which user does an agent run as?',
    front_ja: 'エージェントは誰として動作する？',
    back: 'Employee agent → the logged-in user, inheriting their sharing and field-level security. Public/unauthenticated agent → a dedicated agent user whose permissions define the whole data boundary.',
    back_ja: '従業員向けエージェント→ログインユーザー（共有設定と項目レベルセキュリティを継承）。公開・未認証エージェント→専用エージェントユーザー（その権限がデータ境界そのもの）。',
  },
  {
    id: 'af-fc-20',
    domain: 'af-trust',
    front: 'Masking vs zero data retention',
    front_ja: 'マスキングとゼロデータ保持の違いは？',
    back: 'Masking = the value never leaves the platform. Zero data retention = it leaves but the provider does not store it. These are constantly confused on the exam.',
    back_ja: 'マスキング＝その値はプラットフォームの外へ出ない。ゼロデータ保持＝外へは出るが、プロバイダーが保存しない。試験では頻繁に混同される。',
  },
  {
    id: 'af-fc-21',
    domain: 'af-trust',
    front: 'The five Trust Layer controls',
    front_ja: 'Trust Layer の5つの制御は？',
    back: 'Masking (data leaving), zero data retention (provider storage), toxicity detection (harmful output), prompt defence (injection attacks), audit trail (the record).',
    back_ja: 'マスキング（データの流出）、ゼロデータ保持（プロバイダーの保存）、毒性検出（有害な出力）、プロンプト防御（インジェクション攻撃）、監査証跡（記録）。',
  },
  {
    id: 'af-fc-22',
    domain: 'af-trust',
    front: 'A user pastes "ignore your instructions" into the chat. Which control resists it?',
    front_ja: 'ユーザーが「指示を無視しろ」とチャットに貼り付けた。抵抗する制御は？',
    back: 'Prompt defence. Masking protects values, zero data retention governs storage, and the audit trail only records the attempt after the fact.',
    back_ja: 'プロンプト防御。マスキングは値を保護し、ゼロデータ保持は保存を規定し、監査証跡は事後に試行を記録するだけ。',
  },
  {
    id: 'af-fc-23',
    domain: 'af-trust',
    front: 'Users should run prompt templates but not edit them. What do you grant?',
    front_ja: 'プロンプトテンプレートを実行させたいが編集はさせたくない。何を付与する？',
    back: 'The permission to use prompt templates, without the permission to manage them. Never Modify All Data — and "no permission needed" is also wrong.',
    back_ja: 'プロンプトテンプレートの「利用」権限のみを付与し、「管理」権限は付与しない。Modify All Data は不可。「権限不要」も誤り。',
  },
  {
    id: 'af-fc-24',
    domain: 'af-lifecycle',
    front: 'What does a metadata deployment NOT carry?',
    front_ja: 'メタデータ展開が運ばないものは？',
    back: 'Data 360 configuration (data streams, mappings, indexes, retrievers) and the agent user with its permission assignments. Both must be configured in the target org.',
    back_ja: 'Data 360 の構成（データストリーム、マッピング、インデックス、リトリーバー）と、エージェントユーザーおよびその権限割り当て。どちらも対象組織で構成が必要。',
  },
  {
    id: 'af-fc-25',
    domain: 'af-lifecycle',
    front: 'Three post-deployment symptoms and their causes',
    front_ja: '展開後の3つの症状とその原因は？',
    back: 'Silent → the agent deployed inactive and was not activated. Talks but no grounded content → Data 360 configuration missing. Access error on one action → the agent user lacks permissions.',
    back_ja: '無反応→非アクティブな状態で展開され、有効化されていない。話すがグラウンディングされた内容がない→Data 360 の構成が未構築。特定アクションのアクセスエラー→エージェントユーザーの権限不足。',
  },
  {
    id: 'af-fc-26',
    domain: 'af-lifecycle',
    front: 'What does a Testing Center test case evaluate?',
    front_ja: 'Testing Center のテストケースは何を評価する？',
    back: 'The whole decision path: the utterance, the topic selected, the actions invoked, and the response produced — not just the final wording.',
    back_ja: '判断の経路全体。発話、選択されたトピック、実行されたアクション、生成された応答。最終的な文言だけではない。',
  },
  {
    id: 'af-fc-27',
    domain: 'af-lifecycle',
    front: 'Transcript vs utterance analysis vs containment rate',
    front_ja: 'トランスクリプト・発話分析・封じ込め率の使い分けは？',
    back: 'One specific conversation → transcript. What users asked and where nothing matched → utterance analysis. Proportion completed without a human → containment rate.',
    back_ja: '特定の1会話→トランスクリプト。ユーザーが何を尋ね、どこで一致しなかったか→発話分析。人の介在なく完了した割合→封じ込め率。',
  },
  {
    id: 'af-fc-28',
    domain: 'af-lifecycle',
    front: 'An agent is giving customers wrong information right now. First action?',
    front_ja: 'エージェントがいま顧客に誤った情報を出している。最初の対応は？',
    back: 'Deactivate it. Immediate, reversible, and it leaves the definition intact for diagnosis. Do not delete topics; do not just lower a conversation limit.',
    back_ja: '非アクティブ化する。即時に効き、元に戻せ、定義は調査のために残る。トピックを削除しない。会話上限を下げるだけにもしない。',
  },
  {
    id: 'af-fc-29',
    domain: 'af-integration',
    front: 'MCP vs A2A vs Agent API',
    front_ja: 'MCP・A2A・Agent API の違いは？',
    back: 'MCP → agent to external tools and data. A2A → agent to another agent. Agent API → an external application calling in to your agent. MCP and A2A are outbound; the Agent API is inbound.',
    back_ja: 'MCP→エージェントから外部ツール・データへ。A2A→エージェントから別のエージェントへ。Agent API→外部アプリケーションから自社エージェントへ。MCP と A2A は外向き、Agent API は内向き。',
  },
  {
    id: 'af-fc-30',
    domain: 'af-integration',
    front: 'What determines where an agent is available?',
    front_ja: 'エージェントがどこで利用できるかを決めるものは？',
    back: 'The channels it is published to — the Salesforce app, Slack, a website. For an application you build yourself, use the Agent API instead.',
    back_ja: '公開したチャネル（Salesforce アプリ、Slack、Webサイトなど）。自社で開発するアプリケーションの場合はチャネルではなく Agent API を使う。',
  },
  {
    id: 'af-fc-31',
    domain: 'af-integration',
    front: 'How do you make the agent hand over to a human on a defined condition?',
    front_ja: '定義した条件で人へ引き継がせるには？',
    back: 'Configure an escalation action and instruct the agent to invoke it when the condition is present. Containment rate is a measurement, not a control.',
    back_ja: 'エスカレーションアクションを構成し、条件を満たすときに実行するようエージェントに指示する。封じ込め率は測定指標であって制御ではない。',
  },
  {
    id: 'af-fc-32',
    domain: 'af-integration',
    front: 'Supervisor agent architecture',
    front_ja: 'スーパーバイザーエージェントのアーキテクチャとは？',
    back: 'A supervisor routes to specialist agents by reasoning over each one\'s declared scope. In one org they share its data and governance; MCP is not needed. Across orgs, use A2A.',
    back_ja: 'スーパーバイザーが各専門エージェントの宣言されたスコープを推論して振り分ける。同一組織内ならデータとガバナンスを共有し、MCP は不要。組織をまたぐ場合は A2A。',
  },
]

export const flashcardsByDomain = (domainId) => flashcards.filter((f) => f.domain === domainId)
