// Data Cloud (Data 360) Consultant 用のフラッシュカード。
// 表裏とも英日を併記し、カードごとに切り替えられる。
export const flashcards = [
  // ---- Solution Positioning ----
  {
    id: 'dc-fc-1',
    domain: 'dc-positioning',
    front: 'The Data 360 pipeline, in order?',
    front_ja: 'Data 360 のパイプラインを順番に言うと？',
    back: 'Connect → Harmonise → Unify → Analyse → Act. Almost every positioning question asks which stage a term belongs to.',
    back_ja: '接続→調和→統合→分析→実行。位置づけの設問はほぼすべて「その用語がどの段階か」を問うている。',
  },
  {
    id: 'dc-fc-2',
    domain: 'dc-positioning',
    front: 'Data Cloud vs Data 360 — what is the difference?',
    front_ja: 'Data Cloud と Data 360 の違いは？',
    back: 'None. Salesforce renamed the product and the credential to Data 360. Older material and much of the setup UI still say Data Cloud.',
    back_ja: '違いはない。Salesforce が製品名と資格名を Data 360 へ改称した。古い教材や設定画面の多くは今も Data Cloud のまま。',
  },
  {
    id: 'dc-fc-3',
    domain: 'dc-positioning',
    front: 'How is Data 360 priced, and why does it matter to design?',
    front_ja: 'Data 360 の課金方式は？ それが設計にどう影響する？',
    back: 'Consumption-based in credits — ingestion, processing, queries and activations all consume. This is why narrow streams, sensible refresh schedules and Zero Copy are usually right.',
    back_ja: 'クレジットの従量課金。取り込み・処理・クエリ・アクティベーションのすべてが消費する。絞り込んだストリーム、妥当な更新間隔、Zero Copy が正解になりやすい理由。',
  },
  {
    id: 'dc-fc-4',
    domain: 'dc-positioning',
    front: 'How do predictive and generative AI consume Data 360 differently?',
    front_ja: '予測AI と生成AI で Data 360 の使い方はどう違う？',
    back: 'Predictive writes a prediction back as a DMO field you can segment on. Generative reads context at prompt time (data graphs + retrievers) and writes nothing back.',
    back_ja: '予測は予測結果を DMO の項目として書き戻し、セグメントに使える。生成はプロンプト実行時にコンテキストを読む（Data Graph＋Retriever）だけで何も書き戻さない。',
  },
  {
    id: 'dc-fc-5',
    domain: 'dc-positioning',
    front: 'How do you choose a first use case?',
    front_ja: '最初のユースケースはどう選ぶ？',
    back: 'Start from a measurable business outcome, then work backwards to the minimum data needed. "Ingest everything first" is the classic wrong answer.',
    back_ja: '測定可能なビジネス成果から始め、必要最小限のデータへ逆算する。「まず全部取り込む」が典型的な誤答。',
  },
  {
    id: 'dc-fc-6',
    domain: 'dc-positioning',
    front: 'The core data ethics principle tested on this exam?',
    front_ja: 'この試験で問われるデータ倫理の中核原則は？',
    back: 'Technical capability does not create permission. Collect for a stated purpose, use only for that purpose, minimise what you take, and honour consent at activation.',
    back_ja: '技術的にできることは、やってよいことを意味しない。明示した目的のために収集し、その目的にのみ使い、取得を最小化し、アクティベーション時に同意を尊重する。',
  },

  // ---- Setup and Administration ----
  {
    id: 'dc-fc-7',
    domain: 'dc-setup',
    front: 'Permission set vs data space — what does each control?',
    front_ja: '権限セットとデータスペース — それぞれ何を制御する？',
    back: 'Permission set = what a user can do. Data space = which data they do it to. Scenarios naming both a role and a brand or region need both.',
    back_ja: '権限セット＝ユーザーが何をしてよいか。データスペース＝どのデータに対してか。役割とブランド／地域の両方が書かれたシナリオは両方が必要。',
  },
  {
    id: 'dc-fc-8',
    domain: 'dc-setup',
    front: 'Order the marketing permission sets by breadth.',
    front_ja: 'マーケティング系の権限セットを広さの順に。',
    back: 'Marketing Specialist (works within existing segments) < Marketing Manager (creates segments and activations) < Marketing Admin (that plus platform setup). Admin/Architect covers setup.',
    back_ja: 'Marketing Specialist（既存セグメント内で作業）＜ Marketing Manager（セグメントとアクティベーションを作成）＜ Marketing Admin（それに加え基盤設定）。Admin／Architect が基盤のセットアップを担う。',
  },
  {
    id: 'dc-fc-9',
    domain: 'dc-setup',
    front: 'Two brands must not see or unify each other\'s customers. What do you use?',
    front_ja: '2つのブランドが互いの顧客を閲覧も統合もしてはならない。何を使う？',
    back: 'Separate data spaces. Segments, activations and identity resolution are all scoped to a data space, so both requirements are satisfied at once.',
    back_ja: '別々のデータスペース。セグメント・アクティベーション・ID解決はすべてデータスペース単位なので、2つの要件が同時に満たされる。',
  },
  {
    id: 'dc-fc-10',
    domain: 'dc-setup',
    front: 'Which troubleshooting tool answers which question?',
    front_ja: 'トラブルシューティングのツールと問いの対応は？',
    back: 'Data Explorer = did the data arrive and look right? Profile Explorer = why did these merge (or not)? Query Editor = SQL across objects. Refresh history = did ingestion run?',
    back_ja: 'Data Explorer＝データは届いて正しく見えるか。Profile Explorer＝なぜ結合した／しなかったか。クエリエディタ＝オブジェクト横断の SQL。更新履歴＝取り込みは実行されたか。',
  },
  {
    id: 'dc-fc-11',
    domain: 'dc-setup',
    front: 'What does a data kit contain?',
    front_ja: 'Data Kit には何が含まれる？',
    back: 'Data 360 metadata — data streams, DMOs, mappings, calculated insights, segments — for deployment to another org. Configuration only, never the ingested data.',
    back_ja: 'Data 360 のメタデータ（データストリーム、DMO、マッピング、Calculated Insight、セグメント）を他組織へデプロイするためのもの。設定のみで、取り込んだデータは含まない。',
  },
  {
    id: 'dc-fc-12',
    domain: 'dc-setup',
    front: 'Users see no Data 360 features after provisioning. Why?',
    front_ja: 'プロビジョニング後、ユーザーに Data 360 の機能が見えない。なぜ？',
    back: 'No permission sets assigned. Provisioning enables the platform; it grants nobody access. A Salesforce admin assigns the sets.',
    back_ja: '権限セットが未割り当て。プロビジョニングはプラットフォームを有効化するだけで、誰にもアクセス権を与えない。割り当ては Salesforce の管理者が行う。',
  },

  // ---- Ingestion ----
  {
    id: 'dc-fc-13',
    domain: 'dc-ingestion',
    front: 'The three data stream categories, and how to tell them apart?',
    front_ja: 'データストリームの3つのカテゴリと見分け方は？',
    back: 'Profile = who someone is (needs a primary key). Engagement = what they did and when (needs an event time field). Other = reference data such as product or store lists.',
    back_ja: 'Profile＝その人が誰か（主キーが必要）。Engagement＝何をいつしたか（イベント時刻の項目が必要）。Other＝商品や店舗の一覧などの参照データ。',
  },
  {
    id: 'dc-fc-14',
    domain: 'dc-ingestion',
    front: 'Can a data stream category be changed after creation?',
    front_ja: 'データストリームのカテゴリは作成後に変更できる？',
    back: 'No. It is one of the few genuinely irreversible decisions in Data 360 — you must delete and recreate the stream.',
    back_ja: 'できない。Data 360 で数少ない本当に取り消せない判断の1つ。ストリームを削除して作り直すしかない。',
  },
  {
    id: 'dc-fc-15',
    domain: 'dc-ingestion',
    front: 'Upsert vs full refresh — what is the practical difference?',
    front_ja: 'upsert と full refresh の実務上の違いは？',
    back: 'Upsert updates or inserts by primary key, and rows deleted at the source stay forever. Full refresh replaces the contents, so source deletions propagate.',
    back_ja: 'upsert は主キーで更新または挿入し、ソースで削除された行は残り続ける。full refresh は内容を置き換えるので削除が伝播する。',
  },
  {
    id: 'dc-fc-16',
    domain: 'dc-ingestion',
    front: 'Records duplicate in a DLO on every run. Cause?',
    front_ja: '実行のたびに DLO でレコードが重複する。原因は？',
    back: 'The primary key is not unique or not stable in the source. Duplicates within one DLO = key problem; duplicate people across DMOs = identity resolution problem.',
    back_ja: '主キーがソース側で一意でないか安定していない。1つの DLO 内の重複＝主キーの問題、DMO をまたいだ人物の重複＝ID解決の問題。',
  },
  {
    id: 'dc-fc-17',
    domain: 'dc-ingestion',
    front: 'What must be done before the Ingestion API can receive data?',
    front_ja: 'Ingestion API がデータを受け取る前に必要なことは？',
    back: 'Create the connector and upload a schema (OpenAPI/YAML) describing the payload. Applies to both streaming and bulk modes.',
    back_ja: 'コネクタを作成し、ペイロードを定義するスキーマ（OpenAPI／YAML）をアップロードする。ストリーミングとバルクの両モードに適用される。',
  },
  {
    id: 'dc-fc-18',
    domain: 'dc-ingestion',
    front: 'The three forms of Zero Copy?',
    front_ja: 'Zero Copy の3つの形態は？',
    back: 'Query federation (external tables queried live), file federation (lake files referenced), and data sharing (Data 360 objects exposed outward). None duplicates the data.',
    back_ja: 'クエリ連携（外部テーブルをライブでクエリ）、ファイル連携（レイク上のファイルを参照）、データ共有（Data 360 のオブジェクトを外へ公開）。いずれもデータを複製しない。',
  },
  {
    id: 'dc-fc-19',
    domain: 'dc-ingestion',
    front: 'When choose ingestion over Zero Copy?',
    front_ja: 'Zero Copy ではなく取り込みを選ぶのはどんなとき？',
    back: 'When the source is not a supported Zero Copy platform, or the data must remain usable if the external platform is unavailable. Federated queries consume the external platform\'s compute.',
    back_ja: 'ソースが Zero Copy 対応でないとき、または外部プラットフォームが停止してもデータを使い続ける必要があるとき。連携クエリは外部側の計算資源を消費する。',
  },
  {
    id: 'dc-fc-20',
    domain: 'dc-ingestion',
    front: 'Formula field vs batch data transform?',
    front_ja: '数式項目とバッチデータ変換の違いは？',
    back: 'Formula field = light row-level derivation at ingest (concatenate, cast, trim). Batch transform = joins, aggregation and reshaping on a schedule, writing a new DLO.',
    back_ja: '数式項目＝取り込み時の軽量な行単位の導出（連結・型変換・トリム）。バッチ変換＝スケジュール実行での結合・集計・再構成で、新しい DLO を書き出す。',
  },

  // ---- Harmonization and Unification ----
  {
    id: 'dc-fc-21',
    domain: 'dc-unification',
    front: 'DLO vs DMO?',
    front_ja: 'DLO と DMO の違いは？',
    back: 'DLO = raw ingested data with the source\'s own field names, one per data stream. DMO = the harmonised object in the Customer 360 model. Nothing downstream reads the DLO directly.',
    back_ja: 'DLO＝ソース側の項目名のままの生データ、データストリーム1つにつき1つ。DMO＝Customer 360 モデル上の調和済みオブジェクト。下流のどれも DLO を直接は読まない。',
  },
  {
    id: 'dc-fc-22',
    domain: 'dc-unification',
    front: 'Match rules vs reconciliation rules?',
    front_ja: '一致ルールと調整ルールの違いは？',
    back: 'Match runs first: are these the same person? Reconciliation runs second: which conflicting value is displayed? Reconciliation can never cause or undo a merge.',
    back_ja: '一致が先：同一人物か？ 調整が次：衝突する値のどれを表示するか？ 調整が結合を起こしたり取り消したりすることはない。',
  },
  {
    id: 'dc-fc-23',
    domain: 'dc-unification',
    front: 'One person appears as several profiles. What is wrong, and what do you do?',
    front_ja: '1人が複数のプロファイルとして現れる。何が起きていて、どうする？',
    back: 'Under-matching. Standardise the data at ingest, or add a rule on a stronger identifier (party identification, email). Do not tighten — that makes it worse.',
    back_ja: '不足一致。取り込み時にデータを標準化するか、より強い識別子（Party Identification、メール）でルールを追加する。厳しくしてはいけない。悪化する。',
  },
  {
    id: 'dc-fc-24',
    domain: 'dc-unification',
    front: 'Two different people were merged. What is wrong, and what do you do?',
    front_ja: '別人2人が結合された。何が起きていて、どうする？',
    back: 'Over-matching. Tighten: add a discriminating criterion, or stop matching on a weak field. Surname + postal code alone will always merge families.',
    back_ja: '過剰一致。厳しくする。識別力のある条件を追加するか、弱い項目での照合をやめる。姓＋郵便番号だけでは必ず家族が結合される。',
  },
  {
    id: 'dc-fc-25',
    domain: 'dc-unification',
    front: 'The three reconciliation strategies and their scenario cues?',
    front_ja: '3つの調整方式と、シナリオ上の手がかりは？',
    back: 'Most Recent = "latest wins". Most Frequent = "consensus wins", when one system is occasionally wrong. Source Priority = "the named system of record wins".',
    back_ja: 'Most Recent＝「最後が勝つ」。Most Frequent＝「多数が勝つ」、あるシステムが時々誤る場合。Source Priority＝「名指しされた記録システムが勝つ」。',
  },
  {
    id: 'dc-fc-26',
    domain: 'dc-unification',
    front: 'Why are contact points separate DMOs?',
    front_ja: 'なぜ Contact Point は別々の DMO なのか？',
    back: 'One individual can hold several emails, phones and addresses, and consent attaches to the contact point — someone can be opted in for email and out for SMS.',
    back_ja: '1人が複数のメール・電話・住所を持ち得て、同意は Contact Point に紐づくため。メールはオプトイン、SMS はオプトアウトということがある。',
  },
  {
    id: 'dc-fc-27',
    domain: 'dc-unification',
    front: 'When does identity resolution run?',
    front_ja: 'ID解決はいつ実行される？',
    back: 'On a schedule, per data space — never instantly. A large share of "missing unified profile" reports are just a ruleset that has not run since the data arrived.',
    back_ja: 'データスペース単位でスケジュール実行。即時ではない。「統合プロファイルが無い」という報告の多くは、データ到着後にルールセットが未実行なだけ。',
  },
  {
    id: 'dc-fc-28',
    domain: 'dc-unification',
    front: 'A newly ingested DLO does not appear when building a segment. Why?',
    front_ja: '新しく取り込んだ DLO がセグメント作成時に現れない。なぜ？',
    back: 'It has not been mapped to a DMO. Mapping is the gate — "data is there but nothing downstream sees it" is nearly always a mapping gap.',
    back_ja: 'DMO にマッピングされていない。マッピングが関門。「データはあるのに下流から見えない」はほぼ常にマッピング漏れ。',
  },

  // ---- Enhancements, Sharing and Analysis ----
  {
    id: 'dc-fc-29',
    domain: 'dc-insights',
    front: 'Calculated vs streaming insight — how do you choose?',
    front_ja: 'Calculated と Streaming のインサイトはどう選ぶ？',
    back: 'By latency, not by what you compute. Calculated = batch, SQL, scheduled, stable metrics. Streaming = continuous, time-windowed, for values that decay in minutes; can trigger data actions.',
    back_ja: '計算内容ではなく遅延要件で選ぶ。Calculated＝バッチ・SQL・スケジュール・安定した指標。Streaming＝連続・時間ウィンドウ・数分で価値が失われる値。Data Action を起動できる。',
  },
  {
    id: 'dc-fc-30',
    domain: 'dc-insights',
    front: 'What is a data graph for?',
    front_ja: 'Data Graph は何のためのもの？',
    back: 'Pre-joining related DMOs into a materialised view so the full customer context reads in one low-latency call. Used by AI grounding, retrievers, personalisation and APIs.',
    back_ja: '関連 DMO を事前結合してマテリアライズドビューにし、顧客コンテキスト全体を1回の低遅延な呼び出しで読めるようにする。AIのグラウンディング、Retriever、パーソナライゼーション、API が利用する。',
  },
  {
    id: 'dc-fc-31',
    domain: 'dc-insights',
    front: 'Surface in place vs copy the field to CRM — how do you decide?',
    front_ja: 'その場に表示するか、項目を CRM にコピーするか — どう判断する？',
    back: 'People only need to see it → related lists and profile components. It must be filterable, natively reportable or used by standard automation (validation rules) → copy the field.',
    back_ja: '見るだけでよい→関連リストとプロファイルコンポーネント。絞り込み・標準レポート・標準自動化（入力規則）で使う→項目をコピーする。',
  },
  {
    id: 'dc-fc-32',
    domain: 'dc-insights',
    front: 'What is BYOM, and what happens to the prediction?',
    front_ja: 'BYOM とは何で、予測結果はどうなる？',
    back: 'Bring Your Own Model connects a model in SageMaker, Vertex AI or Databricks without the data leaving Data 360. The prediction lands as a DMO field, so you can segment and activate on it.',
    back_ja: '外部（SageMaker、Vertex AI、Databricks）のモデルを、データを Data 360 の外に出さずに接続する仕組み。予測は DMO の項目として着地するので、セグメント化・アクティベートできる。',
  },
  {
    id: 'dc-fc-33',
    domain: 'dc-insights',
    front: 'How does unstructured content (PDFs, articles) get used for grounding?',
    front_ja: '非構造化コンテンツ（PDF・記事）はどうグラウンディングに使う？',
    back: 'Ingested, chunked and placed in a search index, then read by retrievers. Structured data takes the other path: mapped to DMOs and read through data graphs.',
    back_ja: '取り込み・分割して検索インデックスに登録し、Retriever が読む。構造化データは別経路で、DMO にマッピングし Data Graph 経由で読む。',
  },
  {
    id: 'dc-fc-34',
    domain: 'dc-insights',
    front: 'How do you analyse Data 360 data?',
    front_ja: 'Data 360 のデータはどう分析する？',
    back: 'CRM Analytics and Tableau read Data 360 objects directly; Data Explorer and Query Editor cover ad-hoc inspection. Exporting to a spreadsheet is almost always wrong.',
    back_ja: 'CRM Analytics と Tableau が Data 360 のオブジェクトを直接読む。Data Explorer とクエリエディタはその場の確認用。表計算ソフトへのエクスポートはほぼ常に誤り。',
  },

  // ---- Activations and Utilization ----
  {
    id: 'dc-fc-35',
    domain: 'dc-activation',
    front: 'Segment, activation, activation target — which is which?',
    front_ja: 'セグメント・アクティベーション・アクティベーションターゲット — どれがどれ？',
    back: 'Segment = who. Activation target = where (create it first). Activation = what goes there and how often.',
    back_ja: 'セグメント＝誰を。アクティベーションターゲット＝どこへ（先に作る）。アクティベーション＝何を、どの頻度で。',
  },
  {
    id: 'dc-fc-36',
    domain: 'dc-activation',
    front: 'Activation vs data action — when do you use each?',
    front_ja: 'アクティベーションと Data Action の使い分けは？',
    back: 'Segment + activation for "send this population a campaign" (scheduled). Data action or triggered flow for "when this happens, do that" (event-driven, immediate).',
    back_ja: '「この母集団にキャンペーンを送る」（スケジュール）ならセグメント＋アクティベーション。「これが起きたらあれをする」（イベント駆動・即時）なら Data Action か起動フロー。',
  },
  {
    id: 'dc-fc-37',
    domain: 'dc-activation',
    front: 'The three data action targets?',
    front_ja: 'Data Action の3つのターゲットは？',
    back: 'Platform Event (into Salesforce automation), Webhook (to a non-Salesforce system), and Marketing Cloud. Do not confuse these with activation targets.',
    back_ja: 'プラットフォームイベント（Salesforce の自動化へ）、Webhook（Salesforce 以外へ）、Marketing Cloud。アクティベーションターゲットと混同しないこと。',
  },
  {
    id: 'dc-fc-38',
    domain: 'dc-activation',
    front: 'On which object is a people-targeting segment normally built?',
    front_ja: '人を対象とするセグメントは通常どのオブジェクトの上に作る？',
    back: 'The Unified Individual DMO. Building on a source DMO counts rows per system; building on a contact point counts email addresses.',
    back_ja: 'Unified Individual DMO。ソース側の DMO に作るとシステムごとの行を数え、Contact Point に作るとメールアドレスを数えてしまう。',
  },
  {
    id: 'dc-fc-39',
    domain: 'dc-activation',
    front: 'A segment "looks out of date" but ingestion and resolution are current. Why?',
    front_ja: '取り込みと解決は最新なのにセグメントが「古く見える」。なぜ？',
    back: 'It has not been republished. Membership is recalculated at publish time — a segment is not a continuously live query.',
    back_ja: '再公開されていない。メンバーシップは公開時に再計算される。セグメントは常時ライブなクエリではない。',
  },
  {
    id: 'dc-fc-40',
    domain: 'dc-activation',
    front: 'What bounds end-to-end data freshness?',
    front_ja: 'エンドツーエンドの鮮度は何で決まる？',
    back: 'Three independent schedules — ingestion, identity resolution and segment publishing. The slowest one governs. Add them up when a scenario states a deadline.',
    back_ja: '3つの独立したスケジュール（取り込み・ID解決・セグメント公開）。最も遅いものが支配する。期限が示されたシナリオでは足し合わせて考える。',
  },
  {
    id: 'dc-fc-41',
    domain: 'dc-activation',
    front: 'Fewer records reach the destination than the segment contains. Two likely causes?',
    front_ja: 'セグメントの件数より少ない数しか宛先に届かない。考えられる2つの原因は？',
    back: 'Consent filtering excluding opted-out individuals, or profiles missing an attribute the target requires. A wrong segment count would point upstream instead.',
    back_ja: '同意フィルタがオプトアウト済みの人を除外している、またはターゲットが必須とする属性をプロファイルが欠いている。セグメントの件数自体が誤っていれば原因は上流。',
  },
  {
    id: 'dc-fc-42',
    domain: 'dc-activation',
    front: 'How many attributes should an activation include?',
    front_ja: 'アクティベーションに含める属性はどれだけにすべき？',
    back: 'The minimum the destination actually needs. Minimisation applies at the exit as strongly as at ingestion — this is where personal data leaves the platform.',
    back_ja: '宛先が実際に必要とする最小限。最小化は取り込み時と同じ強さで出口にも当てはまる。ここが個人データがプラットフォームを出る地点。',
  },
  {
    id: 'dc-fc-43',
    domain: 'dc-activation',
    front: 'Data Cloud-triggered flow vs invocable action?',
    front_ja: 'Data Cloud 起動フローと Invocable Action の違いは？',
    back: 'Data 360 starts the flow → Data Cloud-triggered flow. A flow that is already running asks Data 360 a question → invocable action. Read the direction.',
    back_ja: 'Data 360 がフローを起動する→Data Cloud 起動フロー。既に動いているフローが Data 360 へ問い合わせる→Invocable Action。方向を読む。',
  },
  {
    id: 'dc-fc-44',
    domain: 'dc-activation',
    front: 'Where does consent live, and how should it be enforced?',
    front_ja: '同意はどこに紐づき、どう強制すべき？',
    back: 'With the contact point, not the person. Filter on it inside the segment or activation so the platform enforces it. Any answer of the form "tell the team to remember" is wrong.',
    back_ja: '人ではなく Contact Point に紐づく。セグメントかアクティベーションの内側で絞り込み、プラットフォームに強制させる。「チームに忘れないよう伝える」形の答えはすべて誤り。',
  },
]

export const flashcardsByDomain = (domainId) => flashcards.filter((c) => c.domain === domainId)
