// Data Cloud (Data 360) Consultant 用の用語集。
// 試験では聞き慣れない製品固有の名前（DLO / DMO / Segment On / Data Action …）が多いため、
// 意味をすばやく引けて、意味を隠して暗記もできるように独立したページにしている。
//
//   term   … 試験・画面に出てくる英語表記（常に表示）
//   ja     … 日本語での呼び方・ひとことの意味（常に表示）
//   def    … 定義（英日併記。表示言語の設定と各カードのボタンで切り替え）
//   tip    … 試験での問われ方（英日併記）
//   vs     … 取り違えやすい用語の id。カード上でリンクになる
//
// 教材本文（study/coreA.js・coreB.js）と記述を揃えている。

export const glossaryCategories = [
  {
    id: 'arch',
    name: 'アーキテクチャ',
    stage: '土台',
    description: '製品の全体像・データの置き場所・組織構成・課金の考え方。',
  },
  {
    id: 'ingest',
    name: '接続・取り込み',
    stage: '接続',
    description: 'データを入れる（またはコピーせず参照する）ための仕組み。',
  },
  {
    id: 'model',
    name: 'データモデル・マッピング',
    stage: '調和',
    description: '取り込んだ生データを共通の型（Customer 360 データモデル）へ揃える。',
  },
  {
    id: 'identity',
    name: 'ID解決',
    stage: '統合',
    description: '複数ソースに散らばった同一人物を1つのプロファイルにまとめる。',
  },
  {
    id: 'insights',
    name: 'インサイト・分析・AI',
    stage: '分析',
    description: '指標の算出、高速参照用のビュー、CRM からの参照、予測AI・生成AI。',
  },
  {
    id: 'activation',
    name: 'セグメント・アクティベーション',
    stage: '実行',
    description: '対象者を切り出し、外部チャネルや業務の現場へ届ける。',
  },
  {
    id: 'admin',
    name: '設定・ガバナンス',
    stage: '土台',
    description: '権限、データスペース、環境間の移行、同意とプライバシー。',
  },
]

export const glossaryIntro =
  'Data 360 の試験は、製品固有の名前が「どの段階の、何をする部品か」を言えるかどうかでほぼ決まります。上の流れ図で段階を選ぶか、検索して意味を確認してください。「意味を隠す」で用語だけを見て意味を思い出す練習ができ、覚えた用語には印を付けられます。'

// パイプライン図に並べる代表的なオブジェクト。上から順にデータが流れる。
export const glossaryFlow = [
  { stage: '接続', cat: 'ingest', items: ['connector', 'data-stream', 'zero-copy'] },
  { stage: '調和', cat: 'model', items: ['dso', 'dlo', 'mapping', 'dmo'] },
  { stage: '統合', cat: 'identity', items: ['match-rule', 'reconciliation-rule', 'unified-individual'] },
  { stage: '分析', cat: 'insights', items: ['calculated-insight', 'streaming-insight', 'data-graph'] },
  { stage: '実行', cat: 'activation', items: ['segment', 'activation', 'data-action'] },
]

export const glossary = [
  // ================= アーキテクチャ =================
  {
    id: 'data-360',
    cat: 'arch',
    term: 'Data 360 (formerly Data Cloud)',
    ja: 'データ 360（旧称 Data Cloud）',
    def: 'Salesforce\'s customer data platform. It connects to data where it lives, harmonises it into a shared model, resolves identities into one profile, and makes that profile actionable inside and outside Salesforce. Renamed from Data Cloud in 2025 — same product.',
    def_ja: 'Salesforce の顧客データプラットフォーム。データのある場所に接続し、共通モデルへ整え、ID を1つのプロファイルに解決し、Salesforce の内外で行動につなげる。2025年に Data Cloud から改称された（同一の製品）。',
    tip: 'It is not a CRM database and not a data warehouse. Records stay in their source systems; Data 360 builds a unified view across them.',
    tip_ja: 'CRM のデータベースでもデータウェアハウスでもない。レコードは元のシステムに残り、Data 360 はそれらを横断したビューを作る。',
    vs: ['cdp'],
  },
  {
    id: 'cdp',
    cat: 'arch',
    term: 'Customer Data Platform (CDP)',
    ja: '顧客データプラットフォーム',
    def: 'A category of software that collects first-party customer data from many systems and builds a persistent, unified profile per person that other systems can use. Data 360 is Salesforce\'s CDP (it was once branded Salesforce CDP).',
    def_ja: '多数のシステムから自社保有の顧客データを集め、1人につき1つの永続的な統合プロファイルを作り、他のシステムから使えるようにするソフトウェアの分類。Data 360 は Salesforce の CDP（かつては Salesforce CDP という名前だった）。',
    tip: 'Contrast with a DMP (anonymous third-party audiences) and a data warehouse (analytics storage). A CDP\'s defining output is the resolved individual.',
    tip_ja: 'DMP（匿名の第三者オーディエンス）やデータウェアハウス（分析用の保管庫）と対比される。CDP を特徴づける成果物は「解決済みの個人」。',
    vs: ['data-360'],
  },
  {
    id: 'pipeline',
    cat: 'arch',
    term: 'Connect → Harmonise → Unify → Analyse → Act',
    ja: 'Data 360 のパイプライン（5段階）',
    def: 'The order in which data moves through Data 360: bring data in, map it to the shared model, resolve identities, derive insights, then activate. Every feature belongs to one stage.',
    def_ja: 'Data 360 の中をデータが流れる順序。取り込む → 共通モデルへマッピング → ID を解決 → インサイトを算出 → アクティベーション。あらゆる機能はどこか1つの段階に属する。',
    tip: 'Most positioning questions reduce to "which stage does this term belong to?". Segmentation normally targets the unified profile, which only exists after the Unify stage.',
    tip_ja: '位置づけの設問はほぼ「この用語はどの段階か」に帰着する。セグメントの通常の対象は統合プロファイルで、それは統合段階の後にしか存在しない。',
  },
  {
    id: 'lakehouse',
    cat: 'arch',
    term: 'Data Lakehouse',
    ja: 'データレイクハウス（Data 360 の保存基盤）',
    def: 'The storage architecture underneath Data 360: data lives in open-format tables (Apache Iceberg / Parquet) that support both large-scale analytics and transactional-style access. It is separate from the CRM org\'s relational database.',
    def_ja: 'Data 360 の下にある保存方式。データはオープン形式のテーブル（Apache Iceberg／Parquet）に置かれ、大規模分析とトランザクション的な参照の両方に対応する。CRM 組織のリレーショナルデータベースとは別物。',
    tip: 'This is why Data 360 objects (DLOs, DMOs) are not ordinary sObjects, do not count against CRM data storage, and are queried with SQL rather than SOQL.',
    tip_ja: 'このため Data 360 のオブジェクト（DLO・DMO）は通常の sObject ではなく、CRM のデータストレージを消費せず、SOQL ではなく SQL でクエリする。',
    vs: ['query-api'],
  },
  {
    id: 'iceberg',
    cat: 'arch',
    term: 'Apache Iceberg',
    ja: 'アパッチ・アイスバーグ（オープンなテーブル形式）',
    def: 'An open table format used by the Data 360 lakehouse. Because it is open, external platforms such as Snowflake, Databricks and BigQuery can read shared data without copying it.',
    def_ja: 'Data 360 のレイクハウスが採用しているオープンなテーブル形式。オープンであるため、Snowflake・Databricks・BigQuery などの外部基盤がデータをコピーせずに読める。',
    tip: 'Appears as the technical reason Zero Copy is possible; you are rarely asked to configure it.',
    tip_ja: 'Zero Copy が可能な技術的理由として登場する。設定方法を問われることはほぼない。',
    vs: ['zero-copy'],
  },
  {
    id: 'hyperforce',
    cat: 'arch',
    term: 'Hyperforce',
    ja: 'ハイパーフォース（Salesforce のパブリッククラウド基盤）',
    def: 'Salesforce\'s infrastructure running on public cloud providers. Data 360 runs on Hyperforce, which determines the region where data is stored.',
    def_ja: 'パブリッククラウド上で動く Salesforce のインフラ。Data 360 は Hyperforce 上で動き、これによってデータを保存するリージョンが決まる。',
    tip: 'Relevant to data residency questions — the region is chosen at provisioning.',
    tip_ja: 'データ所在地（データレジデンシー）の設問に関係する。リージョンはプロビジョニング時に決まる。',
    vs: ['provisioning'],
  },
  {
    id: 'home-org',
    cat: 'arch',
    term: 'Data 360 home org',
    ja: 'ホーム組織（Data 360 を持つ組織）',
    def: 'The Salesforce org where Data 360 is provisioned. Other Salesforce orgs can be connected to it as data sources, and with Data 360 One companion orgs can use the home org\'s data without their own instance.',
    def_ja: 'Data 360 がプロビジョニングされた Salesforce 組織。他の Salesforce 組織はデータソースとして接続でき、Data 360 One を使えばコンパニオン組織が自前のインスタンスなしでホーム組織のデータを使える。',
    tip: 'One Data 360 instance can serve many orgs. A scenario with several business-unit orgs rarely needs several Data 360 instances.',
    tip_ja: '1つの Data 360 インスタンスで複数組織に対応できる。事業部ごとに組織がある設問でも、Data 360 を複数用意する必要はまずない。',
    vs: ['companion-org', 'data-space'],
  },
  {
    id: 'companion-org',
    cat: 'arch',
    term: 'Companion org (Data 360 One)',
    ja: 'コンパニオン組織',
    def: 'A Salesforce org connected to a Data 360 home org through Data 360 One, so its users can work with the home org\'s unified data — segments, profiles, enrichments — from inside their own org.',
    def_ja: 'Data 360 One によってホーム組織に接続された Salesforce 組織。そのユーザーは自分の組織の中から、ホーム組織の統合データ（セグメント、プロファイル、エンリッチメント）を使える。',
    tip: 'The data stays in the home org; access is typically scoped by data space.',
    tip_ja: 'データはホーム組織に残る。アクセス範囲は通常データスペースで区切る。',
    vs: ['home-org'],
  },
  {
    id: 'credits',
    cat: 'arch',
    term: 'Consumption credits',
    ja: 'クレジット（従量課金の単位）',
    def: 'Data 360 is priced by consumption. Ingestion, batch and streaming processing, identity resolution, queries, segmentation and activation all consume credits at different rates.',
    def_ja: 'Data 360 は従量課金。取り込み、バッチ・ストリーミング処理、ID解決、クエリ、セグメンテーション、アクティベーションがそれぞれ異なる単価でクレジットを消費する。',
    tip: 'Cost-aware answers win: ingest only needed fields, avoid needless full refreshes, prefer Zero Copy for large external data, and choose sensible publish schedules.',
    tip_ja: 'コストを意識した選択肢が正解になりやすい。必要な項目だけ取り込む、不要な全件更新を避ける、大きな外部データは Zero Copy、公開スケジュールは妥当な間隔に。',
    vs: ['digital-wallet'],
  },
  {
    id: 'digital-wallet',
    cat: 'arch',
    term: 'Digital Wallet',
    ja: 'デジタルウォレット（消費量の確認画面）',
    def: 'The place in Salesforce where admins monitor consumption-based usage — how many credits have been used, by which feature, over time.',
    def_ja: '従量課金の利用状況（どの機能がいつどれだけクレジットを使ったか）を管理者が確認する Salesforce 内の画面。',
    tip: 'The answer to "how can the admin see which process is consuming the most credits?".',
    tip_ja: '「どの処理が最もクレジットを消費しているか管理者が確認するには？」の答え。',
    vs: ['credits'],
  },

  // ================= 接続・取り込み =================
  {
    id: 'connector',
    cat: 'ingest',
    term: 'Connector',
    ja: 'コネクタ（データソースとの接続口）',
    def: 'A prebuilt integration that lets Data 360 read from a source: Salesforce CRM, Marketing Cloud Engagement, Commerce Cloud, Amazon S3, Google Cloud Storage, Azure, SFTP, Snowflake and many others via MuleSoft.',
    def_ja: 'Data 360 がソースからデータを読むための既製の連携。Salesforce CRM、Marketing Cloud Engagement、Commerce Cloud、Amazon S3、Google Cloud Storage、Azure、SFTP、Snowflake など。MuleSoft 経由でさらに多数。',
    tip: 'Always prefer a native connector over custom code when one exists. Custom sources with no connector use the Ingestion API.',
    tip_ja: '既製のコネクタがあれば、独自コードより常に優先する。コネクタが無い独自ソースは Ingestion API を使う。',
    vs: ['ingestion-api', 'data-stream'],
  },
  {
    id: 'crm-connector',
    cat: 'ingest',
    term: 'Salesforce CRM Connector',
    ja: 'Salesforce CRM コネクタ',
    def: 'The native connector that ingests objects (Contact, Lead, Account, custom objects …) from one or more Salesforce orgs. Starter data bundles create the streams and mappings for common objects in one step.',
    def_ja: '1つ以上の Salesforce 組織からオブジェクト（取引先責任者、リード、取引先、カスタムオブジェクトなど）を取り込む標準コネクタ。スターターのデータバンドルを使うと、主要オブジェクトのストリームとマッピングを一括で作れる。',
    tip: 'Field access for ingestion comes from the Data Cloud integration user\'s permissions — a field that "will not appear" is usually a field-level security issue on that user.',
    tip_ja: '取り込める項目は Data Cloud の連携ユーザーの権限で決まる。「項目が表示されない」の原因は、たいていその連携ユーザーの項目レベルセキュリティ。',
    vs: ['data-bundle'],
  },
  {
    id: 'data-bundle',
    cat: 'ingest',
    term: 'Data bundle (starter bundle)',
    ja: 'データバンドル（取り込み設定のひな形）',
    def: 'A prepackaged set of data streams and mappings for a known source — for example Sales Cloud, Service Cloud or Marketing Cloud Engagement — that sets up standard objects and their DMO mappings automatically.',
    def_ja: '既知のソース（Sales Cloud、Service Cloud、Marketing Cloud Engagement など）向けに、データストリームとマッピングをまとめたひな形。標準オブジェクトと DMO へのマッピングを自動で作る。',
    tip: 'The fastest correct answer for standard CRM or Marketing Cloud sources. Do not confuse with a data kit, which moves your own configuration between orgs.',
    tip_ja: '標準的な CRM や Marketing Cloud のソースなら最速の正解。自分の設定を組織間で移すデータキットと混同しないこと。',
    vs: ['data-kit'],
  },
  {
    id: 'ingestion-api',
    cat: 'ingest',
    term: 'Ingestion API',
    ja: 'インジェスチョン API（独自ソースからの取り込み）',
    def: 'A REST API for pushing data from systems without a connector. It has two modes — streaming (small JSON payloads, near real time) and bulk (large CSV jobs). The schema is defined by uploading an OpenAPI (YAML) file.',
    def_ja: 'コネクタの無いシステムからデータを送り込むための REST API。ストリーミング（小さな JSON を準リアルタイムで）とバルク（大きな CSV のジョブ）の2モードがある。スキーマは OpenAPI（YAML）ファイルをアップロードして定義する。',
    tip: 'Streaming for frequent small updates, bulk for periodic large loads. A connected app with OAuth is required to call it.',
    tip_ja: '頻繁で小さい更新はストリーミング、定期的な大量ロードはバルク。呼び出しには OAuth の接続アプリケーションが必要。',
    vs: ['connector', 'web-sdk'],
  },
  {
    id: 'web-sdk',
    cat: 'ingest',
    term: 'Web & Mobile SDK (Interactions SDK)',
    ja: 'Web・モバイル SDK（行動データの収集）',
    def: 'JavaScript and mobile SDKs that capture behavioural events — page views, clicks, add-to-cart — from websites and apps and send them to Data 360 as engagement data. A sitemap defines which events are captured.',
    def_ja: 'Web サイトやアプリからページ閲覧・クリック・カート追加などの行動イベントを取得し、エンゲージメントデータとして Data 360 へ送る JavaScript／モバイルの SDK。どのイベントを取るかはサイトマップで定義する。',
    tip: 'Visitors start as anonymous profiles; they join a known profile when identity resolution can link them (for example after login).',
    tip_ja: '訪問者は最初は匿名プロファイル。ログイン後など、ID解決で結び付けられた時点で既知のプロファイルに合流する。',
    vs: ['ingestion-api', 'anonymous-profile'],
  },
  {
    id: 'data-stream',
    cat: 'ingest',
    term: 'Data stream',
    ja: 'データストリーム（取り込みの設定単位）',
    def: 'The configured flow of data from one source object into Data 360. Creating a data stream defines the source, the fields, the category, the primary key and the refresh schedule, and produces a DLO.',
    def_ja: '1つのソースオブジェクトから Data 360 へのデータの流れを設定したもの。作成時にソース、項目、カテゴリ、主キー、更新スケジュールを決め、その結果 DLO ができる。',
    tip: 'Data stream → DLO → DMO is the core chain. A stream is configuration; the DLO is where the data lands.',
    tip_ja: 'データストリーム → DLO → DMO が中核の連鎖。ストリームは「設定」で、データが入る場所は DLO。',
    vs: ['dlo', 'stream-category'],
  },
  {
    id: 'stream-category',
    cat: 'ingest',
    term: 'Data stream category: Profile / Engagement / Other',
    ja: 'データストリームのカテゴリ（プロファイル／エンゲージメント／その他）',
    def: 'Every data stream is classified at creation. Profile = who someone is (customers, contacts). Engagement = time-stamped events (orders, email opens, web visits) and requires an event time field. Other = everything else (products, stores, reference data).',
    def_ja: 'データストリームは作成時に分類する。プロファイル＝その人が誰か（顧客・取引先責任者）。エンゲージメント＝時刻付きの出来事（注文、メール開封、Web 訪問）で、イベント日時項目が必須。その他＝それ以外（商品、店舗、参照データ）。',
    tip: 'The category cannot be changed after the stream is created — the fix is to recreate the stream. Engagement data is what time windows in segments and streaming insights work on.',
    tip_ja: 'カテゴリはストリーム作成後に変更できない。直すにはストリームを作り直す。セグメントや Streaming Insight の期間指定はエンゲージメントデータに対して働く。',
    vs: ['event-time'],
  },
  {
    id: 'event-time',
    cat: 'ingest',
    term: 'Event time field',
    ja: 'イベント日時項目',
    def: 'The date-time field on an engagement data stream that records when the event happened. It drives time-based filtering, streaming insight windows and data retention for engagement data.',
    def_ja: 'エンゲージメントのデータストリームで、出来事が起きた日時を表す項目。期間による絞り込み、Streaming Insight の時間枠、エンゲージメントデータの保持に使われる。',
    tip: 'Required for the Engagement category. Pick the time the event occurred, not the time the record was loaded.',
    tip_ja: 'エンゲージメントのカテゴリでは必須。レコードを読み込んだ日時ではなく、出来事が起きた日時を選ぶ。',
    vs: ['stream-category'],
  },
  {
    id: 'primary-key',
    cat: 'ingest',
    term: 'Primary key',
    ja: '主キー',
    def: 'The field that uniquely identifies each record in a data stream. Data 360 uses it to decide whether an incoming row updates an existing record or creates a new one.',
    def_ja: 'データストリームの各レコードを一意に識別する項目。取り込んだ行が既存レコードの更新か新規作成かを、Data 360 はこれで判断する。',
    tip: 'If the source has no single unique field, create a formula field that concatenates several fields and use that as the key.',
    tip_ja: 'ソースに単独で一意な項目が無い場合は、複数項目を連結する数式項目を作って主キーにする。',
    vs: ['key-qualifier', 'formula-field'],
  },
  {
    id: 'formula-field',
    cat: 'ingest',
    term: 'Formula field (on a data stream)',
    ja: '数式項目（データストリーム上）',
    def: 'A field calculated at ingestion time from other fields in the same row — for example a concatenated key, a normalised value or a derived flag.',
    def_ja: '取り込み時に、同じ行の他の項目から計算される項目。連結したキー、正規化した値、派生フラグなど。',
    tip: 'Row-level only. Anything that needs joins or aggregation across rows belongs in a data transform or calculated insight instead.',
    tip_ja: '行単位の計算だけ。行をまたぐ結合や集計が必要なら、データ変換か Calculated Insight を使う。',
    vs: ['data-transform', 'calculated-insight'],
  },
  {
    id: 'refresh-mode',
    cat: 'ingest',
    term: 'Refresh mode: Upsert vs Full Refresh',
    ja: '更新モード（差分更新／全件置き換え）',
    def: 'How a data stream applies new data. Upsert inserts new rows and updates existing ones by primary key (incremental). Full Refresh replaces the entire contents of the DLO on each run.',
    def_ja: 'データストリームが新しいデータをどう反映するか。Upsert は主キーで新規行を追加し既存行を更新する（差分）。Full Refresh は実行のたびに DLO の中身を丸ごと置き換える。',
    tip: 'Upsert is the default and cheaper choice. Full refresh suits small reference files that are always delivered complete — or when deleted source rows must disappear.',
    tip_ja: 'Upsert が既定で安価。常に全件で届く小さな参照ファイルや、ソースで削除された行を消す必要がある場合は Full Refresh。',
    vs: ['data-stream'],
  },
  {
    id: 'data-transform',
    cat: 'ingest',
    term: 'Data transform (batch / streaming)',
    ja: 'データ変換',
    def: 'A process that reshapes data after ingestion — joining, filtering, aggregating or cleaning DLOs — and writes the result to another DLO. Batch transforms run on a schedule; streaming transforms process records as they arrive.',
    def_ja: '取り込み後のデータを作り替える処理。DLO の結合・絞り込み・集計・クレンジングを行い、結果を別の DLO に書き込む。バッチ変換はスケジュール実行、ストリーミング変換は届いた順に処理する。',
    tip: 'Use it when data must be restructured before mapping (for example, unpivoting or splitting a combined name field). For metrics about customers, use a calculated insight instead.',
    tip_ja: 'マッピング前にデータの形を変える必要があるとき（縦横変換、結合された氏名の分割など）に使う。顧客についての指標なら Calculated Insight を使う。',
    vs: ['formula-field', 'calculated-insight'],
  },
  {
    id: 'zero-copy',
    cat: 'ingest',
    term: 'Zero Copy',
    ja: 'ゼロコピー（コピーせずにデータを使う）',
    def: 'The umbrella term for using data across Data 360 and external platforms (Snowflake, Databricks, Google BigQuery, Amazon Redshift) without physically copying it. It has two directions: data federation (in) and data sharing (out).',
    def_ja: 'Data 360 と外部基盤（Snowflake、Databricks、Google BigQuery、Amazon Redshift）の間で、データを物理的にコピーせずに使う仕組みの総称。流入方向のデータフェデレーションと、流出方向のデータ共有の2方向がある。',
    tip: 'The favoured answer when a customer has large data in a warehouse and wants to avoid duplication, ETL pipelines or storage cost.',
    tip_ja: 'ウェアハウスに大量のデータがあり、重複・ETL・保存コストを避けたい設問で好まれる答え。',
    vs: ['federation', 'data-share'],
  },
  {
    id: 'federation',
    cat: 'ingest',
    term: 'Data federation (external DLO)',
    ja: 'データフェデレーション（外部データの参照）',
    def: 'The inbound half of Zero Copy: Data 360 queries a table in an external warehouse in place. The table appears as an external DLO that can be mapped and used like any other. Queries can run live or use acceleration (a cached copy refreshed on a schedule).',
    def_ja: 'Zero Copy の流入側。Data 360 が外部ウェアハウスのテーブルをその場でクエリする。そのテーブルは外部 DLO として見え、他の DLO と同じようにマッピング・利用できる。クエリはライブ実行か、アクセラレーション（定期更新されるキャッシュ）を使う。',
    tip: 'Direction test: warehouse → Data 360 is federation; Data 360 → warehouse is sharing.',
    tip_ja: '向きで見分ける。ウェアハウス → Data 360 がフェデレーション、Data 360 → ウェアハウスが共有。',
    vs: ['data-share', 'zero-copy'],
  },
  {
    id: 'data-share',
    cat: 'ingest',
    term: 'Data share / Data share target',
    ja: 'データ共有（Data 360 から外部へ）',
    def: 'The outbound half of Zero Copy: selected Data 360 objects (DLOs, DMOs, calculated insights) are exposed to an external warehouse, which reads them directly without an export. The data share target defines the destination account.',
    def_ja: 'Zero Copy の流出側。選んだ Data 360 のオブジェクト（DLO、DMO、Calculated Insight）を外部ウェアハウスに公開し、エクスポートなしで直接読ませる。共有先のアカウントはデータ共有ターゲットで定義する。',
    tip: 'Use it when a data science team wants unified profiles in Snowflake or Databricks for their own modelling.',
    tip_ja: 'データサイエンスチームが自社のモデリングのために Snowflake や Databricks で統合プロファイルを使いたい、という設問で使う。',
    vs: ['federation', 'activation'],
  },

  // ================= データモデル・マッピング =================
  {
    id: 'dso',
    cat: 'model',
    term: 'Data Source Object (DSO)',
    ja: 'データソースオブジェクト（取り込み直後の一時的な置き場）',
    def: 'The staging object that holds data exactly as it arrives from the source, before it is written to the DLO. It is transient and not used directly for modelling.',
    def_ja: 'ソースから届いたデータをそのままの形で保持し、DLO に書き込む前に使う中継用のオブジェクト。一時的なもので、モデリングには直接使わない。',
    tip: 'Order to remember: DSO → DLO → DMO. Questions mostly focus on DLO and DMO.',
    tip_ja: '順序は DSO → DLO → DMO。設問の中心は DLO と DMO。',
    vs: ['dlo'],
  },
  {
    id: 'dlo',
    cat: 'model',
    term: 'Data Lake Object (DLO)',
    ja: 'データレイクオブジェクト（取り込んだ生データ）',
    def: 'The storage object created by a data stream. It keeps the source\'s own structure and field names. Nothing downstream — identity resolution, segments, insights — can use it until it is mapped to a DMO.',
    def_ja: 'データストリームによって作られる保存用オブジェクト。ソースの構造と項目名をそのまま保つ。DMO へマッピングするまでは、ID解決・セグメント・インサイトなど下流の機能からは使えない。',
    tip: '"Data was ingested but does not appear in segmentation" → the DLO has not been mapped (or is mapped to the wrong DMO).',
    tip_ja: '「取り込んだのにセグメントに出てこない」→ DLO がマッピングされていない（または誤った DMO にマッピングされている）。',
    vs: ['dmo', 'dso', 'data-stream'],
  },
  {
    id: 'dmo',
    cat: 'model',
    term: 'Data Model Object (DMO)',
    ja: 'データモデルオブジェクト（共通の型に揃えたデータ）',
    def: 'An object in the Customer 360 data model — Individual, Contact Point Email, Sales Order and so on. Many DLOs from different sources are mapped into the same DMO so the data shares one structure.',
    def_ja: 'Customer 360 データモデルのオブジェクト（Individual、Contact Point Email、Sales Order など）。異なるソースの複数の DLO を同じ DMO にマッピングし、データを1つの構造に揃える。',
    tip: 'DLO = source shape; DMO = shared shape. DMOs are a virtual, harmonised view over the mapped DLOs.',
    tip_ja: 'DLO＝ソースの形、DMO＝共通の形。DMO はマッピングされた DLO の上に乗る、調和済みの仮想的なビュー。',
    vs: ['dlo', 'c360-model'],
  },
  {
    id: 'c360-model',
    cat: 'model',
    term: 'Customer 360 Data Model',
    ja: 'Customer 360 データモデル（Salesforce 標準の共通データモデル）',
    def: 'Salesforce\'s standard, canonical data model for customer data, organised into subject areas (Party, Engagement, Sales Order, Product, Case …). Mapping to it is what lets features work the same way regardless of source.',
    def_ja: '顧客データのための Salesforce 標準の正規データモデル。サブジェクトエリア（Party、Engagement、Sales Order、Product、Case など）に分かれる。これにマッピングすることで、どのソースでも機能が同じように動く。',
    tip: 'Prefer standard DMOs and standard fields. Create custom DMOs or fields only when nothing standard fits.',
    tip_ja: '標準の DMO と標準項目を優先する。当てはまるものが無いときだけカスタム DMO・カスタム項目を作る。',
    vs: ['subject-area', 'dmo'],
  },
  {
    id: 'subject-area',
    cat: 'model',
    term: 'Subject area',
    ja: 'サブジェクトエリア（データモデルの分類）',
    def: 'A grouping of related DMOs in the Customer 360 data model — for example Party (people and their identifiers), Engagement (events), Sales Order, Product and Case.',
    def_ja: 'Customer 360 データモデルで関連する DMO をまとめた区分。Party（人とその識別子）、Engagement（出来事）、Sales Order、Product、Case など。',
    tip: 'The Party subject area is the one identity resolution depends on.',
    tip_ja: 'ID解決が依存するのは Party のサブジェクトエリア。',
    vs: ['c360-model'],
  },
  {
    id: 'mapping',
    cat: 'model',
    term: 'Data mapping',
    ja: 'データマッピング（DLO の項目を DMO の項目へ対応づける）',
    def: 'The step that connects each DLO field to a DMO field. Mapping is what makes ingested data visible to identity resolution, insights, segmentation and activation.',
    def_ja: 'DLO の各項目を DMO の項目へ対応づける作業。マッピングによって、取り込んだデータが ID解決・インサイト・セグメント・アクティベーションから見えるようになる。',
    tip: 'For identity resolution you must map to Individual plus at least one contact point or Party Identification, and set the relationships between them.',
    tip_ja: 'ID解決のためには Individual と、少なくとも1つの Contact Point または Party Identification にマッピングし、その間のリレーションを設定する必要がある。',
    vs: ['relationship'],
  },
  {
    id: 'relationship',
    cat: 'model',
    term: 'Data model relationship',
    ja: 'リレーション（DMO 同士のつながり）',
    def: 'A defined join between two DMOs, such as Contact Point Email → Individual or Sales Order → Individual, with a cardinality (one-to-one or many-to-one).',
    def_ja: '2つの DMO の間に定義した結合。Contact Point Email → Individual、Sales Order → Individual など。カーディナリティ（1対1／多対1）を持つ。',
    tip: 'Segments can only filter on related data along these paths. A missing relationship is a common reason an attribute cannot be used.',
    tip_ja: 'セグメントはこの経路でつながったデータにしか条件を掛けられない。属性が使えない原因として、リレーションの欠落がよく出る。',
    vs: ['mapping'],
  },
  {
    id: 'key-qualifier',
    cat: 'model',
    term: 'Key qualifier',
    ja: 'キー修飾子（ソースごとの主キーを区別する）',
    def: 'A field added alongside a primary or foreign key that records which source the key came from, so that the same key value from two systems (for example ID 1001 in CRM and in ERP) is not joined incorrectly.',
    def_ja: '主キー・外部キーと並べて、そのキーがどのソース由来かを記録する項目。2つのシステムの同じキー値（CRM の ID 1001 と ERP の ID 1001 など）を誤って結合しないようにする。',
    tip: 'The answer to "records from two sources are joining incorrectly because they share ID values".',
    tip_ja: '「2つのソースの ID 値が重なり、レコードが誤って結合される」への答え。',
    vs: ['primary-key'],
  },
  {
    id: 'individual',
    cat: 'model',
    term: 'Individual (DMO)',
    ja: 'Individual（個人を表す DMO）',
    def: 'The DMO representing a person, with attributes such as first name, last name and birth date. Each source contributes its own Individual records; identity resolution merges them.',
    def_ja: '人物を表す DMO。名、姓、生年月日などの属性を持つ。各ソースがそれぞれ Individual のレコードを持ち込み、ID解決がそれらを統合する。',
    tip: 'Mapping to Individual is mandatory for identity resolution. Individual (per source) is not the same as Unified Individual (the merged result).',
    tip_ja: 'ID解決には Individual へのマッピングが必須。Individual（ソースごと）と Unified Individual（統合結果）は別物。',
    vs: ['unified-individual', 'contact-point'],
  },
  {
    id: 'contact-point',
    cat: 'model',
    term: 'Contact Point (Email / Phone / Address / App)',
    ja: 'コンタクトポイント（連絡先を表す DMO）',
    def: 'DMOs that hold the ways to reach a person — Contact Point Email, Contact Point Phone, Contact Point Address, Contact Point App — each related to an Individual. One person can have many.',
    def_ja: '人物への連絡手段を持つ DMO 群（Contact Point Email、Contact Point Phone、Contact Point Address、Contact Point App）。それぞれ Individual に関連し、1人が複数持てる。',
    tip: 'Match rules usually match on contact points (email, phone). Activation needs a contact point to deliver the segment to a channel.',
    tip_ja: '一致ルールは通常コンタクトポイント（メール・電話）で照合する。アクティベーションでセグメントをチャネルへ届けるにもコンタクトポイントが必要。',
    vs: ['party-identification', 'individual'],
  },
  {
    id: 'party-identification',
    cat: 'model',
    term: 'Party Identification',
    ja: 'パーティ識別子（会員番号などの ID を持つ DMO）',
    def: 'The DMO for identifiers that are not contact points — loyalty numbers, customer IDs, driver\'s licence numbers — along with the identifier type and issuer.',
    def_ja: 'コンタクトポイントではない識別子（会員番号、顧客 ID、運転免許証番号など）を、識別子の種類・発行元と一緒に持つ DMO。',
    tip: 'Map a loyalty or customer ID here, then use it in a match rule. It is often the most reliable match key.',
    tip_ja: '会員番号や顧客 ID はここへマッピングし、一致ルールで使う。最も信頼できる照合キーになることが多い。',
    vs: ['contact-point'],
  },
  {
    id: 'engagement-dmo',
    cat: 'model',
    term: 'Engagement DMOs',
    ja: 'エンゲージメント DMO（行動・取引の記録）',
    def: 'DMOs that record events — Email Engagement, Web Engagement, Sales Order, Case and similar. They are related back to the Individual and carry an event date.',
    def_ja: '出来事を記録する DMO（Email Engagement、Web Engagement、Sales Order、Case など）。Individual に関連付けられ、イベント日時を持つ。',
    tip: 'Behaviour-based segments ("opened an email in the last 30 days") filter on engagement DMOs.',
    tip_ja: '行動ベースのセグメント（「過去30日にメールを開封した」）はエンゲージメント DMO に条件を掛ける。',
    vs: ['stream-category'],
  },

  // ================= ID解決 =================
  {
    id: 'identity-resolution',
    cat: 'identity',
    term: 'Identity resolution',
    ja: 'ID解決（名寄せ）',
    def: 'The process that decides which source records belong to the same person and builds one unified profile from them. It is configured as a ruleset of match rules and reconciliation rules.',
    def_ja: 'どのソースレコードが同じ人物のものかを判断し、それらから1つの統合プロファイルを作る処理。一致ルールと調整ルールからなるルールセットとして設定する。',
    tip: 'Resolution never deletes or merges source records — sources stay intact and are linked to the unified profile.',
    tip_ja: 'ID解決はソースレコードを削除も結合もしない。ソースはそのまま残り、統合プロファイルへリンクされる。',
    vs: ['match-rule', 'reconciliation-rule'],
  },
  {
    id: 'ruleset',
    cat: 'identity',
    term: 'Identity resolution ruleset',
    ja: 'ID解決ルールセット',
    def: 'The container for a set of match rules and reconciliation rules, applied to a profile DMO (Individual, or Account for B2B). It runs on a schedule and outputs unified objects.',
    def_ja: '一致ルールと調整ルールをまとめた入れ物。プロファイル DMO（Individual、B2B なら Account）に適用し、スケジュールで実行されて統合オブジェクトを出力する。',
    tip: 'Separate rulesets let you compare strategies or unify accounts and individuals separately. The number of rulesets per org is limited.',
    tip_ja: 'ルールセットを分けると、方針の比較や、取引先と個人の別々の統合ができる。組織あたりのルールセット数には上限がある。',
    vs: ['identity-resolution'],
  },
  {
    id: 'match-rule',
    cat: 'identity',
    term: 'Match rule',
    ja: '一致ルール（同一人物かどうかの判定条件）',
    def: 'A set of criteria that, if all met, means two records are the same person — for example "exact normalised email" or "fuzzy first name + exact last name + exact phone". Any one match rule matching is enough.',
    def_ja: 'すべて満たせば2つのレコードを同一人物とみなす条件の組み合わせ。例：「正規化したメールが完全一致」「名があいまい一致＋姓が完全一致＋電話が完全一致」。どれか1つの一致ルールに該当すれば一致となる。',
    tip: 'Match rules decide WHO is the same; reconciliation rules decide WHICH value wins. Criteria inside a rule are AND; separate rules are OR.',
    tip_ja: '一致ルールは「誰が同一か」、調整ルールは「どの値を採用するか」。1つのルール内の条件は AND、ルール同士は OR。',
    vs: ['reconciliation-rule', 'match-method'],
  },
  {
    id: 'match-method',
    cat: 'identity',
    term: 'Match method: Exact / Exact Normalized / Fuzzy',
    ja: '照合方法（完全一致／正規化して完全一致／あいまい一致）',
    def: 'How a field is compared in a match rule. Exact compares the raw value. Exact Normalized compares after standardising case, spacing and format (emails, phones, addresses). Fuzzy tolerates small differences such as nicknames and typos, and is intended for first names.',
    def_ja: '一致ルールで項目をどう比較するか。Exact は値そのものを比較。Exact Normalized は大文字小文字・空白・書式を標準化してから比較（メール、電話、住所）。Fuzzy は愛称や入力ミスなど小さな違いを許容し、名（ファーストネーム）向け。',
    tip: 'Use fuzzy only together with stronger criteria — fuzzy name alone would over-merge different people.',
    tip_ja: 'あいまい一致は必ず強い条件と組み合わせる。名前のあいまい一致だけだと別人まで統合してしまう。',
    vs: ['match-rule'],
  },
  {
    id: 'reconciliation-rule',
    cat: 'identity',
    term: 'Reconciliation rule',
    ja: '調整ルール（どの値を統合プロファイルに採用するか）',
    def: 'The rule that chooses which value is kept on the unified profile when matched records disagree. Options are Last Updated, Most Frequent and Source Priority, set per field or per object.',
    def_ja: '一致したレコード同士で値が食い違うとき、統合プロファイルにどの値を残すかを選ぶルール。Last Updated（最終更新）、Most Frequent（最頻値）、Source Priority（ソースの優先順位）から、項目またはオブジェクトごとに設定する。',
    tip: '"The CRM value should always win over the e-commerce value" → Source Priority. "Use the most recent address" → Last Updated.',
    tip_ja: '「常に CRM の値を EC より優先したい」→ Source Priority。「最新の住所を使いたい」→ Last Updated。',
    vs: ['match-rule'],
  },
  {
    id: 'unified-individual',
    cat: 'identity',
    term: 'Unified Individual (unified profile)',
    ja: '統合個人（統合プロファイル）',
    def: 'The output of identity resolution: one profile per real person, with attributes chosen by reconciliation rules and unified contact points attached. It is the usual target of segmentation.',
    def_ja: 'ID解決の成果物。実在の1人につき1つのプロファイルで、属性は調整ルールで選ばれ、統合されたコンタクトポイントが付く。セグメントの通常の対象。',
    tip: 'Segment on Unified Individual, not Individual, to avoid counting and messaging the same person several times.',
    tip_ja: 'セグメントは Individual ではなく Unified Individual を対象にする。同じ人を重複して数えたり、何度も配信したりしないため。',
    vs: ['individual', 'unified-link'],
  },
  {
    id: 'unified-link',
    cat: 'identity',
    term: 'Unified Link object',
    ja: '統合リンクオブジェクト（統合結果と元レコードの対応表）',
    def: 'The object that connects each unified profile to the source records it was built from, for example Unified Link Individual. It is how you trace a unified profile back to its sources.',
    def_ja: '各統合プロファイルと、その元になったソースレコードを結ぶオブジェクト（Unified Link Individual など）。統合プロファイルから元のソースをたどるために使う。',
    tip: 'The answer when a question asks how to see which source records were merged into a profile.',
    tip_ja: '「どのソースレコードがプロファイルに統合されたか確認するには？」の答え。',
    vs: ['unified-individual'],
  },
  {
    id: 'consolidation-rate',
    cat: 'identity',
    term: 'Consolidation rate',
    ja: '統合率',
    def: 'The percentage by which identity resolution reduced source profiles into unified profiles. 1,000 source records resolving into 700 unified profiles is a 30% consolidation rate.',
    def_ja: 'ID解決でソースのプロファイル数がどれだけ減ったかの割合。1,000件のソースレコードが700件の統合プロファイルになれば統合率は30%。',
    tip: 'Too low → rules are too strict or key data is missing. Suspiciously high → rules are too loose and are merging different people.',
    tip_ja: '低すぎる → ルールが厳しすぎるか、照合キーのデータが欠けている。高すぎる → ルールが緩すぎて別人を統合している。',
    vs: ['match-rule'],
  },
  {
    id: 'anonymous-profile',
    cat: 'identity',
    term: 'Anonymous vs known profile',
    ja: '匿名プロファイルと既知プロファイル',
    def: 'An anonymous profile is created from behaviour with no identifying data (for example a cookie from the Web SDK). A known profile has identifying data such as an email. Once a link appears — a login, a form fill — identity resolution can join them.',
    def_ja: '匿名プロファイルは識別情報の無い行動データ（Web SDK の Cookie など）から作られる。既知プロファイルはメールなどの識別情報を持つ。ログインやフォーム入力でつながりが生まれると、ID解決が両者を結び付けられる。',
    tip: 'Anonymous profiles still consume and can be segmented, but cannot be reached by email until they become known.',
    tip_ja: '匿名プロファイルもクレジットを消費しセグメント化できるが、既知になるまでメールでは届けられない。',
    vs: ['web-sdk'],
  },

  // ================= インサイト・分析・AI =================
  {
    id: 'calculated-insight',
    cat: 'insights',
    term: 'Calculated Insight (CI)',
    ja: '計算インサイト（バッチで計算する指標）',
    def: 'A metric defined in SQL (or the visual builder) over DMOs and run in batch — lifetime value, order count, days since last purchase. It has measures (the numbers) and dimensions (what they are grouped by).',
    def_ja: 'DMO に対して SQL（またはビジュアルビルダー）で定義し、バッチで実行する指標。生涯価値、注文回数、最終購入からの日数など。メジャー（数値）とディメンション（集計の切り口）を持つ。',
    tip: 'Need a complex, multi-object aggregate to use in segments → calculated insight. Needs to react within minutes → streaming insight.',
    tip_ja: '複数オブジェクトをまたぐ複雑な集計をセグメントで使いたい → Calculated Insight。数分以内に反応したい → Streaming Insight。',
    vs: ['streaming-insight', 'formula-field', 'data-transform'],
  },
  {
    id: 'measure-dimension',
    cat: 'insights',
    term: 'Measure vs Dimension',
    ja: 'メジャーとディメンション',
    def: 'In an insight, a measure is an aggregated number (SUM of order amount, COUNT of visits) and a dimension is an attribute it is grouped by (customer ID, product category, store).',
    def_ja: 'インサイトにおいて、メジャーは集計された数値（注文金額の合計、訪問回数）、ディメンションはその集計の切り口となる属性（顧客 ID、商品カテゴリ、店舗）。',
    tip: 'To use an insight in segmentation it must include a dimension that links to the segment entity (typically the unified individual ID).',
    tip_ja: 'インサイトをセグメントで使うには、セグメント対象（通常は統合個人の ID）につながるディメンションを含める必要がある。',
    vs: ['calculated-insight'],
  },
  {
    id: 'streaming-insight',
    cat: 'insights',
    term: 'Streaming Insight',
    ja: 'ストリーミングインサイト（準リアルタイムの指標）',
    def: 'A metric computed continuously over streaming engagement data within a time window — for example "3 failed logins in 10 minutes" or "cart value in the last hour". It is typically paired with a data action to trigger a response.',
    def_ja: 'ストリーミングのエンゲージメントデータを時間枠で区切って継続的に計算する指標。例：「10分間に3回ログイン失敗」「直近1時間のカート金額」。通常は Data Action と組み合わせて反応を起こす。',
    tip: 'Streaming insights are simpler (windowed aggregates over one stream) but fast. Complex joins across many objects belong in calculated insights.',
    tip_ja: 'Streaming Insight は単純（1つのストリームを時間枠で集計）だが速い。多数のオブジェクトの複雑な結合は Calculated Insight で行う。',
    vs: ['calculated-insight', 'data-action'],
  },
  {
    id: 'data-graph',
    cat: 'insights',
    term: 'Data graph',
    ja: 'データグラフ（高速に読むための事前結合ビュー）',
    def: 'A precomputed, denormalised view that joins a profile with its related DMOs and insights into one JSON-shaped record, so an application can read everything about a customer in a single low-latency call.',
    def_ja: 'プロファイルと関連する DMO・インサイトを1つの JSON 形のレコードに事前結合したビュー。アプリケーションが顧客に関するすべてを1回の低遅延な呼び出しで読める。',
    tip: 'The answer for real-time personalisation and for grounding Agentforce or prompts with customer context. It is for reading, not for segmentation.',
    tip_ja: 'リアルタイムのパーソナライゼーションや、Agentforce・プロンプトを顧客コンテキストでグラウンディングするための答え。読み取り用で、セグメント用ではない。',
    vs: ['calculated-insight', 'grounding'],
  },
  {
    id: 'query-api',
    cat: 'insights',
    term: 'Query API / Query Editor (SQL)',
    ja: 'クエリ API・クエリエディタ（SQL で Data 360 を照会）',
    def: 'Ways to run ANSI SQL against DLOs, DMOs and insights. Query Editor is the in-app workspace; the Query API is the programmatic interface for external systems.',
    def_ja: 'DLO・DMO・インサイトに対して ANSI SQL を実行する手段。クエリエディタはアプリ内の作業画面、クエリ API は外部システムからのプログラム用インターフェース。',
    tip: 'Data 360 is queried with SQL, not SOQL. For a single profile at low latency, a data graph or the Profile API is better than an ad hoc query.',
    tip_ja: 'Data 360 は SOQL ではなく SQL でクエリする。1人分のプロファイルを低遅延で取るなら、その場のクエリより Data Graph や Profile API が適する。',
    vs: ['data-explorer', 'data-graph'],
  },
  {
    id: 'data-explorer',
    cat: 'insights',
    term: 'Data Explorer / Profile Explorer',
    ja: 'データエクスプローラ／プロファイルエクスプローラ',
    def: 'Built-in viewers. Data Explorer shows the records in a DLO, DMO or calculated insight. Profile Explorer shows one unified profile with its source records and related data.',
    def_ja: '組み込みの閲覧画面。データエクスプローラは DLO・DMO・Calculated Insight のレコードを表示する。プロファイルエクスプローラは統合プロファイル1件を、元のソースレコードや関連データとあわせて表示する。',
    tip: 'First stop for troubleshooting: "did the data land?" → Data Explorer; "did this person unify correctly?" → Profile Explorer.',
    tip_ja: 'トラブルシューティングの最初の一手。「データは入ったか」→ データエクスプローラ、「この人は正しく統合されたか」→ プロファイルエクスプローラ。',
    vs: ['query-api'],
  },
  {
    id: 'enrichment',
    cat: 'insights',
    term: 'Copy Field enrichment / Related List enrichment',
    ja: 'エンリッチメント（Data 360 のデータを CRM レコードに表示）',
    def: 'Ways to surface Data 360 data on CRM records. Copy Field enrichment writes selected DMO or insight values into fields on a CRM object (such as Contact). Related List enrichment shows related Data 360 records as a related list on the record page.',
    def_ja: 'Data 360 のデータを CRM レコード上に見せる手段。Copy Field は選んだ DMO やインサイトの値を CRM オブジェクト（取引先責任者など）の項目へ書き込む。Related List は関連する Data 360 のレコードを、レコードページの関連リストとして表示する。',
    tip: 'Copy Field when the value must be usable in CRM reports, flows or formulas; Related List when agents just need to see the history.',
    tip_ja: '値を CRM のレポート・フロー・数式で使う必要があるなら Copy Field。担当者が履歴を見られればよいなら Related List。',
    vs: ['data-action'],
  },
  {
    id: 'einstein-studio',
    cat: 'insights',
    term: 'Einstein Studio / Model Builder',
    ja: 'Einstein Studio（予測モデルの作成・接続）',
    def: 'The workspace for predictive AI on Data 360 data: build a model with clicks, or connect an externally trained model. Predictions are written back so they can be used in segments, flows and records.',
    def_ja: 'Data 360 のデータで予測AI を扱う作業画面。クリック操作でモデルを作るか、外部で学習したモデルを接続する。予測結果は書き戻され、セグメント・フロー・レコードで使える。',
    tip: 'Predictive writes something back (a score); generative reads context at prompt time and writes nothing back.',
    tip_ja: '予測AI は結果（スコア）を書き戻す。生成AI はプロンプト実行時にコンテキストを読むだけで何も書き戻さない。',
    vs: ['byom', 'grounding'],
  },
  {
    id: 'byom',
    cat: 'insights',
    term: 'BYOM / BYOLLM (Bring Your Own Model / LLM)',
    ja: '自社モデルの持ち込み',
    def: 'Connecting a model hosted on an external platform — Amazon SageMaker, Google Vertex AI, Databricks — to Data 360 without moving the data. BYOLLM does the same for large language models used by generative features.',
    def_ja: '外部基盤（Amazon SageMaker、Google Vertex AI、Databricks）にあるモデルを、データを動かさずに Data 360 へ接続すること。BYOLLM は生成AI 機能で使う大規模言語モデルについて同じことを行う。',
    tip: 'The answer when a data science team already has a trained model and wants its predictions in Data 360.',
    tip_ja: 'データサイエンスチームに学習済みモデルがあり、その予測を Data 360 で使いたい設問の答え。',
    vs: ['einstein-studio', 'data-share'],
  },
  {
    id: 'grounding',
    cat: 'insights',
    term: 'Grounding',
    ja: 'グラウンディング（AI に根拠となるデータを渡す）',
    def: 'Supplying a generative AI prompt with real, relevant customer data at run time so the answer is based on facts rather than the model\'s general knowledge. Data 360 provides grounding through data graphs and retrievers.',
    def_ja: '生成AI のプロンプト実行時に、実在する関連顧客データを渡し、モデルの一般知識ではなく事実に基づいて回答させること。Data 360 は Data Graph と Retriever でグラウンディングを提供する。',
    tip: 'Grounding on an un-unified profile gives the model only a fragment of the customer — a reason unification matters to AI.',
    tip_ja: '統合されていないプロファイルでグラウンディングすると、モデルには顧客の断片しか渡らない。統合が AI にとって重要な理由。',
    vs: ['retriever', 'data-graph'],
  },
  {
    id: 'search-index',
    cat: 'insights',
    term: 'Search index / Vector database',
    ja: '検索インデックス（ベクトルデータベース）',
    def: 'The index built from unstructured data (PDFs, knowledge articles, transcripts). Content is split into chunks and converted into vector embeddings so it can be searched by meaning. Hybrid search combines vector and keyword search.',
    def_ja: '非構造化データ（PDF、ナレッジ記事、通話記録）から作るインデックス。コンテンツをチャンク（断片）に分割し、ベクトル埋め込みに変換して意味で検索できるようにする。ハイブリッド検索はベクトル検索とキーワード検索を組み合わせる。',
    tip: 'Unstructured data flows: ingest → unstructured DLO/DMO → chunk → embed → search index → retriever.',
    tip_ja: '非構造化データの流れ：取り込み → 非構造化 DLO／DMO → チャンク化 → 埋め込み → 検索インデックス → Retriever。',
    vs: ['retriever'],
  },
  {
    id: 'retriever',
    cat: 'insights',
    term: 'Retriever',
    ja: 'リトリーバー（RAG の検索担当）',
    def: 'The component that performs the retrieval step of retrieval-augmented generation (RAG): given a question, it searches a search index and returns the most relevant chunks to add to the prompt.',
    def_ja: 'RAG（検索拡張生成）の検索段階を担う部品。質問を受けて検索インデックスを検索し、最も関連する断片を返してプロンプトに加える。',
    tip: 'Agentforce agents and prompt templates reference retrievers to answer from company content. Structured customer context comes from data graphs instead.',
    tip_ja: 'Agentforce のエージェントやプロンプトテンプレートは、社内コンテンツから答えるために Retriever を参照する。構造化された顧客コンテキストは Data Graph から取る。',
    vs: ['search-index', 'grounding'],
  },
  {
    id: 'dc-reports',
    cat: 'insights',
    term: 'Data 360 reports & dashboards',
    ja: 'Data 360 のレポートとダッシュボード',
    def: 'Standard Salesforce reports built on Data 360 report types (DMOs, calculated insights, segments). Tableau and CRM Analytics can also connect directly to Data 360 for deeper analysis.',
    def_ja: 'Data 360 のレポートタイプ（DMO、Calculated Insight、セグメント）を使った標準の Salesforce レポート。より深い分析には Tableau や CRM Analytics から Data 360 へ直接接続できる。',
    tip: 'Data 360 data is reported on in place — it does not need to be copied into CRM objects first.',
    tip_ja: 'Data 360 のデータはその場でレポートできる。先に CRM オブジェクトへコピーする必要はない。',
    vs: ['enrichment'],
  },

  // ================= セグメント・アクティベーション =================
  {
    id: 'segment',
    cat: 'activation',
    term: 'Segment',
    ja: 'セグメント（条件で切り出した対象者の集団）',
    def: 'A group of profiles defined by filter criteria on attributes, related engagement data and insights — for example "unified individuals in Japan who bought in the last 90 days and have LTV over ¥100,000".',
    def_ja: '属性・関連するエンゲージメントデータ・インサイトへの条件で定義したプロファイルの集団。例：「日本在住で、過去90日に購入があり、LTV が10万円を超える統合個人」。',
    tip: 'A segment only defines WHO. Sending them anywhere is activation, which is a separate step.',
    tip_ja: 'セグメントが決めるのは「誰か」だけ。どこかへ送るのはアクティベーションで、別の工程。',
    vs: ['activation', 'segment-on'],
  },
  {
    id: 'segment-on',
    cat: 'activation',
    term: 'Segment On (segment entity)',
    ja: 'セグメント対象（何の単位で集団を作るか）',
    def: 'The DMO a segment counts and returns — normally Unified Individual, but it can be Unified Account (B2B) or another profile-category DMO. Every filter is evaluated relative to this entity.',
    def_ja: 'セグメントが数え、返す単位となる DMO。通常は Unified Individual だが、Unified Account（B2B）や他のプロファイル系 DMO も選べる。すべての条件はこの単位を基準に評価される。',
    tip: '"The segment count is higher than the number of real customers" → it is segmenting on Individual rather than Unified Individual.',
    tip_ja: '「セグメントの件数が実際の顧客数より多い」→ Unified Individual ではなく Individual を対象にしている。',
    vs: ['unified-individual', 'segment'],
  },
  {
    id: 'segment-builder',
    cat: 'activation',
    term: 'Segment canvas / Container',
    ja: 'セグメントキャンバスとコンテナ',
    def: 'The segment builder where you drag attributes into containers. A container groups conditions on one related object; conditions inside a container are evaluated on the same related record.',
    def_ja: '属性をコンテナへドラッグしてセグメントを作る画面。コンテナは1つの関連オブジェクトに対する条件をまとめたもので、コンテナ内の条件は同じ関連レコードに対して評価される。',
    tip: '"Bought product A AND over ¥10,000 in the same order" → one container. Two separate containers mean the conditions can be met by different orders.',
    tip_ja: '「同じ注文で商品 A を買い、かつ1万円超」→ 1つのコンテナに入れる。コンテナを分けると、別々の注文で条件を満たしてもよい意味になる。',
    vs: ['segment'],
  },
  {
    id: 'nested-segment',
    cat: 'activation',
    term: 'Nested segment / Exclusion',
    ja: 'ネストしたセグメント・除外',
    def: 'Reusing an existing segment as a filter inside another (include members of segment X), or excluding its members (everyone except current customers). Exclusion is how suppression lists are built.',
    def_ja: '既存のセグメントを別のセグメントの条件として再利用する（セグメント X のメンバーを含める）、またはそのメンバーを除外する（既存顧客以外すべて）こと。除外によってサプレッション（配信停止）リストを作る。',
    tip: 'Suppressing existing customers from acquisition ads is one of the most common exam scenarios.',
    tip_ja: '獲得広告の配信対象から既存顧客を除外するシナリオは、試験で最もよく出るものの1つ。',
    vs: ['waterfall-segment'],
  },
  {
    id: 'waterfall-segment',
    cat: 'activation',
    term: 'Waterfall segment',
    ja: 'ウォーターフォールセグメント（優先順位で振り分け）',
    def: 'A set of prioritised segments in which each person falls into only the first segment they qualify for. It prevents one customer from receiving several overlapping campaigns.',
    def_ja: '優先順位を付けたセグメントの組で、各人は条件を満たす最初のセグメントにだけ入る。1人の顧客が重なり合う複数のキャンペーンを受け取るのを防ぐ。',
    tip: 'The answer when overlapping segments must be mutually exclusive by priority.',
    tip_ja: '重なるセグメントを優先順位で互いに排他にしたい、という設問の答え。',
    vs: ['nested-segment'],
  },
  {
    id: 'publish-schedule',
    cat: 'activation',
    term: 'Segment publish: Standard / Rapid / Real-time',
    ja: 'セグメントの公開（標準／ラピッド／リアルタイム）',
    def: 'Publishing recalculates membership and sends it to activation targets. Standard publish runs on a schedule of hours. Rapid publish refreshes more frequently but only looks back over recent engagement data. Real-time segments evaluate as events arrive, for use cases such as web personalisation.',
    def_ja: '公開はメンバーを再計算してアクティベーションターゲットへ送る処理。標準の公開は数時間単位のスケジュールで実行。ラピッドパブリッシュはより頻繁に更新するが、直近のエンゲージメントデータしか参照しない。リアルタイムセグメントはイベント到着時に評価され、Web のパーソナライゼーションなどに使う。',
    tip: 'Faster publish costs more credits. Choose the slowest schedule the use case tolerates.',
    tip_ja: '更新が速いほどクレジットを多く消費する。ユースケースが許す範囲で最も遅いスケジュールを選ぶ。',
    vs: ['activation'],
  },
  {
    id: 'activation',
    cat: 'activation',
    term: 'Activation',
    ja: 'アクティベーション（セグメントを外部へ届ける）',
    def: 'Sending a segment\'s members — with selected contact points and attributes — to an activation target such as Marketing Cloud Engagement, an ad platform or cloud storage, where the campaign actually runs.',
    def_ja: 'セグメントのメンバーを、選んだコンタクトポイントと属性とあわせて、Marketing Cloud Engagement・広告プラットフォーム・クラウドストレージなどのアクティベーションターゲットへ送ること。実際の施策はそこで実行される。',
    tip: 'Segment = who; activation target = where; activation = who + what data + where. Activation respects consent and can include direct and related attributes.',
    tip_ja: 'セグメント＝誰に、アクティベーションターゲット＝どこへ、アクティベーション＝誰に＋どのデータを＋どこへ。アクティベーションは同意を尊重し、直接属性と関連属性を含められる。',
    vs: ['segment', 'data-action', 'activation-target'],
  },
  {
    id: 'activation-target',
    cat: 'activation',
    term: 'Activation target',
    ja: 'アクティベーションターゲット（送り先の設定）',
    def: 'The configured destination for activations — Marketing Cloud Engagement, Marketing Cloud Personalization, Amazon S3, Google Cloud Storage, Azure, and advertising platforms such as Meta, Google and Amazon Ads.',
    def_ja: 'アクティベーションの送り先として設定したもの。Marketing Cloud Engagement、Marketing Cloud Personalization、Amazon S3、Google Cloud Storage、Azure、Meta・Google・Amazon Ads などの広告プラットフォーム。',
    tip: 'Set the target up once; many activations can reuse it. The target must exist before you can activate a segment to it.',
    tip_ja: 'ターゲットは一度設定すれば多数のアクティベーションで再利用できる。セグメントを送るには先にターゲットを作っておく必要がある。',
    vs: ['activation', 'data-action-target'],
  },
  {
    id: 'activation-attributes',
    cat: 'activation',
    term: 'Direct attributes vs Related attributes',
    ja: '直接属性と関連属性',
    def: 'Data added to an activation beyond the member list. Direct attributes have one value per person (first name, loyalty tier). Related attributes come from one-to-many objects (the last three orders, items in cart).',
    def_ja: 'アクティベーションでメンバー一覧に加えて送るデータ。直接属性は1人につき1つの値（名、会員ランク）。関連属性は1対多のオブジェクトから取る（直近3件の注文、カート内の商品）。',
    tip: 'Personalising an email with "your recent purchases" requires related attributes.',
    tip_ja: '「最近のご購入商品」でメールをパーソナライズするには関連属性が必要。',
    vs: ['activation'],
  },
  {
    id: 'data-action',
    cat: 'activation',
    term: 'Data action',
    ja: 'データアクション（条件を満たした瞬間に通知する）',
    def: 'A rule that fires when a record changes or a streaming insight meets a condition, and sends an event to a data action target — a Salesforce Platform Event, a webhook or Marketing Cloud.',
    def_ja: 'レコードが変化したとき、または Streaming Insight が条件を満たしたときに発火し、データアクションターゲット（Salesforce のプラットフォームイベント、Webhook、Marketing Cloud）へイベントを送るルール。',
    tip: 'Activation = scheduled batch of a segment to a channel. Data action = event-driven, per-record, near real time. "Alert when a high-value cart is abandoned" → data action.',
    tip_ja: 'アクティベーション＝セグメントをチャネルへ定期的に一括送信。データアクション＝レコード単位でイベント駆動・準リアルタイム。「高額カートが放棄されたら通知」→ データアクション。',
    vs: ['activation', 'streaming-insight', 'dc-flow'],
  },
  {
    id: 'data-action-target',
    cat: 'activation',
    term: 'Data action target',
    ja: 'データアクションターゲット',
    def: 'The destination a data action sends its event to: a Salesforce Platform Event (to start a flow or Apex in core), a webhook to an external system, or Marketing Cloud (to start a journey).',
    def_ja: 'データアクションがイベントを送る先。Salesforce のプラットフォームイベント（コアでフローや Apex を起動）、外部システムへの Webhook、Marketing Cloud（ジャーニーを開始）。',
    tip: 'Do not confuse with activation targets — they are configured separately and serve different patterns.',
    tip_ja: 'アクティベーションターゲットと混同しないこと。設定場所も用途も別。',
    vs: ['activation-target'],
  },
  {
    id: 'dc-flow',
    cat: 'activation',
    term: 'Data Cloud-triggered flow',
    ja: 'Data 360 トリガーのフロー',
    def: 'A Salesforce flow that starts when a Data 360 DMO or calculated insight record changes, allowing CRM automation — create a task, update a record — in response to unified data.',
    def_ja: 'Data 360 の DMO や Calculated Insight のレコードが変化したときに起動する Salesforce フロー。統合データに反応して、ToDo 作成やレコード更新などの CRM 自動化を行える。',
    tip: 'Inside Salesforce → Data Cloud-triggered flow (or data action → platform event → flow). Outside Salesforce → data action with a webhook.',
    tip_ja: 'Salesforce の中で動かす → Data 360 トリガーのフロー（またはデータアクション → プラットフォームイベント → フロー）。外部で動かす → Webhook のデータアクション。',
    vs: ['data-action'],
  },
  {
    id: 'consent',
    cat: 'activation',
    term: 'Consent management',
    ja: '同意管理',
    def: 'Tracking what each person has agreed to — by channel, purpose and subscription — using consent DMOs such as Contact Point Consent, and applying it as a filter so activations reach only people who opted in.',
    def_ja: '各人が何に同意したかを、チャネル・目的・購読ごとに Contact Point Consent などの同意用 DMO で管理し、アクティベーションでは同意した人にだけ届くよう絞り込みに使うこと。',
    tip: 'Consent must be enforced at activation. Technical ability to reach someone is never permission to do so.',
    tip_ja: '同意はアクティベーション時に必ず適用する。技術的に届けられることは、届けてよいことを意味しない。',
    vs: ['privacy-requests'],
  },

  // ================= 設定・ガバナンス =================
  {
    id: 'provisioning',
    cat: 'admin',
    term: 'Provisioning',
    ja: 'プロビジョニング（Data 360 の有効化）',
    def: 'The one-time setup that creates the Data 360 instance attached to an org, including choosing the region. After provisioning, admins assign permission sets and configure connectors.',
    def_ja: '組織に紐づく Data 360 のインスタンスを作る一度きりのセットアップ。リージョンの選択を含む。その後、管理者が権限セットを割り当て、コネクタを設定する。',
    tip: 'Setup order: provision → assign permission sets → connect sources → create streams → map → identity resolution → insights → segments → activation.',
    tip_ja: '設定の順序：プロビジョニング → 権限セット割り当て → ソース接続 → ストリーム作成 → マッピング → ID解決 → インサイト → セグメント → アクティベーション。',
    vs: ['hyperforce'],
  },
  {
    id: 'permission-sets',
    cat: 'admin',
    term: 'Data 360 permission sets',
    ja: 'Data 360 の権限セット',
    def: 'Standard permission sets that define what a user can do: Data Cloud Architect / Admin (full setup), Marketing Manager (segments and activations end to end), Marketing Specialist (build segments), Data Aware Specialist (data work such as streams and mapping), and User (view).',
    def_ja: 'ユーザーが何をできるかを決める標準の権限セット。Data Cloud Architect／Admin（設定全般）、Marketing Manager（セグメントとアクティベーションを一通り）、Marketing Specialist（セグメント作成）、Data Aware Specialist（ストリームやマッピングなどのデータ作業）、User（閲覧）。',
    tip: 'Pick the least-privileged set that covers the task. Permission set = what they can do; data space = which data they can do it to.',
    tip_ja: '作業をカバーする最小権限の権限セットを選ぶ。権限セット＝何ができるか、データスペース＝どのデータに対してできるか。',
    vs: ['data-space'],
  },
  {
    id: 'data-space',
    cat: 'admin',
    term: 'Data space',
    ja: 'データスペース（データを論理的に分ける区画）',
    def: 'A logical partition of data, metadata and processes inside one Data 360 instance — for example one per brand, region or business unit. Each has its own mappings, identity resolution, insights and segments, and users are granted access per data space.',
    def_ja: '1つの Data 360 インスタンスの中で、データ・メタデータ・処理を論理的に区切ったもの（ブランド・地域・事業部ごとなど）。それぞれが独自のマッピング、ID解決、インサイト、セグメントを持ち、ユーザーにはデータスペース単位でアクセス権を与える。',
    tip: '"Brand A marketers must not see brand B customers" → separate data spaces (plus permission sets). Every org starts with a default data space.',
    tip_ja: '「ブランド A の担当者にブランド B の顧客を見せてはならない」→ データスペースを分ける（＋権限セット）。どの組織にも最初から default のデータスペースがある。',
    vs: ['permission-sets', 'home-org'],
  },
  {
    id: 'data-space-filter',
    cat: 'admin',
    term: 'Data space filter',
    ja: 'データスペースフィルタ',
    def: 'A filter on a DLO that decides which of its records flow into a particular data space — for example only rows where Brand = "A".',
    def_ja: 'DLO のどのレコードを特定のデータスペースに流すかを決める条件（ブランド＝A の行だけ、など）。',
    tip: 'One stream can feed several data spaces with different filters; you do not need to ingest the source twice.',
    tip_ja: '1つのストリームを条件の異なる複数のデータスペースへ流せる。ソースを二重に取り込む必要はない。',
    vs: ['data-space'],
  },
  {
    id: 'data-kit',
    cat: 'admin',
    term: 'Data kit',
    ja: 'データキット（設定を組織間で移すための入れ物）',
    def: 'A container that packages Data 360 metadata — data stream definitions, mappings, calculated insights, segments — so it can be deployed to another org through packages, change sets or DevOps tooling.',
    def_ja: 'Data 360 のメタデータ（データストリーム定義、マッピング、Calculated Insight、セグメント）を梱包し、パッケージ・変更セット・DevOps ツールで別の組織へ展開できるようにする入れ物。',
    tip: 'Moving configuration from a sandbox to production → data kit. It carries metadata only, never the customer data itself.',
    tip_ja: 'Sandbox から本番へ設定を移す → データキット。運ぶのはメタデータだけで、顧客データそのものは運ばない。',
    vs: ['data-bundle', 'sandbox'],
  },
  {
    id: 'sandbox',
    cat: 'admin',
    term: 'Data 360 sandbox',
    ja: 'Data 360 の Sandbox',
    def: 'A sandbox org with its own Data 360 environment for building and testing configuration without affecting production. Configuration is promoted with data kits.',
    def_ja: '本番に影響を与えずに設定を作成・テストするための、独自の Data 360 環境を持つ Sandbox 組織。設定はデータキットで昇格させる。',
    tip: 'Development lifecycle questions: build in sandbox → package in a data kit → deploy → validate in production.',
    tip_ja: '開発ライフサイクルの設問：Sandbox で作る → データキットで梱包 → 展開 → 本番で検証。',
    vs: ['data-kit'],
  },
  {
    id: 'privacy-requests',
    cat: 'admin',
    term: 'Data deletion & privacy requests',
    ja: '削除要求・プライバシー要求への対応',
    def: 'Handling individuals\' rights such as the right to be forgotten or to restrict processing. Data 360 provides a consent/data-deletion API that removes the person\'s data across Data 360, including from unified profiles.',
    def_ja: '忘れられる権利や処理制限の権利など、本人の権利への対応。Data 360 には、統合プロファイルを含め Data 360 全体からその人のデータを削除する、同意・データ削除用の API がある。',
    tip: 'Deleting the record in one source system is not enough — use the Data 360 deletion request so every copy and unified profile is removed.',
    tip_ja: '1つのソースシステムでレコードを削除するだけでは不十分。Data 360 の削除要求を使い、すべての複製と統合プロファイルから消す。',
    vs: ['consent'],
  },
]

export const glossaryById = Object.fromEntries(glossary.map((t) => [t.id, t]))
