// Service Cloud Consultant 用のフラッシュカード。表裏とも英日を併記し、カードごとに切り替えられる。
export const flashcards = [
  {
    id: 'sc-fc-1',
    domain: 'sc-implementation',
    front: 'A stakeholder raises a new requirement during design. What is the correct first step?',
    front_ja: '設計中にステークホルダーが新しい要件を提示した。正しい最初の手順は？',
    back: 'Document it and evaluate the impact on scope, timeline and cost — then the sponsor decides. Never build immediately; never defer without analysis.',
    back_ja: '文書化し、スコープ・スケジュール・コストへの影響を評価する。判断はスポンサーが行う。ただちに構築しない。分析せずに先送りもしない。',
  },
  {
    id: 'sc-fc-2',
    domain: 'sc-implementation',
    front: 'The four sandbox types — what does each contain?',
    front_ja: '4つのサンドボックス種別 — それぞれ何を含む？',
    back: 'Developer: metadata only, small. Developer Pro: metadata only, larger. Partial Copy: metadata + sample data. Full: complete production copy including all data.',
    back_ja: 'Developer：メタデータのみ・小。Developer Pro：メタデータのみ・大きめ。Partial Copy：メタデータ＋サンプルデータ。Full：全データを含む本番の完全コピー。',
  },
  {
    id: 'sc-fc-3',
    domain: 'sc-implementation',
    front: 'Which sandbox for performance testing, and why?',
    front_ja: 'パフォーマンステストにはどのサンドボックス？その理由は？',
    back: 'Full Sandbox — only it reproduces production data volume and distribution. Loading extra data into a Partial Copy does not.',
    back_ja: 'Full Sandbox。本番のデータ量と分布を再現できるのはこれだけ。Partial Copy に追加データを読み込んでも再現できない。',
  },
  {
    id: 'sc-fc-4',
    domain: 'sc-implementation',
    front: 'A change set fails: a validation rule references a field not in the target org. Cause?',
    front_ja: '変更セットが失敗し、入力規則が対象組織にない項目を参照しているとエラーが出た。原因は？',
    back: 'The field was omitted — change sets do not gather dependencies automatically. Add it, and deploy objects and fields before the rules and flows referencing them.',
    back_ja: '項目が漏れている。変更セットは依存関係を自動収集しない。項目を追加し、それを参照する規則やフローより先にオブジェクトと項目をデプロイする。',
  },
  {
    id: 'sc-fc-5',
    domain: 'sc-implementation',
    front: 'UAT shows the build does not match the approved design. What do you do?',
    front_ja: 'UAT で構築内容が承認済み設計と一致しないと判明した。どうする？',
    back: 'It is a defect: fix the configuration and retest. Do not rewrite the documentation, do not ask agents to adapt, do not escalate a plain build defect.',
    back_ja: 'これは不具合。構成を修正して再テストする。文書を書き換えない、担当者に合わせてもらわない、単なる構築不具合をエスカレーションしない。',
  },
  {
    id: 'sc-fc-6',
    domain: 'sc-solution',
    front: 'Product vs Asset vs Contract vs Entitlement',
    front_ja: 'Product・Asset・Contract・Entitlement の違いは？',
    back: 'Product = what you sell (model/SKU). Asset = the individual unit a customer owns, holding its service history. Contract = commercial terms. Entitlement = the level of support due.',
    back_ja: 'Product＝販売するもの（型番／SKU）。Asset＝顧客が所有する個体で、そのサービス履歴を保持。Contract＝商取引条件。Entitlement＝受けられるサポートのレベル。',
  },
  {
    id: 'sc-fc-7',
    domain: 'sc-solution',
    front: 'Which licence for internal staff who only read case data?',
    front_ja: 'ケースデータを参照するだけの社内職員に適したライセンスは？',
    back: 'Salesforce Platform — the cost-effective internal option. Service Cloud User is for agents who work cases; Chatter Free has no CRM record access.',
    back_ja: 'Salesforce Platform。コスト効率の良い社内向け選択肢。Service Cloud User はケースを処理する担当者向け、Chatter Free は CRM レコードにアクセスできない。',
  },
  {
    id: 'sc-fc-8',
    domain: 'sc-solution',
    front: 'Customer Community vs Customer Community Plus vs Partner Community',
    front_ja: 'Customer Community・Customer Community Plus・Partner Community の使い分けは？',
    back: 'Customer Community: high-volume B2C, submit and track cases, read knowledge. Plus: adds roles, sharing and reports. Partner: channel partners needing sales objects.',
    back_ja: 'Customer Community：大量B2C、ケースの起票・追跡、ナレッジ閲覧。Plus：ロール・共有・レポートを追加。Partner：営業オブジェクトが必要なチャネルパートナー。',
  },
  {
    id: 'sc-fc-9',
    domain: 'sc-solution',
    front: 'How do you stop portal guests seeing other customers\' cases?',
    front_ja: 'ポータルのゲストに他の顧客のケースを見せないようにするには？',
    back: 'Set the Case org-wide default to Private. OWD is the floor; sharing rules and permission sets only ever widen access, never restrict it.',
    back_ja: 'Case の組織の共有設定を「非公開」にする。OWD が下限であり、共有ルールと権限セットはアクセスを広げる方向にしか働かない。',
  },
  {
    id: 'sc-fc-10',
    domain: 'sc-solution',
    front: 'Assignment rules vs skills-based routing vs escalation rules',
    front_ja: '割り当てルール・スキルベースルーティング・エスカレーションルールの使い分けは？',
    back: 'Assignment: routes on a record attribute known at creation (e.g. account tier). Skills: matches agent capabilities (language, product). Escalation: time-based reassignment, one active rule per object.',
    back_ja: '割り当て：作成時に判明しているレコード属性（取引先区分など）でルーティング。スキル：担当者の能力（言語、製品）で突合。エスカレーション：時間ベースの再割り当てで、オブジェクトごとに有効化できるのは1つ。',
  },
  {
    id: 'sc-fc-11',
    domain: 'sc-case',
    front: 'When do you need entitlements rather than an escalation rule?',
    front_ja: 'エスカレーションルールではなくエンタイトルメントが必要なのはどんなとき？',
    back: 'When tiers have different commitments and someone must be warned before breach. A single uniform rule ("escalate everything after 72 hours") is an escalation rule.',
    back_ja: '区分ごとにコミットメントが異なり、違反前に警告が必要なとき。「区分に関係なく72時間で全件エスカレーション」のような一律のルールはエスカレーションルール。',
  },
  {
    id: 'sc-fc-12',
    domain: 'sc-case',
    front: 'Milestones do not appear on cases. What do you check first?',
    front_ja: 'ケースにマイルストーンが表示されない。まず何を確認する？',
    back: 'Whether the entitlement process is actually applied to the case. Then whether the entitlement is associated with the account/asset/contract, then timing relative to activation.',
    back_ja: 'ケースにエンタイトルメントプロセスが実際に適用されているか。次に取引先／納入品／契約にエンタイトルメントが関連付けられているか、最後に有効化との時間関係。',
  },
  {
    id: 'sc-fc-13',
    domain: 'sc-case',
    front: 'Send a survey 24 hours after a case is closed — which tool?',
    front_ja: 'ケースのクローズ24時間後にアンケートを送る — どのツール？',
    back: 'A record-triggered flow with a scheduled path. Escalation rules act on open cases only; a macro needs a manual trigger; a template has no scheduling of its own.',
    back_ja: 'スケジュールパス付きのレコードトリガーフロー。エスカレーションルールは未解決ケースのみに作用し、マクロは手動起動が必要、テンプレート自体にスケジュール機能はない。',
  },
  {
    id: 'sc-fc-14',
    domain: 'sc-case',
    front: 'What is the Web-to-Case daily limit, and what happens above it?',
    front_ja: 'Web-to-Case の1日あたりの上限と、超過時の挙動は？',
    back: 'A default of 5,000 cases per day. Excess submissions simply do not create cases — the failure is silent and customer requests are lost.',
    back_ja: '既定で1日5,000件。超過分はケースを作成せず、失敗は無言で起きて顧客の依頼が失われる。',
  },
  {
    id: 'sc-fc-15',
    domain: 'sc-case',
    front: '"Enforce" vs "guide" — which mechanism for each?',
    front_ja: '「強制する」と「案内する」— それぞれどの仕組み？',
    back: 'Enforce/must/prevent → validation rule (it blocks the save). Guide/remind/suggest → flow screen, path guidance or an alert. A required field forces a value, not a meaningful one.',
    back_ja: '強制／必須／防ぐ→入力規則（保存をブロックする）。案内／促す／提案→画面フロー、パスのガイダンス、アラート。必須項目は値の入力を強制するが、意味のある値とは限らない。',
  },
  {
    id: 'sc-fc-16',
    domain: 'sc-channels',
    front: 'On-Demand vs On-Premises Email-to-Case',
    front_ja: 'On-Demand と On-Premises の Email-to-Case の違いは？',
    back: 'On-Demand routes email through Salesforce servers. On-Premises runs an email agent behind the company firewall, so message data never leaves internal servers — the answer for regulatory constraints.',
    back_ja: 'On-Demand はメールが Salesforce のサーバーを経由する。On-Premises は自社ファイアウォール内でメールエージェントを動かし、メッセージデータが社内から出ない。規制上の制約がある場合の答え。',
  },
  {
    id: 'sc-fc-17',
    domain: 'sc-channels',
    front: 'Customer replies create new cases instead of updating existing ones. Fix?',
    front_ja: '顧客の返信が既存ケースを更新せず新規ケースを作ってしまう。対処は？',
    back: 'Configure email threading via the subject line or email headers. Header-based threading is more robust because customers often edit the subject.',
    back_ja: '件名またはメールヘッダーによるスレッド化を構成する。顧客は件名を書き換えることが多いため、ヘッダーによるスレッド化のほうが堅牢。',
  },
  {
    id: 'sc-fc-18',
    domain: 'sc-channels',
    front: 'Chat vs Messaging for In-App and Web',
    front_ja: 'チャットと Messaging for In-App and Web の違いは？',
    back: 'Chat is synchronous and session-bound. Messaging is asynchronous: the conversation persists across devices and sessions, so the customer can continue later with history intact.',
    back_ja: 'チャットは同期かつセッションに紐づく。メッセージングは非同期で、デバイスとセッションをまたいで会話が保持され、履歴を保ったまま後から続けられる。',
  },
  {
    id: 'sc-fc-19',
    domain: 'sc-channels',
    front: 'An Einstein Bot cannot resolve the issue. What happens?',
    front_ja: 'Einstein Bot が問題を解決できない場合、何が起きる？',
    back: 'The conversation transfers to a live agent within the same session, so the agent inherits the transcript and the context the bot collected.',
    back_ja: '同一セッション内で有人担当者へ会話が転送され、担当者はトランスクリプトとボットが収集した文脈を引き継ぐ。',
  },
  {
    id: 'sc-fc-20',
    domain: 'sc-channels',
    front: 'Open CTI vs Service Cloud Voice',
    front_ja: 'Open CTI と Service Cloud Voice の違いは？',
    back: 'Open CTI with a vendor adapter integrates an existing phone system (e.g. Cisco) into the console. Service Cloud Voice is Salesforce-native telephony — the answer only when replacing the phone system.',
    back_ja: 'ベンダーアダプタを用いた Open CTI は既存の電話システム（Cisco など）をコンソールに統合する。Service Cloud Voice は Salesforce ネイティブの電話機能で、電話システムを置き換える場合の答え。',
  },
  {
    id: 'sc-fc-21',
    domain: 'sc-channels',
    front: 'Social Customer Service — which posts should NOT create cases?',
    front_ja: 'Social Customer Service — ケース化すべきでない投稿は？',
    back: 'Retweets of the company\'s own promotional posts — marketing engagement with no service request. DMs, complaints and replies to the support account should create cases.',
    back_ja: '自社の販促投稿のリツイート。サービス上の依頼を含まないマーケティングへの反応。DM、苦情、サポートアカウントへの返信はケース化する。',
  },
  {
    id: 'sc-fc-22',
    domain: 'sc-knowledge',
    front: 'What happens to a published article while it is being updated?',
    front_ja: '公開済み記事の更新中、その記事はどうなる？',
    back: 'It remains published and searchable while the new version goes through draft and review. It is replaced only when the new version is published — never unpublished, archived or deleted by editing.',
    back_ja: '新バージョンが下書きとレビューを経る間、公開・検索可能なまま維持される。新バージョンの公開時に置き換わるだけで、編集によって非公開化・アーカイブ・削除されることはない。',
  },
  {
    id: 'sc-fc-23',
    domain: 'sc-knowledge',
    front: 'Agents see some knowledge articles but not others. First check?',
    front_ja: '担当者に一部のナレッジ記事だけが表示されない。まず確認するのは？',
    back: 'Data category visibility settings against the agent profiles/roles. They filter silently. If NO Knowledge appears at all, check the Knowledge User licence or the page layout component instead.',
    back_ja: '担当者のプロファイル／ロールに対するデータカテゴリの表示設定。無言で絞り込む。ナレッジがまったく表示されない場合は、Knowledge User ライセンスまたはページレイアウトのコンポーネントを確認する。',
  },
  {
    id: 'sc-fc-24',
    domain: 'sc-knowledge',
    front: 'What is most central to KCS adoption?',
    front_ja: 'KCS の定着で最も中心となる実践は？',
    back: 'Agents search Knowledge before working a case and attach or create articles as part of the resolution workflow. Capture is a by-product of solving, and reuse comes before creating.',
    back_ja: '担当者がケース対応前にナレッジを検索し、解決の流れの中で記事を添付または作成すること。知識の蓄積は解決の副産物であり、作る前にまず再利用する。',
  },
  {
    id: 'sc-fc-25',
    domain: 'sc-knowledge',
    front: 'Surface relevant articles without the agent searching — which feature?',
    front_ja: '担当者が検索しなくても関連記事を表示する機能は？',
    back: 'Einstein Article Recommendations. Promoted search terms and data categories improve searching but still require a search. On a portal the same feature deflects cases before submission.',
    back_ja: 'Einstein Article Recommendations。プロモート検索語やデータカテゴリは検索を改善するが、検索が前提。ポータル上では同じ機能が送信前のケース回避に働く。',
  },
  {
    id: 'sc-fc-26',
    domain: 'sc-console',
    front: 'The softphone does not appear in Service Console. Most likely cause?',
    front_ja: 'サービスコンソールにソフトフォンが表示されない。最も可能性の高い原因は？',
    back: 'It has not been added to the utility bar. In Lightning, persistent tools (softphone, history, notes) live in the utility bar.',
    back_ja: 'ユーティリティバーに追加されていない。Lightning では常駐ツール（ソフトフォン、履歴、メモ）はユーティリティバーに置く。',
  },
  {
    id: 'sc-fc-27',
    domain: 'sc-console',
    front: 'Highlights Panel vs Related Records vs Utility Bar vs Split View',
    front_ja: 'ハイライトパネル・関連レコード・ユーティリティバー・分割ビューの違いは？',
    back: 'Highlights Panel: key fields of this record, pinned at the top. Related Records: other related records in a sidebar. Utility Bar: persistent app tools in the footer. Split View: a list alongside one record.',
    back_ja: 'ハイライトパネル：このレコードの主要項目を上部に固定。関連レコード：関連する他のレコードをサイドバーに表示。ユーティリティバー：フッターの常駐ツール。分割ビュー：一覧と1件の詳細を並べて表示。',
  },
  {
    id: 'sc-fc-28',
    domain: 'sc-console',
    front: 'Quick Text vs Quick Action vs Macro',
    front_ja: 'クイックテキスト・クイックアクション・マクロの違いは？',
    back: 'Quick Text inserts predefined text only. Quick Action performs one operation. Macro runs a multi-step sequence from one trigger — the answer when several steps must happen "with one click".',
    back_ja: 'クイックテキストは定型文の挿入のみ。クイックアクションは単一の操作。マクロは1回の実行で複数手順をまとめて行う。複数手順を「1クリックで」という要件の答え。',
  },
  {
    id: 'sc-fc-29',
    domain: 'sc-data',
    front: 'The four integration patterns',
    front_ja: '4つの連携パターンは？',
    back: 'Remote Call-In: external system calls into Salesforce. Request and Reply: Salesforce calls out and waits. Fire and Forget: calls out without waiting. Batch Data Sync: scheduled bulk movement.',
    back_ja: 'Remote Call-In：外部システムが Salesforce を呼ぶ。Request and Reply：Salesforce が呼び出して待つ。Fire and Forget：呼び出して待たない。Batch Data Sync：スケジュールされた一括移動。',
  },
  {
    id: 'sc-fc-30',
    domain: 'sc-data',
    front: 'Show live external data on the case without storing it in Salesforce. How?',
    front_ja: '外部データを Salesforce に保存せずケース上にライブ表示するには？',
    back: 'Salesforce Connect with an external object — read live at view time, nothing copied in. A nightly batch sync fails both the freshness and the no-storage requirement.',
    back_ja: '外部オブジェクトを用いた Salesforce Connect。閲覧時にライブで読み取り、何もコピーしない。夜間バッチ同期は鮮度と非保存の両方の要件に反する。',
  },
  {
    id: 'sc-fc-31',
    domain: 'sc-data',
    front: 'Why create an external ID before a large migration?',
    front_ja: '大規模移行の前に外部IDを作る理由は？',
    back: 'It enables upsert, so a restart after a failure updates already-loaded rows instead of duplicating them. Without it there is no matching key and Salesforce does not deduplicate automatically.',
    back_ja: 'upsert を可能にするため。失敗後の再実行が、すでに読み込まれた行を重複させずに更新できる。外部IDがなければ突合キーがなく、Salesforce は自動的に重複排除しない。',
  },
  {
    id: 'sc-fc-32',
    domain: 'sc-data',
    front: 'A custom index was requested. What else must be true for it to help?',
    front_ja: 'カスタムインデックスを依頼した。効かせるために他に必要な条件は？',
    back: 'Queries must actually filter on the indexed field and be selective — returning a small enough proportion of records. A non-selective filter makes the optimiser skip the index.',
    back_ja: 'クエリが実際にその項目で絞り込み、かつ選択的（十分に少ない割合のレコードを返す）であること。選択性が低いとオプティマイザはインデックスを使わない。',
  },
  {
    id: 'sc-fc-33',
    domain: 'sc-data',
    front: 'A bulk integration runs but the flow\'s emails are never sent. Why?',
    front_ja: '一括連携は実行されるのに、フローのメールが送信されない。なぜ？',
    back: 'The daily single-email limit was exhausted by the batch. Flows DO run during bulk DML — that misconception is a common distractor.',
    back_ja: 'バッチが1日あたりの単一メール送信上限を使い切った。フローは一括DML中も実行される。実行されないという誤解は頻出の誤答。',
  },
  {
    id: 'sc-fc-34',
    domain: 'sc-data',
    front: '1,000 cases created at once, each flow updating the same parent Account. Errors. Why?',
    front_ja: '1,000件のケースを同時作成し、各フローが同じ親取引先を更新するとエラーになる。なぜ？',
    back: 'Record locking from concurrent updates to the same parent. Reduce batch size, order the load by parent, or move the parent update to an asynchronous path.',
    back_ja: '同じ親への同時更新によるレコードロック。バッチサイズを縮小する、親ごとに並べ替える、親の更新を非同期化する。',
  },
  {
    id: 'sc-fc-35',
    domain: 'sc-analytics',
    front: 'Executive vs supervisor vs analyst — which artefact for each?',
    front_ja: '経営層・スーパーバイザー・アナリスト — それぞれどの成果物？',
    back: 'Executive: summary dashboard with trends. Supervisor: Omni-Channel Supervisor for live agent and queue status. Analyst: detailed report.',
    back_ja: '経営層：傾向を示すサマリーダッシュボード。スーパーバイザー：担当者とキューのリアルタイム状況を見る Omni-Channel Supervisor。アナリスト：詳細レポート。',
  },
  {
    id: 'sc-fc-36',
    domain: 'sc-analytics',
    front: 'How do you measure case deflection?',
    front_ja: 'ケース回避はどう測る？',
    back: 'Customers who viewed an article and did NOT create a case. Counting cases created through the portal measures the opposite.',
    back_ja: '記事を閲覧してケースを作成しなかった顧客数。ポータル経由で作成されたケース数を数えるのは逆の測定。',
  },
  {
    id: 'sc-fc-37',
    domain: 'sc-analytics',
    front: 'Knowledge adoption vs article effectiveness — which metric for each?',
    front_ja: 'ナレッジの定着度と記事の有効性 — それぞれどの指標？',
    back: 'Adoption: percentage of closed cases with an attached article. Effectiveness: percentage where the article was attached AND the case was not reopened.',
    back_ja: '定着度：記事が添付されたクローズ済みケースの割合。有効性：記事が添付され、かつ再オープンされなかった割合。',
  },
  {
    id: 'sc-fc-38',
    domain: 'sc-analytics',
    front: 'Average handle time including phone hold time — where does the data come from?',
    front_ja: '電話の保留時間を含む平均処理時間 — データの出所は？',
    back: 'The ACD telephony system. Hold time is measured by the phone platform; Salesforce never sees it unless it is integrated in.',
    back_ja: 'ACD 電話システム。保留時間は電話基盤側で計測され、連携しない限り Salesforce は観測しない。',
  },
]

export const flashcardsByDomain = (domainId) => flashcards.filter((f) => f.domain === domainId)
